### ISSUE TITLE
Validation Layer error in api sample swapchain_recreation

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#1003]
When starting the api sample swapchain_recreation, I get the following Validation Error, triggered in `SwapchainRecreation::acquire_next_image`:

`Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0xec4bec000000000b, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must not have any uncompleted signal or wait operations pending (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)`

Build with VS2022, run on NVIDIA GPU.

**Comment by SaschaWillems** [comment]
This is a false validation and has been fixed in the layers recently, but afair didn't make it into the SDK. If you compile validation from github, that error no longer shows up.

**Comment by SaschaWillems** [comment]
Retested with SDK 1.3.283 and I'm not seeing any validation. Closing this then.
