### ISSUE TITLE
clang-format script fails due to objective C files

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#1006]
I'm trying to fix some clang format problems on one of my branches, but I'm no longer able to run the clang-format script locally. It always errors out because it doesn't support objective-C files:

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/10283127/1aad21b8-ff35-405d-88d2-51f42fc6ae7a)

Is there a way to exclude these?

**Comment by jeroenbakker-atmind** [comment]
I can have a look at this.

The .clang-format config file only provides rules for CPP, `scripts/clang_format.py` has a filter that ignores none cpp files. Header files seems not to be ignored as they have the same extensions.
Will see if we can detect Objective-C header files, or we really need to have a blacklist
