### ISSUE TITLE
Link in Command buffers usage readme broken

### ISSUE THREAD

**Issue by wasimabbas-arm** [KhronosGroup/Vulkan-Samples#1018]
In the further reading section of https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/performance/command_buffer_usage/README.adoc 

<img width="1025" alt="Screenshot 2024-04-11 at 09 37 30" src="https://github.com/KhronosGroup/Vulkan-Samples/assets/17299876/bf79a99f-68b0-46da-96a8-668289b83b83">

The `Multi-threaded recording with multiple render passes` is using this `xref` markdown autolink, 

`* xref:samples/performance/multithreading_render_passes/README.adoc[Multi-threaded recording with multiple render passes]`

which is pointing at `https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/performance/command_buffer_usage/samples/performance/multithreading_render_passes/README.adoc` and that doesn't exist, you get a 404.

**Comment by SaschaWillems** [comment]
That's an unfortunate side-effect of getting thinks properly working with docs.vulkan.org. If you click the link on that site: https://docs.vulkan.org/samples/latest/samples/performance/command_buffer_usage/README.html#_further_reading it'll work properly.

Getting documentation to work both with github and antora isn't always easy but I'll try to take a look at it.

**Comment by SaschaWillems** [comment]
Closing this for now. There is sadly no easy fix with github's asciidoc support being kinda limited. We'll probably add a hint letting people know that the proper documentation should be viewed through docs.vulkan.org.
