### ISSUE TITLE
16 bit arithmetic sample crashes at startup

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#1024]
The 16 bit arithmetic sample is no longer working for me. Ot always crashes at start with the following error:

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/10283127/bb6b0ea8-1010-4caf-960a-cdb85e8c0cb0)

I can reproduce this on two different machines with windows, one with an RTX 4070 and another one with an integrated Intel GPU.

**Comment by gary-sweet** [comment]
This same assert is also being hit for me in lots of other samples. At least, subpasses, 16bit_storage_input_output, afbc & async_compute, probably more.

**Comment by gary-sweet** [comment]
Reverting https://github.com/KhronosGroup/Vulkan-Samples/pull/984 makes the asserts go away again.
@asuessenbach Do you want to take a look at this, or should we just revert that change for the time being?

**Comment by asuessenbach** [comment]
Sorry, please, I had accidentally removed a check in some destructors... will fix it right now.
