### ISSUE TITLE
wait_idle is failing at startup with ERROR_NATIVE_WINDOW_IN_USE_KHR

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-Samples#1033]
I'm seeing `[error] Error Message: Cannot create Swapchain : ERROR_NATIVE_WINDOW_IN_USE_KHR` when I run wait_idle now.

A bisect has shown that this started happening when https://github.com/KhronosGroup/Vulkan-Samples/pull/910 was merged.

@asuessenbach Does this sample run for you? Any idea what you might have changed that caused this to start failing?

**Comment by asuessenbach** [comment]
No, that sample doesn't run for me either!
I tried a hard reset to right before #910, but could not configure with CMake anymore!
Even after resetting to main top of tree, that same error stayed:
```
CMake Error at third_party/CMakeLists.txt:270 (set_target_properties):
  set_target_properties Can not find target to add properties to: OGLCompiler
```
Absolutely no idea what happened there!
I'll continue investigation on Monday
