### ISSUE TITLE
Build Failure (Windows 11, VS 2022)

### ISSUE THREAD

**Issue by lang-sec** [KhronosGroup/Vulkan-Samples#1049]
CPU : Intel 11700

I have two VGA cards
NVIDIA RTX 4060 Ti
NVIDIA RTX 4060 Ti

OS : Windows 11 (updated)

I have two versions of Vulkan

C:\VulkanSDK\1.3.280.0
C:\VulkanSDK\1.3.283.0

I also have

Visual Studio 2022 (updated)
Python 3.12.3 (64bit)
CMake 3.29.3
Git 2.45.1.windows.1
Git Large File Storage installed

I did below

enabled Developer Mode

git clone --recurse-submodules https://github.com/KhronosGroup/Vulkan-Samples.git

cd Vulkan-Samples

cmake -G "Visual Studio 17 2022" -A x64 -S . -Bbuild/windows

But I have errors as follows

So please help me with this issues
Thank you

K:\>git clone --recurse-submodules https://github.com/KhronosGroup/Vulkan-Samples.git
Cloning into 'Vulkan-Samples'...
remote: Enumerating objects: 11307, done.
remote: Counting objects: 100% (1587/1587), done.
remote: Compressing objects: 100% (989/989), done.
remote: Total 11307 (delta 894), reused 983 (delta 564), pack-reused 9720
Receiving objects: 100% (11307/11307), 63.50 MiB | 19.81 MiB/s, done.
Resolving deltas: 100% (7365/7365), done.
Submodule 'assets' (https://github.com/KhronosGroup/Vulkan-Samples-Assets) registered for path 'assets'
Submodule 'third_party/CTPL' (https://github.com/vit-vit/CTPL) registered for path 'third_party/CTPL'
Submodule 'third_party/astc' (https://github.com/ARM-software/astc-encoder) registered for path 'third_party/astc'
Submodule 'third_party/catch2' (https://github.com/catchorg/Catch2.git) registered for path 'third_party/catch2'
Submodule 'third_party/cli11' (https://github.com/CLIUtils/CLI11.git) registered for path 'third_party/cli11'
Submodule 'third_party/fmt' (https://github.com/fmtlib/fmt) registered for path 'third_party/fmt'
Submodule 'third_party/glfw' (https://github.com/glfw/glfw) registered for path 'third_party/glfw'
Submodule 'third_party/glm' (https://github.com/g-truc/glm) registered for path 'third_party/glm'
Submodule 'third_party/glslang' (https://github.com/KhronosGroup/glslang) registered for path 'third_party/glslang'
Submodule 'third_party/hwcpipe' (https://github.com/ARM-software/HWCPipe) registered for path 'third_party/hwcpipe'
Submodule 'third_party/imgui' (https://github.com/ocornut/imgui) registered for path 'third_party/imgui'
Submodule 'third_party/ktx' (https://github.com/KhronosGroup/KTX-Software) registered for path 'third_party/ktx'
Submodule 'third_party/opencl' (https://github.com/KhronosGroup/OpenCL-Headers.git) registered for path 'third_party/opencl'
Submodule 'third_party/spdlog' (https://github.com/gabime/spdlog) registered for path 'third_party/spdlog'
Submodule 'third_party/spirv-cross' (https://github.com/KhronosGroup/SPIRV-Cross) registered for path 'third_party/spirv-cross'
Submodule 'third_party/stb' (https://github.com/nothings/stb) registered for path 'third_party/stb'
Submodule 'third_party/tinygltf' (https://github.com/syoyo/tinygltf) registered for path 'third_party/tinygltf'
Submodule 'third_party/vma' (https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator) registered for path 'third_party/vma'
Submodule 'third_party/volk' (https://github.com/zeux/volk) registered for path 'third_party/volk'
Submodule 'third_party/vulkan' (https://github.com/KhronosGroup/Vulkan-Headers) registered for path 'third_party/vulkan'
Cloning into 'K:/Vulkan-Samples/assets'...
remote: Enumerating objects: 522, done.
remote: Counting objects: 100% (522/522), done.
remote: Compressing objects: 100% (394/394), done.
remote: Total 522 (delta 133), reused 509 (delta 126), pack-reused 0
Receiving objects: 100% (522/522), 428.74 MiB | 14.43 MiB/s, done.
Resolving deltas: 100% (133/133), done.
Cloning into 'K:/Vulkan-Samples/third_party/CTPL'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 82 (delta 37), reused 36 (delta 36), pack-reused 41
Receiving objects: 100% (82/82), 19.77 KiB | 6.59 MiB/s, done.
Resolving deltas: 100% (40/40), done.
Cloning into 'K:/Vulkan-Samples/third_party/astc'...
remote: Enumerating objects: 12084, done.
remote: Counting objects: 100% (1675/1675), done.
remote: Compressing objects: 100% (325/325), done.
remote: Total 12084 (delta 1385), reused 1366 (delta 1349), pack-reused 10409
Receiving objects: 100% (12084/12084), 49.25 MiB | 18.08 MiB/s, done.
Resolving deltas: 100% (9327/9327), done.
Cloning into 'K:/Vulkan-Samples/third_party/catch2'...
remote: Enumerating objects: 39423, done.
remote: Counting objects: 100% (5464/5464), done.
remote: Compressing objects: 100% (1000/1000), done.
remote: Total 39423 (delta 4932), reused 4725 (delta 4464), pack-reused 33959
Receiving objects: 100% (39423/39423), 25.81 MiB | 15.57 MiB/s, done.
Resolving deltas: 100% (28245/28245), done.
Cloning into 'K:/Vulkan-Samples/third_party/cli11'...
remote: Enumerating objects: 9364, done.
remote: Counting objects: 100% (1610/1610), done.
remote: Compressing objects: 100% (400/400), done.
remote: Total 9364 (delta 1378), reused 1316 (delta 1192), pack-reused 7754
Receiving objects: 100% (9364/9364), 3.67 MiB | 9.42 MiB/s, done.
Resolving deltas: 100% (6581/6581), done.
Cloning into 'K:/Vulkan-Samples/third_party/fmt'...
remote: Enumerating objects: 35360, done.
remote: Counting objects: 100% (1071/1071), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 35360 (delta 1006), reused 1025 (delta 992), pack-reused 34289
Receiving objects: 100% (35360/35360), 14.95 MiB | 22.00 MiB/s, done.
Resolving deltas: 100% (24012/24012), done.
Cloning into 'K:/Vulkan-Samples/third_party/glfw'...
remote: Enumerating objects: 32389, done.
remote: Counting objects: 100% (692/692), done.
remote: Compressing objects: 100% (307/307), done.
remote: Total 32389 (delta 472), reused 488 (delta 367), pack-reused 31697
Receiving objects: 100% (32389/32389), 16.48 MiB | 19.74 MiB/s, done.
Resolving deltas: 100% (22948/22948), done.
Cloning into 'K:/Vulkan-Samples/third_party/glm'...
remote: Enumerating objects: 59610, done.
remote: Total 59610 (delta 0), reused 0 (delta 0), pack-reused 59610
Receiving objects: 100% (59610/59610), 71.20 MiB | 14.54 MiB/s, done.
Resolving deltas: 100% (45208/45208), done.
Cloning into 'K:/Vulkan-Samples/third_party/glslang'...
remote: Enumerating objects: 55881, done.
remote: Counting objects: 100% (55881/55881), done.
remote: Compressing objects: 100% (8691/8691), done.
remote: Total 55881 (delta 47075), reused 55501 (delta 46872), pack-reused 0
Receiving objects: 100% (55881/55881), 70.47 MiB | 20.40 MiB/s, done.
Resolving deltas: 100% (47075/47075), done.
Cloning into 'K:/Vulkan-Samples/third_party/hwcpipe'...
remote: Enumerating objects: 705, done.
remote: Counting objects: 100% (425/425), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 705 (delta 182), reused 377 (delta 158), pack-reused 280
Receiving objects: 100% (705/705), 721.11 KiB | 27.73 MiB/s, done.
Resolving deltas: 100% (324/324), done.
Cloning into 'K:/Vulkan-Samples/third_party/imgui'...
remote: Enumerating objects: 53945, done.
remote: Counting objects: 100% (10695/10695), done.
remote: Compressing objects: 100% (516/516), done.
remote: Total 53945 (delta 10425), reused 10311 (delta 10179), pack-reused 43250
Receiving objects: 100% (53945/53945), 89.09 MiB | 15.27 MiB/s, done.
Resolving deltas: 100% (41893/41893), done.
Cloning into 'K:/Vulkan-Samples/third_party/ktx'...
remote: Enumerating objects: 35682, done.
remote: Counting objects: 100% (871/871), done.
remote: Compressing objects: 100% (426/426), done.
remote: Total 35682 (delta 455), reused 758 (delta 421), pack-reused 34811
Receiving objects: 100% (35682/35682), 211.80 MiB | 20.72 MiB/s, done.
Resolving deltas: 100% (23187/23187), done.
Cloning into 'K:/Vulkan-Samples/third_party/opencl'...
remote: Enumerating objects: 1364, done.
remote: Counting objects: 100% (387/387), done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 1364 (delta 296), reused 253 (delta 205), pack-reused 977
Receiving objects: 100% (1364/1364), 774.02 KiB | 28.67 MiB/s, done.
Resolving deltas: 100% (880/880), done.
Cloning into 'K:/Vulkan-Samples/third_party/spdlog'...
remote: Enumerating objects: 28588, done.
remote: Counting objects: 100% (1043/1043), done.
remote: Compressing objects: 100% (397/397), done.
remote: Total 28588 (delta 631), reused 896 (delta 557), pack-reused 27545
Receiving objects: 100% (28588/28588), 41.41 MiB | 13.40 MiB/s, done.
Resolving deltas: 100% (19059/19059), done.
Cloning into 'K:/Vulkan-Samples/third_party/spirv-cross'...
remote: Enumerating objects: 35837, done.
remote: Counting objects: 100% (9059/9059), done.
remote: Compressing objects: 100% (822/822), done.
remote: Total 35837 (delta 8410), reused 8484 (delta 8235), pack-reused 26778
Receiving objects: 100% (35837/35837), 15.19 MiB | 16.82 MiB/s, done.
Resolving deltas: 100% (25765/25765), done.
Cloning into 'K:/Vulkan-Samples/third_party/stb'...
remote: Enumerating objects: 8031, done.
remote: Counting objects: 100% (163/163), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 8031 (delta 99), reused 104 (delta 78), pack-reused 7868
Receiving objects: 100% (8031/8031), 5.59 MiB | 16.21 MiB/s, done.
Resolving deltas: 100% (5324/5324), done.
Cloning into 'K:/Vulkan-Samples/third_party/tinygltf'...
remote: Enumerating objects: 5188, done.
remote: Counting objects: 100% (324/324), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 5188 (delta 184), reused 267 (delta 161), pack-reused 4864
Receiving objects: 100% (5188/5188), 20.64 MiB | 21.70 MiB/s, done.
Resolving deltas: 100% (2846/2846), done.
Cloning into 'K:/Vulkan-Samples/third_party/vma'...
remote: Enumerating objects: 10419, done.
remote: Counting objects: 100% (2477/2477), done.
remote: Compressing objects: 100% (476/476), done.
remote: Total 10419 (delta 2034), reused 2227 (delta 1902), pack-reused 7942
Receiving objects: 100% (10419/10419), 26.55 MiB | 19.24 MiB/s, done.
Resolving deltas: 100% (8195/8195), done.
Cloning into 'K:/Vulkan-Samples/third_party/volk'...
remote: Enumerating objects: 1192, done.
remote: Counting objects: 100% (745/745), done.
remote: Compressing objects: 100% (229/229), done.
remote: Total 1192 (delta 563), reused 621 (delta 505), pack-reused 447
Receiving objects: 100% (1192/1192), 331.85 KiB | 30.17 MiB/s, done.
Resolving deltas: 100% (707/707), done.
Cloning into 'K:/Vulkan-Samples/third_party/vulkan'...
remote: Enumerating objects: 4495, done.
remote: Counting objects: 100% (1170/1170), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 4495 (delta 1026), reused 1064 (delta 976), pack-reused 3325
Receiving objects: 100% (4495/4495), 43.33 MiB | 18.49 MiB/s, done.
Resolving deltas: 100% (3087/3087), done.
Submodule path 'assets': checked out 'ee839b65f277ecaf26e4d3fd9877d9f37ced17d2'
Submodule path 'third_party/CTPL': checked out '437e135dbd94eb65b45533d9ce8ee28b5bd37b6d'
Submodule path 'third_party/astc': checked out '1a51f2915121275038677317c8bf61f1a78b590c'
Submodule 'Source/GoogleTest' (https://github.com/google/googletest.git) registered for path 'third_party/astc/Source/GoogleTest'
Cloning into 'K:/Vulkan-Samples/third_party/astc/Source/GoogleTest'...
remote: Enumerating objects: 27509, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 27509 (delta 20), reused 30 (delta 11), pack-reused 27462
Receiving objects: 100% (27509/27509), 12.73 MiB | 24.97 MiB/s, done.
Resolving deltas: 100% (20433/20433), done.
Submodule path 'third_party/astc/Source/GoogleTest': checked out 'e2239ee6043f73722e7aa812a459f54a28552929'
Submodule path 'third_party/catch2': checked out '3f0283de7a9c43200033da996ff9093be3ac84dc'
Submodule path 'third_party/cli11': checked out 'a6c48261d4fb62b232c46277acbcc3d14d5b7e14'
Submodule path 'third_party/fmt': checked out 'dd6f657a79104101a2e4ea6ba90f69e0dc114822'
Submodule path 'third_party/glfw': checked out '8f470597d625ae28758c16b4293dd42d63e8a83a'
Submodule path 'third_party/glm': checked out 'fce2abd01ce21063bd25ba67c9318be83bf48813'
Submodule path 'third_party/glslang': checked out '54726b3c1c5cb70043174365750ab0f1b7e1a6a0'
Submodule path 'third_party/hwcpipe': checked out '0116b700a8d73189ece070279b62ca1b744cc965'
Submodule path 'third_party/imgui': checked out 'da29b776eed289db16a8527e5f16a0e1fa540251'
fatal: active `post-checkout` hook found during `git clone`:
        K:/Vulkan-Samples/.git/modules/third_party/ktx/hooks/post-checkout
For security reasons, this is disallowed by default.
If this is intentional and the hook should actually be run, please
run the command again with `GIT_CLONE_PROTECTION_ACTIVE=false`
fatal: Unable to checkout '6a38a0694b4d73d22c5d1e22f865d03545e808ea' in submodule path 'third_party/ktx'

K:\>cd Vulkan-Samples

K:\Vulkan-Samples>cmake -G "Visual Studio 17 2022" -A x64 -S . -Bbuild/windows
-- vulkan_libraryC:/VulkanSDK/1.3.283.0/Lib32/vulkan-1.libsearchpathsC:\VulkanSDK\1.3.283.0/lib32C:\VulkanSDK\1.3.283.0/bin32C:\VulkanSDK\1.3.283.0/libC:\VulkanSDK\1.3.283.0/bin
-- Found Vulkan: C:/VulkanSDK/1.3.283.0/Lib32/vulkan-1.lib (found version "1.3.283") found components: glslc glslangValidator
Found DirectX Shader Compiler under C:/VulkanSDK/1.3.283.0/Bin/dxc.exe
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.39.33523.0
-- The CXX compiler identification is MSVC 19.39.33523.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Debug
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
CMake Error at third_party/CMakeLists.txt:275 (add_subdirectory):
  The source directory

    K:/Vulkan-Samples/third_party/spirv-cross

  does not contain a CMakeLists.txt file.

CMake Error at third_party/CMakeLists.txt:277 (set_target_properties):
  set_target_properties Can not find target to add properties to: spirv-cross

CMake Error at third_party/CMakeLists.txt:278 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  spirv-cross-c

CMake Error at third_party/CMakeLists.txt:279 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  spirv-cross-core

CMake Error at third_party/CMakeLists.txt:280 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  spirv-cross-glsl

CMake Error at third_party/CMakeLists.txt:281 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  spirv-cross-cpp

CMake Error at third_party/CMakeLists.txt:282 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  spirv-cross-hlsl

CMake Error at third_party/CMakeLists.txt:283 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  spirv-cross-msl

CMake Error at third_party/CMakeLists.txt:284 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  spirv-cross-reflect

CMake Error at third_party/CMakeLists.txt:285 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  spirv-cross-util

-- Try AVX2 C flag = [/arch:AVX]
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Success
-- Found AVX2: /arch:AVX
-- Performing Test HAVE_AVX2_MM256_SET1_EPI64X
-- Performing Test HAVE_AVX2_MM256_SET1_EPI64X - Success
-- Performing Test HAVE_AVX2_MM256_SET_EPI64X
-- Performing Test HAVE_AVX2_MM256_SET_EPI64X - Success
-- Performing Test HAVE_AVX2_MM256_INSERT_EPI64
-- Performing Test HAVE_AVX2_MM256_INSERT_EPI64 - Success
-- Performing Test HAVE_AVX2_MM256_INSERT_EPI32
-- Performing Test HAVE_AVX2_MM256_INSERT_EPI32 - Success
-- Performing Test HAVE_AVX2_MM256_INSERT_EPI16
-- Performing Test HAVE_AVX2_MM256_INSERT_EPI16 - Success
-- Performing Test HAVE_AVX2_MM256_INSERT_EPI8
-- Performing Test HAVE_AVX2_MM256_INSERT_EPI8 - Success
-- Performing Test HAVE_AVX2_MM256_EXTRACT_EPI64
-- Performing Test HAVE_AVX2_MM256_EXTRACT_EPI64 - Success
-- Performing Test HAVE_AVX2_MM256_EXTRACT_EPI32
-- Performing Test HAVE_AVX2_MM256_EXTRACT_EPI32 - Success
-- Performing Test HAVE_AVX2_MM256_EXTRACT_EPI16
-- Performing Test HAVE_AVX2_MM256_EXTRACT_EPI16 - Success
-- Performing Test HAVE_AVX2_MM256_EXTRACT_EPI8
-- Performing Test HAVE_AVX2_MM256_EXTRACT_EPI8 - Success
-- Try SSE2 C flag = [ ]
-- Performing Test HAVE_SSE2
-- Performing Test HAVE_SSE2 - Success
-- Found SSE2:
-- Performing Test HAVE_SSE2_MM_SET1_EPI64X
-- Performing Test HAVE_SSE2_MM_SET1_EPI64X - Success
-- Performing Test HAVE_SSE2_MM_SET_EPI64X
-- Performing Test HAVE_SSE2_MM_SET_EPI64X - Success
-- Try NEON C flag = [ ]
-- Performing Test HAVE_NEON
-- Performing Test HAVE_NEON - Failed
-- Could NOT find NEON (missing: NEON_C_FLAGS)
--   AVX2 backend     - ON
--   SSE4.1 backend   - OFF
--   SSE2 backend     - OFF
--   NEON backend     - OFF
--   NONE backend     - OFF
--   NATIVE backend   - OFF
--   Invariance       - ON
--   Shared libs      - OFF
--   Decompressor     - ON
--   Diagnostics      - OFF
--   ASAN             - OFF
--   Unit tests       - OFF
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Including Win32 support
-- Version: 10.1.1
-- Build type:
CMake Error at third_party/CMakeLists.txt:408 (add_subdirectory):
  The source directory

    K:/Vulkan-Samples/third_party/spdlog

  does not contain a CMakeLists.txt file.

CMake Error at third_party/CMakeLists.txt:409 (set_property):
  set_property could not find TARGET spdlog.  Perhaps it has not yet been
  created.

CMake Deprecation Warning at third_party/cli11/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- STATIC: vkb__core
-- STATIC: vkb__windows_platform
-- STATIC: vkb__filesystem
-- Windows platform detected
-- Warnings as Errors Enabled
-- Sample `compute_nbody` - BUILD
-- Sample `dynamic_uniform_buffers` - BUILD
-- Sample `hdr` - BUILD
-- Sample `hello_triangle` - BUILD
-- Sample `hlsl_shaders` - BUILD
-- Sample `hpp_compute_nbody` - BUILD
-- Sample `hpp_dynamic_uniform_buffers` - BUILD
-- Sample `hpp_hdr` - BUILD
-- Sample `hpp_hello_triangle` - BUILD
-- Sample `hpp_hlsl_shaders` - BUILD
-- Sample `hpp_instancing` - BUILD
-- Sample `hpp_oit_linked_lists` - BUILD
-- Sample `hpp_separate_image_sampler` - BUILD
-- Sample `hpp_terrain_tessellation` - BUILD
-- Sample `hpp_texture_loading` - BUILD
-- Sample `hpp_texture_mipmap_generation` - BUILD
-- Sample `hpp_timestamp_queries` - BUILD
-- Sample `instancing` - BUILD
-- Sample `oit_depth_peeling` - BUILD
-- Sample `oit_linked_lists` - BUILD
-- Sample `separate_image_sampler` - BUILD
-- Sample `swapchain_recreation` - BUILD
-- Sample `terrain_tessellation` - BUILD
-- Sample `texture_loading` - BUILD
-- Sample `texture_mipmap_generation` - BUILD
-- Sample `timestamp_queries` - BUILD
-- Sample `buffer_device_address` - BUILD
-- Sample `calibrated_timestamps` - BUILD
-- Sample `color_write_enable` - BUILD
-- Sample `conditional_rendering` - BUILD
-- Sample `conservative_rasterization` - BUILD
-- Sample `debug_utils` - BUILD
-- Sample `descriptor_buffer_basic` - BUILD
-- Sample `descriptor_indexing` - BUILD
-- Sample `dynamic_blending` - BUILD
-- Sample `dynamic_line_rasterization` - BUILD
-- Sample `dynamic_primitive_clipping` - BUILD
-- Sample `dynamic_rendering` - BUILD
-- Sample `extended_dynamic_state2` - BUILD
-- Sample `fragment_shader_barycentric` - BUILD
-- Sample `fragment_shading_rate` - BUILD
-- Sample `fragment_shading_rate_dynamic` - BUILD
-- Sample `full_screen_exclusive` - BUILD
-- Sample `graphics_pipeline_library` - BUILD
-- Sample `gshader_to_mshader` - BUILD
-- Sample `hpp_mesh_shading` - BUILD
-- Sample `logic_op_dynamic_state` - BUILD
-- Sample `memory_budget` - BUILD
-- Sample `mesh_shader_culling` - BUILD
-- Sample `mesh_shading` - BUILD
-- Sample `open_cl_interop` - BUILD
-- Sample `open_gl_interop` - BUILD
-- Sample `patch_control_points` - BUILD
-- Sample `portability` - BUILD
-- Sample `push_descriptors` - BUILD
-- Sample `ray_queries` - BUILD
-- Sample `ray_tracing_basic` - BUILD
-- Sample `ray_tracing_extended` - BUILD
-- Sample `ray_tracing_reflection` - BUILD
-- Sample `shader_debugprintf` - BUILD
-- Sample `shader_object` - BUILD
-- Sample `sparse_image` - BUILD
-- Sample `synchronization_2` - BUILD
-- Sample `vertex_dynamic_state` - BUILD
-- Sample `mobile_nerf` - BUILD
-- Sample `16bit_arithmetic` - BUILD
-- Sample `16bit_storage_input_output` - BUILD
-- Sample `afbc` - BUILD
-- Sample `async_compute` - BUILD
-- Sample `command_buffer_usage` - BUILD
-- Sample `constant_data` - BUILD
-- Sample `descriptor_management` - BUILD
-- Sample `hpp_pipeline_cache` - BUILD
-- Sample `hpp_swapchain_images` - BUILD
-- Sample `image_compression_control` - BUILD
-- Sample `layout_transitions` - BUILD
-- Sample `msaa` - BUILD
-- Sample `multi_draw_indirect` - BUILD
-- Sample `multithreading_render_passes` - BUILD
-- Sample `pipeline_barriers` - BUILD
-- Sample `pipeline_cache` - BUILD
-- Sample `render_passes` - BUILD
-- Sample `specialization_constants` - BUILD
-- Sample `subpasses` - BUILD
-- Sample `surface_rotation` - BUILD
-- Sample `swapchain_images` - BUILD
-- Sample `texture_compression_basisu` - BUILD
-- Sample `texture_compression_comparison` - BUILD
-- Sample `wait_idle` - BUILD
-- Sample `profiles` - BUILD
-- Plugin `batch_mode` - BUILD
-- Plugin `benchmark_mode` - BUILD
-- Plugin `data_path` - BUILD
-- Plugin `file_logger` - BUILD
-- Plugin `force_close` - BUILD
-- Plugin `fps_logger` - BUILD
-- Plugin `gpu_selection` - BUILD
-- Plugin `real_time_shader_selection` - BUILD
-- Plugin `screenshot` - BUILD
-- Plugin `start_sample` - BUILD
-- Plugin `stop_after` - BUILD
-- Plugin `user_interface_options` - BUILD
-- Plugin `window_options` - BUILD
-- Configuring incomplete, errors occurred!

**Comment by lang-sec** [comment]
Hello, I found the error caused from this

fatal: Unable to checkout '6a38a0694b4d73d22c5d1e22f865d03545e808ea' in submodule path 'third_party/ktx'

So, please help me with this third-party lib downloading issue

Thank you

**Comment by SaschaWillems** [comment]
Can you test again? A clean checkout incl. submodules works fine for me, so it might be a problem with github.

**Comment by lang-sec** [comment]
Hello, Sascha
I solved this problem

setting environment variable GIT_CLONE_PROTECTION_ACTIVE = false
in Windows 11
git clone full recursive downloads work all right now
and I can build this project OK

Thank you and have a nice day, Sascha
You can close this issue
