### ISSUE TITLE
Creating a Khronos glad fork based off of @Jericho's.

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/Vulkan-Samples#106]
Needed for #97 to work. 

The primary glad repository contains not an instance of glad, but code for a glad generator.  In theory I could have integrated the main repository and used CMake to execute the generator to produce the appropriate GL loader, but that would have made the build process significantly more fragile and added a dependency on Python to execute the generator.  

Instead I opted to create a fork of glad, and then create branches with the output of the generator needed for the two specific API's, OpenGL and OpenGL ES.  

There are a few possible paths...

* Leave it as it is
* Leave the glad dependencies as submodules, but switch to a fork of Glad owned by KhronosGroup
* Switch to embedding the glad dependencies as files under third-party instead of submodules
  * Unfortunately this would require fixing the CI servers to ignore these files in the linting and copyright headers checks
* Switch to the main glad repository and modify the CMake process to call the generator appropriately and create these files at configure or build time.

_Originally posted by @jherico in https://github.com/KhronosGroup/Vulkan-Samples/pull/97#issuecomment-613671240_

**Comment by Dav1dde** [comment]
Feel free to ping me (author of glad) if you have questions, need support or changes in glad.

**Comment by TomAtkinsonArm** [comment]
As this feature is only for a single sample it has been suggested that we simply copy the required files into the sample.

@Dav1dde Thanks for such a quick reply! I was wandering if you have had any experience with adding GLAD to an android native application. I've been searching for some detailed examples and cannot find any. My attempts have all ended in the project not compiling.

**Comment by Dav1dde** [comment]
@TomAtkinsonArm unfortunately I personally have never tried, nor am I aware of a project doing that. In theory it should "just work". Do you have the compilation errors for me?

**Comment by TomAtkinsonArm** [comment]
I will try again now, I believe my compilation issues before where to do with incorrect config of NDK.

Another Q related to this can i have the GLES and GL loader in the same glad loader? Currently we have glad and glad_android i'm hoping we can just have glad

**Comment by Dav1dde** [comment]
Yes you can generate GLES and GL symbols at the same time, either select both on the website or specify both APIs on the CLI `--api="gl=4.6,gles2=3.2"`.

You'll have to select at runtime which one to load and of course there may be symbols which don't actually get loaded because they belong to a different API.

**Comment by TomAtkinsonArm** [comment]
Hi @Dav1dde, you're completely right! Everything builds fine now. The issue was that we used OBJECT libraries in CMake which you can not link against. I've rectified this now and everything works perfect!

If its ok with you I'll keep this issue open until the sample is merged just in case i have any more questions.

**Comment by Dav1dde** [comment]
Yeah of course! Glad it is working now ;)

**Comment by ghost** [comment]
Should have closed with #97 merge.
