### ISSUE TITLE
OIT Sample blending is off

### ISSUE THREAD

**Issue by ds-pascalwe** [KhronosGroup/Vulkan-Samples#1066]
I implemented "order independent linked list transparency" with the guidance of the Vulkan sample. In our engine, we have different transparency modes, linked list transparency was supposed to be our newest one. Since we have a lot of integration tests, I noticed that with the linked list transparency, the blended colors are completely different, almost inverted. The blending function provided in oit_linked_lists/combine.frag seemed strange to me, especially that there is a need to invert the resulting accumulated alpha in line 141. The blending operations for our Combine pass are the following (which seem to me like they basic premultiplied alpha blending):

- blend op: Add
- Color blend factors (eSrcAlpha, eOneMinusSrcAlpha)
- Alpha blend factors (eOne, eOneMinusSrcAlpha)

To fix the compositing, I had to switch up the blending function in combine.frag to this:

```glsl
vec4 blendColors(vec4 srcColor, vec4 dstColor)
{
	float alphaResult = srcColor.a + dstColor.a * (1.0f - srcColor.a);
	vec3 rgbResult = (srcColor.rgb * srcColor.a + dstColor.rgb * dstColor.a * (1.0f - srcColor.a)) / alphaResult;

	return vec4(rgbResult, alphaResult);
}
```

color needs to be initialized like this: `vec4 color = vec4(0.0f, 0.0f, 0.0f, 0.0f);`

and the alpha inversion in line 141 can be removed. With these changes, the resulting colors are the same as with basic transparency rendering.

I guess for the sample, it's not a problem if the blending is off, but for anyone using your sample as reference, it could lead to unnecessary problem solving. Just a suggestion :)

**Comment by asuessenbach** [comment]
Could you please provide some images without and with your proposed changes?

**Comment by ds-pascalwe** [comment]
Of course, see here:

In the spheres example, most of the spheres are a lot less visible in general, and especially in the overlap areas, the results look strange.

"Fixed" Blending:
![BlendingFixed_Spheres](https://github.com/KhronosGroup/Vulkan-Samples/assets/85922318/34c31536-a869-4df8-84f3-09eb3dc38b2f)

Original Blending:
![OriginalSampleBlending_Spheres](https://github.com/KhronosGroup/Vulkan-Samples/assets/85922318/cdb9705f-a7fe-408d-81b8-6524b48671f6)

With the transparent textures the blending problem becomes more apparent, as darker and brighter areas are almost inverted in both cases.

"Fixed" Blending:
![BlendingFixed_Textures](https://github.com/KhronosGroup/Vulkan-Samples/assets/85922318/2ddc3821-31d7-498b-b3e1-e327cd64eee2)

Original Blending:
![OriginalSampleBlending_Textures](https://github.com/KhronosGroup/Vulkan-Samples/assets/85922318/1326a18c-7015-4128-b853-ef6204cadf95)

**Comment by jeroenbakker-atmind** [comment]
I applied your comments to the sample in the PR above #1186
Thanks for the clear instructions :-)
