### ISSUE TITLE
JPEG to RGB bitmap conversion

### ISSUE THREAD

**Issue by mpatalberta** [KhronosGroup/Vulkan-Samples#1067]
Is their an example of converting from JPG bitmap to a RGB bitmap.

**Comment by SaschaWillems** [comment]
JPEG already stores image data as RGB(A).

Can you elaborate? How would this be relevant to this repository?

**Comment by gpx1000** [comment]
https://github.com/libjpeg-turbo/libjpeg-turbo jpeg is a CODEC, that means that you'd want to use a library which can take the compressed jpeg and output an uncompressed bitmap.

**Comment by mpatalberta** [comment]
I was hoping to use the VulKan to provide a hardware JPG to BMP converter.

**Comment by SaschaWillems** [comment]
Vulkan does not know anything about codecs like JPEG, nor does it have any libraries to do such a conversion.

**Comment by gpx1000** [comment]
Additionally, there'd be very little if any benefit of doing such a conversion in the graphics card.  It is probably possible to use OpenCL or even Vulkan Compute shaders to do a conversion in the graphics card; but you wouldn't get much benefit from the extra effort, and you'd have to write a decompressor specific to your codec in a shader.  If you were interested in more than one frame, you could look at Vulkan Video.  However, for a single image, that's a lot of overhead for something the CPU is quite capable of.
