### ISSUE TITLE
ADB_EXECUTABLE not found when building with Android Studio

### ISSUE THREAD

**Issue by mpatalberta** [KhronosGroup/Vulkan-Samples#1075]
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\spock\Vulkan-Samples\build\android_gradle\app\build-native\Debug\4x4g2r6w\arm64-v8a'
  [0/2] Re-checking globbed directories...
  [1/4] Update assets in external storage
  FAILED: app/CMakeFiles/sync.assets.stamp D:/spock/Vulkan-Samples/build/android_gradle/app/build-native/Debug/4x4g2r6w/arm64-v8a/app/CMakeFiles/sync.assets.stamp 
  cmd.exe /C "cd /D D:\spock\Vulkan-Samples\build\android_gradle\app\build-native\Debug\4x4g2r6w\arm64-v8a\app && C:\Users\PMH786\AppData\Local\Android\Sdk\cmake\3.22.1\bin\cmake.exe -DCMAKE_MODULE_PATH=D:/spock/Vulkan-Samples/bldsys/cmake/module D:/spock/Vulkan-Samples/bldsys/cmake D:/spock/Vulkan-Samples/bldsys/cmake/module -DFOLDER_DIR=D:/spock/Vulkan-Samples/app/../assets/. -DDEVICE_DIR=/sdcard/Android/data/com.khronos.vulkan_samples/files/assets/ -P D:/spock/Vulkan-Samples/bldsys/cmake/android_sync_folder.cmake"
  CMake Error at C:/Users/PMH786/AppData/Local/Android/Sdk/cmake/3.22.1/share/cmake-3.22/Modules/**FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Adb (missing: ADB_EXECUTABLE) (Required is at least version
    "1.0.39")
  Call Stack (most recent call first):**
    C:/Users/PMH786/AppData/Local/Android/Sdk/cmake/3.22.1/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    D:/spock/Vulkan-Samples/bldsys/cmake/module/FindAdb.cmake:50 (find_package_handle_standard_args)
    D:/spock/Vulkan-Samples/bldsys/cmake/android_sync_folder.cmake:26 (find_package)

**Comment by SaschaWillems** [comment]
That message clearly states that ADB cannot be found. Is it installed (e.g. via the Android SDK)? You can simply test this by opening a command prompt and trying to run ADB from there. If that doesn't work ADB is either not installed, or not in your path.

**Comment by mpatalberta** [comment]
After some work i finally got the path enviroment correct

**Comment by mpatalberta** [comment]
thanks
