### ISSUE TITLE
How do I add android VulKan to my project

### ISSUE THREAD

**Issue by mpatalberta** [KhronosGroup/Vulkan-Samples#1077]
I can compile and the VulKan on my android unit.
How do I add the vulKan to a seperate to android application. (where is the sdk for android.
Thanks Pat

**Comment by SaschaWillems** [comment]
Can you elaborate? What exactly do you want to do? Create your own Vulkan application with Android support?

**Comment by mpatalberta** [comment]
I have the supplied example working on my android device.
How do I add VulKan to an already existing  android project?

**Comment by SaschaWillems** [comment]
And what information do you actually need. The samples already contain everything that you need for adding Vulkan to any Android application. Just look at the code, search for the android defines and copy that code to your own application.

In general Vulkan is a first-class api on Android and there is nothing special required to use it there. If in doubt, google has very good documentation on that: https://developer.android.com/ndk/guides/graphics/getting-started

Note that this issue tracker is meant for actual issues with our samples and not for asking general Vulkan realted questions. Those are better suited for the various Vulkan communities (see https://vulkan.org/learn)
