### ISSUE TITLE
MSAA example unnecessarily enables VK_KHR_multiview

### ISSUE THREAD

**Issue by tambry** [KhronosGroup/Vulkan-Samples#109]
The MSAA example [enables `VK_KHR_multiview`](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/performance/msaa/msaa.cpp#L83) despite seemingly never using it.

**Comment by JoseEmilio-ARM** [comment]
Hi, thanks for your feedback!

The MSAA sample uses [`VK_KHR_depth_stencil_resolve`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_depth_stencil_resolve) which depends on [`VK_KHR_create_renderpass2`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_create_renderpass2) which in turn depends on [`VK_KHR_multiview`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_multiview). Disabling it results in the following validation layer error:
```
2020-04-22 13:17:21.626 12137-12320/? E/VulkanSamples: [error] [ is available, enabling it:52] Validation:  [ UNASSIGNED-GeneralParameterError-ExtensionNotEnabled ] Object: VK_NULL_HANDLE (Type = 0) | Attemped to call vkCreateRenderPass2KHR() but its required extension VK_KHR_multiview has not been enabled
```

Is there an alternative way to work around this?

**Comment by tambry** [comment]
Thanks for the info. Wasn't immediately obvious why `VK_KHR_multiview` was required since it's required indirectly.  
I don't think there's any other way to do this (besides requiring a newer Vulkan version). I'll close this as it's as intended. :)
