### ISSUE TITLE
Using renderdoc to catch frames, the swapchain image only shows UI with a black background.

### ISSUE THREAD

**Issue by SakuragiHnmch** [KhronosGroup/Vulkan-Samples#1128]
I was using renderdoc to capture the `async_compute` sample's frames, and found that the swapChain image only contains UI informations . At first, I guess that might be caused by the multi queues. But when I set the `async_enabled` false, this problem remained.

And later I tested several other samples like `msaa` , `render_passes` , the same problem occurred.

The problem shows as below:
![capture](https://github.com/user-attachments/assets/108a2ee3-6bfe-4925-af23-9d843ec94461)

I have no idea about why this will happen. And I know there is In-application API of renderdoc for headless vulkan application, but it seems have nothing to do with my problem.

Could anyone offer some help, thanks very much!

**Comment by SaschaWillems** [comment]
Can you please add some information on you setup? What OS? What device? And does this also happen with earlier RenderDoc version?

I just tested with RenderDoc 1.33 and the samples you mentioned on Win11 with an RTX 4070 and everything works as expected.

**Comment by SakuragiHnmch** [comment]
Thank for your reply. 
Below is my environment:
- RenderDoc version: 1.34
- Operating System: Windows10
- Graphics API: Vulkan1.3.283
- Graphics Card: RTX 2060 super

And I have just downloaded the old 1.33 renderdoc, and tested some other samples.

The `pipeline cache` scene looks like:
![pipeline](https://github.com/user-attachments/assets/0e65b4d8-e10c-4e0b-a084-2783df7c486d)

But the capture of `pipeline_cache` sample looks like:
![pipeline_capture](https://github.com/user-attachments/assets/99a74632-68a7-4756-9fca-eb16f49cda4a)

Howerver, the capture of `multi_draw_indirect` works as expected, it looks like:
![indirect](https://github.com/user-attachments/assets/3b171f9a-5463-43a4-9805-12f1c46cca67)

 That's really weird.

**Comment by SaschaWillems** [comment]
The samples use different frame works. One based on mine and one based on ARM samples. The ARM samples framework does have some sync/resource creation issues that might explain why you see differences between different samples.

**Comment by SakuragiHnmch** [comment]
I just found out that, all the samples inherited from `VulkanSampleC` or `VulkanSampleCpp` could not be captured as expected. And all those samples have the same warning in renderdoc, shows as below:
![error](https://github.com/user-attachments/assets/9ea97187-bde0-4cfa-b9b1-70f34cc28520)
The message is:
> Validation Error: [ VUID-vkCmdDrawIndexed-None-08114 ] Object 0: handle = Descriptor Set 772, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x3f6fd836 | vkCmdDrawIndexed():  the descriptor (VkDescriptorSet Descriptor Set 772, binding 1, index 0) is using buffer VkBuffer 0x9dc4de00000002b8[] that is invalid or has been destroyed. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid as described by descriptor validity if they are statically used by the VkPipeline bound to the pipeline bind point used by this command and the bound VkPipeline was not created with VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-08114)

And when those samples runs, the console window also shows a bunch of validatiion errors:
> [debug] Building #1 cache object (class vkb::DescriptorSet)
[error] -36706146 - VUID-VkWriteDescriptorSet-descriptorType-00327: Validation Error: [ VUID-VkWriteDescriptorSet-descri
ptorType-00327 ] | MessageID = 0xfdcfe89e | vkUpdateDescriptorSets(): pDescriptorWrites[0].pBufferInfo[0].offset (1872)
must be a multiple of device limit minUniformBufferOffsetAlignment 64 when descriptor type is VK_DESCRIPTOR_TYPE_UNIFORM
_BUFFER. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BU
FFER_DYNAMIC, the offset member of each element of pBufferInfo must be a multiple of VkPhysicalDeviceLimits::minUniformB
ufferOffsetAlignment (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-VkWriteDescri
ptorSet-descriptorType-00327)
[debug] Building #2 cache object (class vkb::DescriptorSet)
[error] -36706146 - VUID-VkWriteDescriptorSet-descriptorType-00327: Validation Error: [ VUID-VkWriteDescriptorSet-descri
ptorType-00327 ] | MessageID = 0xfdcfe89e | vkUpdateDescriptorSets(): pDescriptorWrites[0].pBufferInfo[0].offset (2064)
must be a multiple of device limit minUniformBufferOffsetAlignment 64 when descriptor type is VK_DESCRIPTOR_TYPE_UNIFORM
_BUFFER. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BU
FFER_DYNAMIC, the offset member of each element of pBufferInfo must be a multiple of VkPhysicalDeviceLimits::minUniformB
ufferOffsetAlignment (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-VkWriteDescri
ptorSet-descriptorType-00327) .....

**Comment by SakuragiHnmch** [comment]
> The samples use different frame works. One based on mine and one based on ARM samples. The ARM samples framework does have some sync/resource creation issues that might explain why you see differences between different samples.

That means those ARM samples might not work properly on WIndows. Emmmm, that sounds sad~.

**Comment by SaschaWillems** [comment]
Are you running the latest commit? We had a buffer alignment issue recently but since then merged a PR to fix it. I'm not seeing any of those errors on my side.

**Comment by SakuragiHnmch** [comment]
> Are you running the latest commit? We had a buffer alignment issue recently but since then merged a PR to fix it. I'm not seeing any of those errors on my side.

I was running the code updated in Jul 29 with the commit `9487ac2f3be74dd0d3ce4580d3fd45cee0359cb1`.

And I just pulled the latest commit and ran, but the same validation errors still remained.

I turned to use Nsight Graphics to capture those sample frames, it just worked fine with the expected swapchain image. 

It might be my individual problem, with something wrong on my environment. If  I figure it out, I will record it at this isssue.

And thank you very much for your reply!

**Comment by SakuragiHnmch** [comment]
> > Are you running the latest commit? We had a buffer alignment issue recently but since then merged a PR to fix it. I'm not seeing any of those errors on my side.
> 
> I was running the code updated in Jul 29 with the commit `9487ac2f3be74dd0d3ce4580d3fd45cee0359cb1`.
> 
> And I just pulled the latest commit and ran, but the same validation errors still remained.
> 
> I turned to use Nsight Graphics to capture those sample frames, it just worked fine with the expected swapchain image.
> 
> It might be my individual problem, with something wrong on my environment. If I figure it out, I will record it at this isssue.
> 
> And thank you very much for your reply!

After updated the latest commit, the problem of renderdoc captures and validation error of bufferInfo has desappeared.

And I found out that the commit 90c1d924a01d2ebf461b8e5281869b811f7de274 exactly solved the issue.
