### ISSUE TITLE
subpasses sample floods console with error messages

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-Samples#1153]
I see a constant flood of these errors when running the subpasses sample:
`[error] Subpass::allocate_lights: exceeding max_lights_per_type of 32 for point lights`

A bisect has shown that this started happening with this commit:

```
0d347b1029f4a3df307b0b17d8779fd08c08e9a2 is the first bad commit
commit 0d347b1029f4a3df307b0b17d8779fd08c08e9a2 (tomadamatkinson/main)
Author: Andreas Süßenbach <asuessenbach@nvidia.com>
Date:   Tue Jul 2 18:18:48 2024 +0200

    Unify vkb::Subpass and vkb::rendering::HPPSubpass into vkb::rendering::Subpass<bindingType> (#1035)
    
    * Unify vkb::Subpass and vkb::rendering::HPPSubpass into vkb::rendering::Subpass<bindingType>
    
    * Introduce type aliases SubpassC and SubpassCpp to simplify usage of Subpass<vkb::BindingType>
    
    * Fix some functions in class Subpass to not take a vector by value, but by const reference.
```

**Comment by gary-sweet** [comment]
This may be intentional of course. That change might have introduced the message to flag a condition that was always true. Flooding the console is generally a bad idea though, so we should at least limit the amount of messages we send if it is intentional.

**Comment by asuessenbach** [comment]
I also see those error messages, but I "just" get 16 of them (as there are 16 more lights than to be handled).
The issue was already there before my PR, but just without any logging.
On limiting the amount of messages: do we already have such a mechanism available in the framework? Besides that, I wouldn't call 16 such messages a "flood".
What I get like a flood, though, are VVL messages, but those predates my PR.

**Comment by gary-sweet** [comment]
That's odd because I literally got thousands of those messages. Maybe something else is going on as well. I'll have to dig deeper.

**Comment by gary-sweet** [comment]
I don't understand why you only see 16 of those messages. I'm seeing a constant flood all the time that rendering is happening. The messages come from allocate_lights() which is called from LightingSubpass::draw(), which is called once per frame.

I see 16 messages per frame - so I'm definitely calling that a 'flood' ;-)

**Comment by asuessenbach** [comment]
I see... you're right, it's 16 times per frame. It's a flood!

I could easily remove those error messages, sure. But I think, the question is, why is that function called per frame?
I assume, the scene lights aren't supposed to change per frame?
There are a couple of vectors that are recreated here every frame, and maybe more importantly, there's a new (part of a) buffer allocated each time, and the previous allocation is just orphaned. This seems to be a GPU-memory leak.

If that function is done just on the first frame, everything looks correct, and of course, those 16 messages appear just once.

**Comment by gary-sweet** [comment]
> This seems to be a GPU-memory leak.

I'm not seeing any evidence locally of device memory growing whilst the sample is running.

**Comment by asuessenbach** [comment]
> I'm not seeing any evidence locally of device memory growing whilst the sample is running.

You're right, again. The `BufferBlocks` are reset each frame! That way, that `render_frame.allocate_buffer` gets you the very same memory (modulo three frames). That is, it's not a memory leak, but it's still questionable why it gets generated each and every frame. It should probably be enough, to make that just once.

**Comment by asuessenbach** [comment]
... to just prevent all those error message, one could as well just crank up the `MAX_DEFERRED_LIGHT_COUNT` in `rendering/subpasses/lighting_subpass.h` to 48, fitting the number of points lights in that scene.

**Comment by gary-sweet** [comment]
> ... to just prevent all those error message, one could as well just crank up the `MAX_DEFERRED_LIGHT_COUNT` in `rendering/subpasses/lighting_subpass.h` to 48, fitting the number of points lights in that scene.

Sounds good to me. It does slow the subpasses sample down a little, but I'm ok with that.
