### ISSUE TITLE
Solution swamped with shader projects

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#1156]
With PR #1130, the solution (VS2022-speak) is filled with lots of top-level shader projects.
Is that intended?
Shouldn't we at least move them into some "shaders"-folder, or so?

**Comment by SaschaWillems** [comment]
100% not intended.  Somehow didn't happen when I reviewed it, but when doing a cmake clean and full rebuild of the project I get that too. Moving them into a folder would be an option, but I'd rather prefer not having them at all. Shaders are already accessible from the respective samples.

@gpx1000 : Any suggestions?

**Comment by gpx1000** [comment]
top level shader projects?  Does VS now make cmake tasks into shader projects?!?  <sigh>...  sorry not intended...  Maybe let's move them into folders for now, and let's look into making them subtasks for each sample; which probably is the *right* way to do it.
