### ISSUE TITLE
struct HPPVertex missing glm::vec3 color member in hpp_api_vulkan_sample.h

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/Vulkan-Samples#1161]
Commit d0fda1b added member `glm::vec3 color` to the `Vertex` struct in **api_vulkan_sample.h**.  However, the corresponding `HPPVertex` struct is now missing the same entry in **hpp_api_vulkan_sample.h**.  It's likely just an oversight, but causes a bunch of problems for hpp samples as can be seen below:

![Screenshot 2024-09-11 at 10 59 06 AM](https://github.com/user-attachments/assets/5313c9fb-953f-400f-b87a-596a1ad9aa7b)

**Comment by SaschaWillems** [comment]
Tbh. as someone adding new samples I always have a hard time getting things right with having so much code duplicated as C/C++. The odd thing is that I did a full batch run back then and didn't notice any problems.

I think we should move that struct to a central place and deduplicate it to avoid such problems in the future.

**Comment by asuessenbach** [comment]
> I think we should move that struct to a central place and deduplicate it to avoid such problems in the future.

Agreed, that would be the best solution. Someone has to do it...
With #1162, we have a quick fix on the current situation, though. Should merge that soon.
