### ISSUE TITLE
Assets for dynamic_rendering_local_read sample not available

### ISSUE THREAD

**Issue by hrjanardhan** [KhronosGroup/Vulkan-Samples#1163]
Dynamic rendering local read sample looks for the following assets in assets/ folder, but they're not present.
* scenes/subpass_scene_opaque.gltf
* scenes/subpass_scene_transparent.gltf

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. We still need to merge the asset PR. Until that's done you can grab them from https://github.com/KhronosGroup/Vulkan-Samples-Assets/pull/23/files
