### ISSUE TITLE
[For discussion] Update C++ standard requirement to 20

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#1167]
I think we discussed this in one of our meetings, but wanted to write it down so we won't forget about it. Right now we use C++17, but updating to C++20 would give us e.g. designated initializes. Using them would improve code readability in many places.

Not sure if all our target platforms support C++20 though.

**Comment by gary-sweet** [comment]
In addition to a recent compiler toolchain, if we are thinking about using modules we would also need to bump the minimum cmake version to 3.28

**Comment by marty-johnson59** [comment]
Individual samples can enable 2.0 as needed.  Closing this for now
