### ISSUE TITLE
Failed assert and crash when clicking two mouse button same time when using free camera

### ISSUE THREAD

**Issue by burak-efe** [KhronosGroup/Vulkan-Samples#1176]
To produce: open a sample that use free camera, click two mouse button at the same time.
Looks like there is two type of camera base class in repo, I'm talking about that used in performance samples.

Issue was getcomponent returning an empty cameras vector but this happens only when clicking two buttons at the same time for some reason.

https://github.com/KhronosGroup/Vulkan-Samples/blob/5daac4d8b0988b7a18ec8a486d7b973e3dc72d47/framework/scene_graph/hpp_scene.h#L37-L54

**Comment by SaschaWillems** [comment]
Will take a look. It actually crashes even when you only right click (at least in the samples I tested).
