### ISSUE TITLE
Multisampling and sRGB issue

### ISSUE THREAD

**Issue by matteomeli** [KhronosGroup/Vulkan-Samples#1182]
I have noticed some issues with the resulting displayed colours of the MSAA sample. When I select MSAA from the drop down list (any sample count) the scene appears much darker. If I choose no MSAA instead, the scene appears much brighter, looking correct.

With MSAA:
![image](https://github.com/user-attachments/assets/7c55d674-a73b-466b-bfdf-b2cd8661dbda)

Without MSAA:
![image](https://github.com/user-attachments/assets/c14139f3-f881-4488-aa58-32610b982e0b)

This is on my laptop with an AMD Radeon RX 7700S (discrete), but it also happens with the integrated chip AMD Radeon 780M.

I wrote a much simpler program to just load a texture onto a quad, and I can reproduce the same issue. If I load the texture and create its view with VK_R8G8B8A8_SRGB format, then, if multisampling is enabled, it appears much darker. With multisampling enabled, f I load it with  VK_R8G8B8A8_UNORM, then it will appear fine. But if I then disable multisampling, it appears very bright.

On my desktop (Intel UHD Graphics 630 and NVIDIA GeForce RTX 2080 SUPER), the issue doesn't reproduce at all, again with either card.

Any idea what's going on? Is it a known driver issue about multisampling and sRGB on AMD cards?

Driver details are:
AMD Software Adrenaline Edition Version: 23.40.18.02
AMD Windows Driver Version: 31.0.24018.2001

**Comment by SaschaWillems** [comment]
If you can reproduce this in a simple app, it's most probably a driver issue and nothing we can fix.

Sample looks and works fine for me on an RTX 4070 and a Google Pixel 4a.

**Comment by matteomeli** [comment]
Yeah was worried it could be that.

Have you tried, or could you try, the sample on AMD GPU?

**Comment by jeroenbakker-atmind** [comment]
I tried on an M2 and a Arc and was not able to reproduce. I can test AMD early November

**Comment by mdrost** [comment]
I am just following [Vulkan Tutorial](https://docs.vulkan.org/tutorial/latest/index.html) and probably encountered the same problem.  
Code from [Generating Mipmaps](https://docs.vulkan.org/tutorial/latest/09_Generating_Mipmaps.html) chapter gives me normal colors:
![obraz](https://github.com/user-attachments/assets/30e3ee55-5184-484c-822a-e07e894b2878)
Code from [Multisampling](https://docs.vulkan.org/tutorial/latest/10_Multisampling.html) chapter gives me darker colors:
![obraz](https://github.com/user-attachments/assets/f991ab34-b964-495d-9de7-3c83a0b19e92)
If for [Multisampling](https://docs.vulkan.org/tutorial/latest/10_Multisampling.html) chapter I change `VK_FORMAT_R8G8B8A8_SRGB` to `VK_FORMAT_R8G8B8A8_UNORM` then colors are fine.  
The same change for [Generating Mipmaps](https://docs.vulkan.org/tutorial/latest/09_Generating_Mipmaps.html) chapter gives brighter colors:
![obraz](https://github.com/user-attachments/assets/3fb07631-2038-4afe-9612-4846ed376566)

I am using Windows 11 with AMD Ryzen 7 7800X3D and AMD Radeon RX 7900 XTX.  
Driver Version: 24.10.29.01-240714a-406784C-AMD-Software-Adrenalin-Edition  
AMD Windows Driver Version: 32.0.11029.1008

**Comment by SaschaWillems** [comment]
Can you open an issue with your GPU vendor? Most probably nothing we can fix on our side.

**Comment by marty-johnson59** [comment]
Hi @matteomeli, we're closing this as it appears to be a vendor bug - please reopen if this is not the case.  Thanks!

**Comment by mdrost** [comment]
@matteomeli Can you test the sample again with newest drivers? It seems the issue is gone for me.

**Comment by matteomeli** [comment]
> [@matteomeli](https://github.com/matteomeli) Can you test the sample again with newest drivers? It seems the issue is gone for me.

Unfortunately this still happens for me, after I have updated drivers to most up to date available for this machine (Framework laptop 16):
AMD Software Adrenaline Edition Version: 24.20.60.01
AMD Windows Driver Version: 32.0.12060.1002
