### ISSUE TITLE
Play YUV420P video on android platform

### ISSUE THREAD

**Issue by mandagod** [KhronosGroup/Vulkan-Samples#1190]
Playing a YUV420P video on android platform, what parts of the Vulkan Samples project need to change and what parts to keep? I didn't see  an examples of video rendering. Thx

**Comment by SaschaWillems** [comment]
We have no Vulkan video related samples right now. The only ones I know of are these from nvidia: https://github.com/nvpro-samples/vk_video_samples

**Comment by mandagod** [comment]
> We have no Vulkan video related samples right now. The only ones I know of are these from nvidia: https://github.com/nvpro-samples/vk_video_samples

Are there plans to add examples like video rendering in the future?

**Comment by gpx1000** [comment]
Yes these samples are coming
