### ISSUE TITLE
Typo in swapchain_images_tutorial.md

### ISSUE THREAD

**Issue by locke-li** [KhronosGroup/Vulkan-Samples#121]
**The typo:**
In section [Double buffering or triple buffering?](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/performance/swapchain_images/swapchain_images_tutorial.md#double-buffering-or-triple-buffering), the last reference image link should be called **Triple buffering at <60 FPS**, I suppose? It shows **Double buffering at <60 FPS** when the image is still loading.

**Some questions:**
1.For triple-buffering, we need an additional swapchain image allocated, so we will require more memory for this image and maybe some static buffer, right?

2.If some FPS control exists in the application, so we can choose to lower it to save battery. Does that affect how we choose between VK_PRESENT_MODE_FIFO_KHR and VK_PRESENT_MODE_MAILBOX_KHR?

3.Can we safely go for double buffering if we cap FPS to 30, if we guarantee GPU can finish the rendering well within 33ms, to squash down memory usage?

**Comment by JoseEmilio-ARM** [comment]
Thank you for letting us know! Regarding your questions:
1) Correct, more images will require more memory to back them up.
2) I think in this case it may not make a difference on performance, but FIFO is the only mode that is [guaranteed ](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPresentModeKHR.html) to be supported everywhere.
3) I think so, capping FPS to 30 means there should not be any benefits from using more than 2 images and as you say this saves memory.

A resource I found very useful to learn more about the swapchain and presentation modes is [API without Secrets: Introduction to Vulkan* Part 2: Swap Chain](https://software.intel.com/content/www/us/en/develop/articles/api-without-secrets-introduction-to-vulkan-part-2.html) by Pawel Lapinski.

Hope that helps!

**Comment by locke-li** [comment]
@JoseEmilio-ARM Thank you! You help me a lot :D.
