### ISSUE TITLE
GLFW may retrieve bad DPI scaling data for the UI

### ISSUE THREAD

**Issue by kiroma** [KhronosGroup/Vulkan-Samples#1242]
I've stumbled upon an interesting issue on my laptop. For every sample in the repository, no matter how back I checked out the samples, the UI would be either invisible or show up incorrectly.
![image](https://github.com/user-attachments/assets/434c5a17-709a-4be6-b489-43f422fe9268)
I've traced this issue to [`GlfwWindow::get_dpi_factor`](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/framework/platform/glfw_window.cpp#L378) where the call to `glfwGetMonitorPhysicalSize` incorrectly reported my 16x10 inches screen as 16x10mm, causing the reported DPI to be 4000.
Statically setting the factor to 1 fixes the issue, I've also tested out clamping the factor between 0.5 and 2 and this seems to still allow for interactable UI.

**Comment by SaschaWillems** [comment]
Can you check with this PR: #1237 and see if that changes anything?

We use glfw as a submodule and haven't updated that in years.

**Comment by kiroma** [comment]
No noticeable difference, unfortunately.
<details>
<summary>new screenshot</summary>

![image](https://github.com/user-attachments/assets/460e4a1d-e4e7-4663-89b5-85c60a6ba3c3)
</details>

I believe this is simply an issue with the laptop / driver reporting the physical size wrong. If I run xrandr I get the same wrong dimensions as well:
```
DP-2 connected primary 2560x1600+0+0 (normal left inverted right x axis y axis) 16mm x 10mm
```
I believe the laptop is trying to report its screen size using inches (as it is a 16 x 10 inch display) but the unit information is lost and thus a bogus value is reported.

**Comment by SaschaWillems** [comment]
Should be fine to close then. No chance we can fix a driver bug in our samples.
