### ISSUE TITLE
How to use Debug Printf in Vulkan-Samples

### ISSUE THREAD

**Issue by kimown** [KhronosGroup/Vulkan-Samples#125]
I follow the official [doc](https://github.com/greg-lunarg/Vulkan-ValidationLayers/blob/46cd6d46eb50fea264236ea99e8daf61ffbffc18/docs/debug_printf.md)

Add file named vk_layer_settings.txt  in root directory
<details>
<summary>vk_layer_settings.txt</summary>
<p>
khronos_validation.enables = VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT
khronos_validation.printf_to_stdout = true
</p>
</details>

Change triangle.vert
```
#extension GL_EXT_debug_printf : enable

debugPrintfEXT("Hit");
```

But when I run `./cmake-build-debug/app/bin/Debug/x86_64/vulkan_samples hello_triangle`, nothing stdout.

**Comment by kimown** [comment]
It works.

**Comment by HugoPeters1024** [comment]
I'm having the same issue, any tips?

**Comment by rebelroad-reinhart** [comment]
make sure the file is in the cwd of your exe and then make sure there are two lines in the file:
khronos_validation.enables = VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT 
khronos_validation.printf_to_stdout = true

if you copy what's in kimown's original post, you'll get one line which doesn't work.
