### ISSUE TITLE
conservative_rasterization validation error: Depth-only image formats can have only the VK_IMAGE_ASPECT_DEPTH_BIT set.

### ISSUE THREAD

**Issue by llyzs** [KhronosGroup/Vulkan-Samples#128]
In ConservativeRasterization::prepare_offscreen(), the framebuffer_depth_format VK_FORMAT_D32_SFLOAT was chosen, but image view creation includes VK_IMAGE_ASPECT_STENCIL_BIT. This gives validation error as title.

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. The depth format is selected based on a list of available formats for your GPU, so the sample needs to check if the actual format returned includes a stencil aspect.
