### ISSUE TITLE
Windows build issue

### ISSUE THREAD

**Issue by wanlizhu** [KhronosGroup/Vulkan-Samples#130]
* CMake generate Visual Studio x64 project
* open generated project and build `vulkan_samples` target

C:\Users\zhuwa.ADS\Desktop\KhronosGroup-Vulkan-Samples\third_party\vma\src\vk_mem_alloc.h(4364,9):  error C2280: 'VmaPoolAllocator<VmaAllocation_T>::Item::Item(void)': attempting to reference a deleted function (compiling source file C:\Users\zhuwa.ADS\Desktop\KhronosGroup-Vulkan-Samples\framework\core\device.cpp)

**Comment by leaf2fire** [comment]
I got around the issue by defining an empty constructor for `VmaPoolAllocator<T>::Item`.

**Comment by SaschaWillems** [comment]
Which Version of Visual Studio are you using?

**Comment by leaf2fire** [comment]
@SaschaWillems If you're referring to me, I'm using 16.6.0. 

Might be relevant: https://en.wikipedia.org/wiki/C%2B%2B11#Unrestricted_unions

**Comment by SaschaWillems** [comment]
I can confirm this. As this works fine on my fork with an updated VMA submodule I guess we need to update our submodule on master. Pinging @JoseEmilio-ARM and @ZandroFargnoli.

**Comment by wanlizhu** [comment]
I’m using Visual Studio 2019, and this issue was fixed by replacing ’VMA’ subdirectory content with the latest VMA code.
