### ISSUE TITLE
Support for deep learning models

### ISSUE THREAD

**Issue by vinorth-v** [KhronosGroup/Vulkan-Samples#153]
Hello, 

I am wondering if there i a plan to make Vulkan API supported by TensorFlow or PyTorch.

In fact, after seeing this performance on a RaspberryPi:
https://www.tomshardware.com/news/nvidia-engineer-vulkan-driver-raspberry-pi-quake-iii-100-fps
I am really curious to try that with Deep Learning models on a Raspberry Pi !

Thank you in advance,
Best regards

**Comment by ghost** [comment]
Hi @vinorth05, 

Have you taken a look at [OpenVX](https://www.raspberrypi.org/blog/openvx-api-for-raspberry-pi/)? It is another Khronos standard dedicated to vision processing amongst other applications. 

[Here](https://www.raspberrypi.org/blog/openvx-api-for-raspberry-pi/) is a very recent Raspberry Pi blog that covers the support for OpenVX on the platform. 

For TensorFlow and PyTorch it would probably be best to contact them directly as it would largely fall to them to support Vulkan and is out of scope for this repo/project. 

I hope this helps! Please feel free to [email me](mailto:kris@khronos.org) or join the[ developer Slack ](www.khr.io/slack)and message me directly on there.
