### ISSUE TITLE
gui endering issues under macosx retina display

### ISSUE THREAD

**Issue by neshume** [KhronosGroup/Vulkan-Samples#158]
Samples gui rendering is not pick able due to hdpi scaling issues.

**Comment by neshume** [comment]
It seems

this fix:
Fix UI scaling issues on Windows #156

breaks on macosx ;o)

**Comment by wasimabbas-arm** [comment]
Can you provide a screenshot of what do you see please? I understand you can't pick/click on it anymore but not sure why.
Is the UI very tiny for you?

**Comment by neshume** [comment]
<img width="1272" alt="Screenshot at Jul 27 14-00-54" src="https://user-images.githubusercontent.com/203608/88535228-3ecf8e80-d012-11ea-8bec-bfefb12b1bde.png">

I have attached a scren shot .. all samples are the same. It's tiny and non pickable (wrong pick coordinates)

**Comment by wasimabbas-arm** [comment]
ok thanks @neshume I can confirm I see the same issue. We should have done more testing on Mac. @PaoloJovon-arm is already looking into this.

**Comment by PaoloJovon-arm** [comment]
Hello @neshume, could you please test https://github.com/PaoloJovon-arm/Vulkan-Samples/commit/d9949acbda1f24ec8a8fab0df3f6edb379b2f742 and see if it fixes the main UI?
(there might still be problems with the debug panel, however - we're currently investigating the issue)

**Comment by neshume** [comment]
the fix is confirmed to fix the issue. but resizing the window messes things up ... :o)
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/203608/88541944-3e3cf500-d01e-11ea-8220-060cb61db95b.png">

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/203608/88542005-5f054a80-d01e-11ea-8258-24440ff5aef4.png">

**Comment by TomAtkinsonArm** [comment]
Hi @neshume, This fix has resolved the issues on my 2015 MacBook Pro 5f9f53756129f670f3609994ac393eca637f8fee. Can you confirm that it has also fixed the issues on your machine. Thanks
