### ISSUE TITLE
HLSL shader support

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/Vulkan-Samples#179]
Hi all,
Excellent stuff of all those samples, do you have any plans to add HLSL shader support as well?

I'm working on game engine and will support D3D12 backend as well, would like to know how Vulkan handles the Vulkan HLSL scenario.

Feel free to close issues if it doesn't make sense for this project.

Thanks

**Comment by SaschaWillems** [comment]
Yes we are already evaluating on how to add HLSL shaders to this repo.

**Comment by Andreyogld3d** [comment]
Also we need a HLSL's support for Mesh Shaders

**Comment by SaschaWillems** [comment]
Mesh shaders are supported in the SPIR-V backend of DXC, see https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#mesh-and-amplification-shaders.

**Comment by SaschaWillems** [comment]
For progress on this, see #961, the list of samples with HLSL support will be tracked in #1014
