### ISSUE TITLE
Not able to perform system test

### ISSUE THREAD

**Issue by dubeyabhijeet** [KhronosGroup/Vulkan-Samples#180]
=== System Test started! ===
        === Running bonza on Android ===
                === Test started: bonza ===
                        (Error) Couldn't find screenshot (D:\Repgithub\tests\system_test\../../output/images/bonza.png), perhaps test crashed
        === Running sponza on Android ===
                === Test started: sponza ===
                        (Error) Couldn't find screenshot (D:\Repgithub\tests\system_test\../../output/images/sponza.png), perhaps test crashed
=== Failed: 0 passed - 2 failed ===

Is something i am missing in my setup?

**Comment by TomAtkinsonArm** [comment]
Are you executing the system test script from the root of the projects directory? 

`D:\Repgithub\tests\system_test../../output/images/bonza.png`

should be more like

`D:\Repgithub\Vulkan-Samples\tests\system_test\../../output/images/bonza.png`

**Comment by dubeyabhijeet** [comment]
Vukan-Samples folder is renamed to Repgithub

**Comment by dubeyabhijeet** [comment]
/output/images/bonza.png this png is the screenshot captured from android phone. Right? I think screenshot is not working

**Comment by dubeyabhijeet** [comment]
Is there any update on this part?

**Comment by TomAtkinsonArm** [comment]
Hey @dubeyabhijeet, Just found some spare time to debug this.

I cloned Vulkan Samples into Repgithub as you mentioned above. I then built the project and the tests crashed when running `python ./tests/system_test/system_test.py -B build -C debug` from the root of the project.

I then realized that tests are not built by default so re-built the project after configuring the build to build tests. `cmake -Bbuild -H. -DVKB_BUILD_TESTS=ON`

Running the previous system test command then gave me the following output

```
python ./tests/system_test/system_test.py -B build -C debug
error: no devices/emulators found
Device not found, disabling Android testing
=== System Test started! ===
        === Running bonza on Windows ===
                === Test started: bonza ===
                        (Comparing images...) 'C:\Projects\Repgithub\tests\system_test\tmp/Windows/bonza.png' with 'C:\Projects\Repgithub\tests\system_test\../../assets/gold/bonza/1028x720.png': 99.8%
                === Failed. ===
        === Running sponza on Windows ===
                === Test started: sponza ===
                        (Comparing images...) 'C:\Projects\Repgithub\tests\system_test\tmp/Windows/sponza.png' with 'C:\Projects\Repgithub\tests\system_test\../../assets/gold/sponza/1028x720.png': 99.23%
                === Failed. ===
=== Failed: 0 passed - 2 failed ===
=== Archiving results into 'C:\Projects\Repgithub\tests\system_test\artifacts\system_test-2020.12.30-16.11.12.zip' ===
```

Here you can see the 99.8% and 99.23% similarity between tests and golds which is classed as a failure.

This means the tests are working correctly. The failure here is to do with running the tests on different hardware and the hardware/driver implementation yielding ever so slightly pixel value results. If you wanted the tests to run perfectly on your device you would need to copy the images created from a test pass on a working version of the project to the assets/gold directories for each test.

**Comment by dubeyabhijeet** [comment]
@TomAtkinsonArm Hi, Understood. Can you guide me any other way to detect any graphical error using automation?

**Comment by TomAtkinsonArm** [comment]
Automatically testing for graphical errors at the point of presentation is an exponential problem. For full coverage you must generate a gold image on each combination of hardware and test against this respective to the device that you are testing on

Personally it seems to be a simply impossible task due to resources. Some bugs just need to be fixed when they occur. That said, my advice if you wanted to graphically test an application would be to select a subset of devices you wish to to support and perform some sort of image comparison test on each device.

Manual testing tends to pick up more visual artefacts currently than that of automatic tests, to my knowledge

Hope this helps!

**Comment by gpx1000** [comment]
FWIW, as in all things context is key.  If you're looking for a generic graphics testing solution; then Tom's answer is perfect.  If however, you are careful and realistic about what your goals are in automated testing, there's plenty that can be truly tested in a graphical system.
Think about breaking down the graphics system.  Approach it as the "Testing Pyramid" expect lots of unit tests and few integration tests.  Unit testing is available.  Math is math is math, thus testing out all the parts of your graphics engine will mean writing Unit Tests the advantage here is you don't actually have to render anything to achieve a proper unit test that validates if your math is correct that you depend upon for the graphics system.
The next thing to test is to think of the idea of running "things that are controlled."  That is things like buttons and GUI interaction.  You can take a screen shot, then detect your UI, and automate interaction with your UI.  There's even tools that will do this for you.  If you want to write your own, I suggest OpenCV and MSER.
The next thing to test is how do fonts look (are they contained within buttons etc).  This is another OpenCV tasking with word detection within the buttons found with MSER.  If the output word doesn't match expectations, then that should flag.

All other visual artifact and graphics testing is a fun challenging exercise.  Just remember getting true generic everything testing is exponentially hard, so test what you can where you can.

**Comment by marty-johnson59** [comment]
See above details on how to do testing
