### ISSUE TITLE
How to use below command in android vulkan_samples --sample afbc --benchmark 5000

### ISSUE THREAD

**Issue by dubeyabhijeet** [KhronosGroup/Vulkan-Samples#181]

**Comment by ZandroFargnoli** [comment]
Currently in Android we don't support custom benchmarking frame counts, the UI will let you start a benchmark for 2000 frames (which you can change inside the code if you'd like to alter this). 

If you run the app so you're in the sample launcher screen (the list of different samples), you can enable benchmark mode with the three dotted menu icon in the top right. Clicking on a sample will then run that in benchmark mode for 2000 frames.

**Comment by ZandroFargnoli** [comment]
Hi @dubeyabhijeet I haven't heard from you so I'll assume that you've worked out how to solve this yourself. 

For anyone else wishing to change the frame count of a benchmark test (on Android), please go to the `project/app/android/java/com/khronos/vulkan_samples/SampleLauncherActivity.java` file, find the `public void setArguments(String... args)` function, and change the value of 2000 to your desired amount (i.e. `arguments.add("5000")`), then rebuild and install :)
