### ISSUE TITLE
hello_triangle renders nothing on macos 10.14.6 / intel iris 655

### ISSUE THREAD

**Issue by acgaudette** [KhronosGroup/Vulkan-Samples#184]
reproduced on a 2018 macbook last night w/integrated graphics.

on hello_triangle you just get the clear color. I was running into similar issues with another project and decided to compile these samples and compare. I have a hunch that this bug is related to rendering with a null vertex input state / vertices from the vert shader / gl_VertexIndex, since this is a commonality between my code and the sample.

texture_loading runs fine (as does vkcube).
figured I'd open an issue here before e.g. moltenVK.

could this be related to mojave? unfortunately I am not able to upgrade the machine in question to catalina at this time.

**Comment by ghost** [comment]
Hi @acgaudette - this is likely MoltenVK related, did you open an issue there?

**Comment by billhollings** [comment]
I've tried to investigate this to see if it's a MoltenVK issue. Unfortunately, when I do, I end up hitting #190 first, before encountering the issue described above.

**Comment by billhollings** [comment]
Okay. I've managed to clear away #190 in my environment, and I've been able to run `hello_triangle`.

I can confirm that the triangle is rendering correctly on the 3 macOS 11.2.2 GPU's I've been able to test:
- Intel HD Graphics 630
- AMD Radeon Pro 560
- Apple Silicon M1

If this is still an issue, it seems to be fairly localized to the GPU driver or macOS version reported.

I don't have access to that GPU or macOS version. If anyone can provide further diagnostic info or testing, it would be helpful.

**Comment by gpx1000** [comment]
Here's a gputrace from xcode running with blank screen.
[vulkan_samples.gputrace.zip](https://github.com/KhronosGroup/Vulkan-Samples/files/6079236/vulkan_samples.gputrace.zip)

**Comment by billhollings** [comment]
@gpx1000 

That looks like a perfectly normal GPU trace, and shows that the triangle has rendered all the way through to being presented.

When you captured this GPU capture, was the displayed window blank as per the original issue?

And if you open the GPU trace on the faulty machine, does it display the rendering as expected, and as it does in this screen capture from my machine?

![Screen Shot 2021-03-03 at 7 18 40 PM](https://user-images.githubusercontent.com/356402/109890690-ba9f5280-7c55-11eb-833b-d435a4bbc196.jpg)

**Comment by gpx1000** [comment]
It's blank.
![Screen Shot 2021-03-03 at 5 25 11 PM](https://user-images.githubusercontent.com/3833955/109896190-5ffdfa80-7c45-11eb-9248-16e10bb0628c.png)

**Comment by billhollings** [comment]
Curious. But makes sense, and is consistent.

As far as I can tell, this is a driver issue.

I've filed bug report FB9029296 to Apple's Feedback Assistant about this for now.

**Comment by marty-johnson59** [comment]
@gpx1000, as you have a machine that can repro this, I'm wondering if there's more digging we can do, or do we close this and leave it with Apple?  @billhollings, do you have suggestions for Steven on what further investigation he could do here?

**Comment by gpx1000** [comment]
I think it makes sense to close this and leave it with Apple as I agree this is likely a driver issue.  @marty-johnson59

**Comment by marty-johnson59** [comment]
OK, I'll go ahead and close. If someone feels this is in error, please re-open and we'll see if there's more we can do, but it looks like and Apple issue.
