### ISSUE TITLE
vulkan_asset_pack_gltf.zip is not availaible

### ISSUE THREAD

**Issue by sev-ludwig** [KhronosGroup/Vulkan-Samples#188]
Im not able to download the assets. Neither with the py-script nor manually from http://vulkan.gpuinfo.org/downloads/vulkan_asset_pack_gltf.zip

**Comment by SaschaWillems** [comment]
The assets you're referring to are from a different set of samples (https://github.com/SaschaWillems/Vulkan). For the samples in this repo, the assets are included as a submodule. So you need to clone the repo with sub modules, or manually update them after cloning.

**Comment by ghost** [comment]
Assets for this repo can be found at: https://github.com/KhronosGroup/Vulkan-Samples-Assets
