### ISSUE TITLE
third party is not feed when dowloading Vulkan-Samples

### ISSUE THREAD

**Issue by hterrolle** [KhronosGroup/Vulkan-Samples#210]
I spend Two day tryng to install your sample to be used with Android studio an windows OS. I put the mess intalling new EDI in my hold project. A lot of time losed.

And i just find out that Vulkan-Samples-master\third_party is empty. So it is impossible to compile because android native ndk do not hold these cpp hpp ... files.

regards.

**Comment by wasimabbas-arm** [comment]
Did you follow the instructions in the readme? specifically the way to clone it:

```
git clone --recurse-submodules https://github.com/KhronosGroup/Vulkan-Samples.git
cd Vulkan-Samples
```

If yes you should have received everything in `third_party` if you still haven't please submit a complete log of what's the output of that command. Otherwise it's very hard to help with the information you have provided.

Also not sure I understand what you mean by the NDK issue. If you are building for Android, setting up your environment has nothing to do with the Samples repo itself so its out of scope. We do mention the dependencies in the build instructions for Android though.

**Comment by hterrolle** [comment]
Hi,

I already use Github for dowloading zip version but i did not know that some folder could be hided. To use git i must install it and bacause i do not use it for project participation i never done it. 
The problem is that you cannot see if the donwloading project is complete or not.

The sample is also done for android so it is not out of the scope. Gradle for example depends on the IDE version for NDK which depends from the API version. It all related in fact. And when you change the IDE many yhings must be change in old projects like the gradle wrapper. It is a little mess all the time, new syntax, new obligation. It is a real nightmare ;)).

So if i new that the donwload was not complete i would have donwloaded the missing folder first before changing IDE.

Why allowing a donwload with half of the need ? This should have been explain or i should have be able to find it out.

In the donwload the third party folder look fine. nobody could know that it is empty when donwloaded. And if i go further some missing file could be for more deep in the tree and i will have to look at all the folder to find the missing one.

Why make it avalaible for donwload if it is not complete ? why to force using installing git if not real use ? 

Any way it does not matter but i am sur that i am not the only one in this case.  I will look at all folder and donwload the needed one.

**Comment by SaschaWillems** [comment]
That's unfortunately nothing we can change. The zip files are generated by github, and github simply does not put the submodules into those zip files.

So the recommended way is to pull the repository via git, which will pull all the submodules.

**Comment by hterrolle** [comment]
I just donwloaded GitHubDesktopSetup.exe and and error SeDefaultDllDirectories  in KERNEL32.dll.

I am sorry but it look like something is missing inside again ;)) . I am joking now but in you case i better watch out what you are doing because 2 time in 3 days it a little bit to much for your réputation. 

can you tell me which git can be used directly with android. Something working would be better.

;)) i like to joke. It is a pitty because it is a good idea to share compute information and code. 

Bonne continuation.

**Comment by hterrolle** [comment]
Happy end ;))

I manage to get everything using Git. And i am quite surprise of the sample work. It seems very complete. So bravo to the team. And sorry for been a little bit rude. To old to change ;)).

sincerely Bravo.
