### ISSUE TITLE
Some obstacles when trying to build android. 

### ISSUE THREAD

**Issue by Eths33** [KhronosGroup/Vulkan-Samples#214]
I found what might be an issue. Or it may help someone else.

When trying to run the samples on android from android studio. After clicking run in android studio, I then click on a sample from the app menu (on my connected phone) and the app crashes. When trying to debug, I saw the error bellow in the code block. I followed step 1 and step 2 in the build.md then went to android studio. 
Android Gradle Plugin Version: 3.3.0, Gradle Version 4.10.1, ndk\21.2.6472646

Initial error after step 1 & 2:
```
error: module importing failed: No module named renderers.jb_lldb_logging_manager
File "temp.py", line 1, in <module>

error: 'jb_renderers_set_diagnostics_level' is not a valid command.
error: Unrecognized command 'jb_renderers_set_diagnostics_level'.
error: module importing failed: No module named renderers.jb_lldb_declarative_formatters
  File "temp.py", line 1, in <module>

error: 'jb_renderers_loaders_add' is not a valid command.
error: Unrecognized command 'jb_renderers_loaders_add'.
error: 'jb_renderers_load' is not a valid command.
error: Unrecognized command 'jb_renderers_load'.
error: 'jb_renderers_load' is not a valid command.
error: Unrecognized command 'jb_renderers_load'.
error: 'jb_renderers_load' is not a valid command.
error: Unrecognized command 'jb_renderers_load'.
error: 'jb_renderers_load' is not a valid command.
error: Unrecognized command 'jb_renderers_load'.
```

------Second try----- 
After I tried step 3 and the command didn't work as shown. I saw this:
```adb: error: failed to get feature set: more than one device/emulator```

Without -t
```adb: failed to install build/outputs/apk/debug/vulkan_samples-debug.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]```

The following command worked: 
adb -s AQH7N17C18011026 install -r -t build/outputs/apk/debug/vulkan_samples-debug.apk 

To get devices:
adb devices

global options:
-s SERIAL  use device with given serial (overrides $ANDROID_SERIAL)

app installation:
-r: replace existing application
-t: allow test packages

After the modified step 3 I tried running from android studio again and it worked. (forgot if I tried it immediately after step 3).

**Comment by dubeyabhijeet** [comment]
Why you are using Studio to build? Use command prompt method mentioned in build docs

**Comment by Eths33** [comment]
Okay. I was not aware studio was not reccomended. 
Thanks for letting me know.

Could you expand on why though?
