### ISSUE TITLE
Dynamic uniform buffers sample renders incorrectly on Android

### ISSUE THREAD

**Issue by r-potter** [KhronosGroup/Vulkan-Samples#217]
This is giving me a either a black screen or renders garbage on both Mali and Adreno devices. This occurs on the master branch as well as multiple PRs. Tested on Note 10 and Note9. 

Self-assigning for further investigation

**Comment by TomAtkinsonArm** [comment]
@r-potter did you get to look into this? Does this issue still exist in the project?

**Comment by marty-johnson59** [comment]
Hi Ralph, we're just triaging old bugs...closing this for now, but feel free to re-open if you think it still needs to be addressed.  Thx
