### ISSUE TITLE
Gitlab CI Scripts

### ISSUE THREAD

**Issue by DigitalInBlue** [KhronosGroup/Vulkan-Samples#229]
This project has a nice set Gitlab-CI integration, but it references many python scripts in `/usr/local/bin/` that are not provided with the project.  Are these in another repository or could they be added to this repository so I can run this pipeline locally?

**Comment by TomAtkinsonArm** [comment]
This has been in consideration but won't be looked at until the new year.

Currently we use clang format and clang tidy helper scripts that can be found in the official releases and other pipelines. [Here is a version used in the chromium project](https://chromium.googlesource.com/chromium/llvm-project/cfe/tools/clang-format/+/refs/heads/master/git-clang-format). Other binaries used from the bin directory are publicly accessible Open Source Software such as Doxygen. There are also two other scripts used, one for snake case checking which uses flex and a custom lexer and another that uses regex to check if we have included the correct copyright. These are currently not accessible.

System tests should run locally but there are some issues such as #180 which have are to be looked into.

I would suggest installing docker and pulling [khronosgroup/vulkan-samples](https://hub.docker.com/r/khronosgroup/vulkan-samples) to explore the CI environment used for the custom tests.

**Comment by TomAtkinsonArm** [comment]
Hey @DigitalInBlue, Do you need any more info? Can we close this issue?

**Comment by DigitalInBlue** [comment]
Thank you.  Yes.  You can close the issue.  The information was helpful!

**Comment by TomAtkinsonArm** [comment]
Glad i could help!
