### ISSUE TITLE
Build on Windows doesn't find python

### ISSUE THREAD

**Issue by observant2** [KhronosGroup/Vulkan-Samples#233]
Hi!
With CMake 3.19, Visual Studio 2019 (16.8.3), Python 2 and Python 3 installed, cmake only found Python 2.
I had to change all instances of "PythonInterp" to "Python" in the CMakeLists.txt to make it work.
The error message with PythonInterp is:
```
1> [CMake]   Could NOT find PythonInterp: Found unsuitable version "2.7.17", but
1> [CMake]   required is at least "3" (found C:/Python27/python.exe)
```
It also seems that "PythonInterp" is deprecated. Just wanted to leave this here in case anyone else has the same problem.

**Comment by abbaswasim** [comment]
Is this the same a #193. Unfortunately all of these dependencies are coming from third party modules. So it should be reported there?

**Comment by gpx1000** [comment]
https://github.com/KhronosGroup/glslang/pull/2503 <-- fix is already upstream.

**Comment by greg-lunarg** [comment]
A while back a change was made to glslang such that Python was **always** required to build. A more recent change https://github.com/KhronosGroup/glslang/pull/2526 has removed this requirement, especially when building glslang to **only** compile GLSL.

If indeed the samples only need to compile GLSL, moving up to the latest version of glslang will remove the Python dependency, and obviate the problem noted by this issue.

If this is not the case, please file an issue directly against glslang.

@marty-johnson59
