### ISSUE TITLE
Cannot debug with gdb

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/Vulkan-Samples#251]
I get an error saying 'no line number information' when I try to debug the 'vulkan_samples' executable:

https://gist.github.com/fctorial/e7187ea834a28e5fae6ca3732f43c912

The gdb version is 9.2 and the gcc version is 9.3.

**Comment by gpx1000** [comment]
gdb is complaining that it can't find the source code.

https://sourceware.org/gdb/current/onlinedocs/gdb/Source-Path.html

The easiest way from the command line is to launch vulkan_samples executable with the current working directory in the source directory.

The **really** easy way is to use an IDE.  I personally use CLion, just set the executable's current working directory and it does the rest.

**Comment by ghost** [comment]
I'm running gdb from the `Vulkan-Samples` directory. gdb is looking for a file `sysdeps/x86_64/start.S`. There's no such file on my system:

```
(gdb) l
1       ../sysdeps/x86_64/start.S: No such file or directory.
(gdb) b create_vulkan_samples()
Breakpoint 1 at 0x47f6c0
(gdb) r hdr
Starting program: /home/fctorial/src/pgs/Vulkan-Samples/build/linux/app/bin/Release/x86_64/vulkan_samples hdr
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Breakpoint 1, 0x000000000047f6c0 in create_vulkan_samples() ()
(gdb) l
1       in ../sysdeps/x86_64/start.S

```

**Comment by marty-johnson59** [comment]
@fctorial do you have sufficient direction to track this one down?  Unfortunately, this doesn't seem to be anything the samples team can solve as we don't have ability to control gdb requirements, but let us know if we can help further and if we can close this issue.  Thanks!

**Comment by ghost** [comment]
Yes, I suppose it's not a problem in the vulkan samples project.
