### ISSUE TITLE
Replace explicit file definitions by using GLOB (CMake 3.12)

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#255]
As of CMake 3.12 `GLOB` can be used with `CONFIGURE_DEPENDS` when selecting source files to compile. This is an improvement on previous `GLOB` behaviour as it re-configures the build system if the outputs of `GLOB` changes.

>If the CONFIGURE_DEPENDS flag is specified, CMake will add logic to the main build system check target to rerun the flagged GLOB commands at build time. If any of the outputs change, CMake will regenerate the build system.

https://cmake.org/cmake/help/v3.12/command/file.html#glob

This could be used within the `framework` and `samples` CMakeLists to improve readability and maintenance

**Comment by r-potter** [comment]
I just checked what the Android Studio IDE uses as it's built in cmake, and it appears to be 3.10 (at least on my installation)

**Comment by gpx1000** [comment]
I personally am not a big fan of using glob in CMakeLists.txt.  It has an awful habit of encouraging forgetfulness and sloppy placement of files with unintended consequences.
That said, I have no issue with this solution despite AS shipping with 3.10.  AS is easy to configure for system CMake installs.

**Comment by TomAtkinsonArm** [comment]
Checking my AS I can install up to 3.18 through the sdk tools prompt.

I like the idea that our current set up does force some extra thought in how the project is structured and what files are added

Closing the ticket for now
