### ISSUE TITLE
Set up the issue template

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-Samples#257]
Looking at #187, it would be nice to have an issue template with a comment saying something like this:
> if you are experiencing an issue running samples on Vulkan Portability (macOS/iOS/other), please consider filing them to  https://github.com/KhronosGroup/Vulkan-Portability instead, or the relevant VkPI implementation ([MoltenVK](https://github.com/KhronosGroup/MoltenVK) or [gfx-portability](https://github.com/gfx-rs/portability)).

cc @marty-johnson59

**Comment by marty-johnson59** [comment]
OK, I added an issue template with your suggested text.  Check it out and LMK if this works.  Thanks,

Marty

**Comment by kvark** [comment]
Looks good, thank you!
We can make it better by turning `MoltenVK` and `gfx-portability` into links, like in my example.

**Comment by marty-johnson59** [comment]
Hmm, I tried adding a link with the documented syntax ([link] (URL)), but it doesn't seem to work when embedded in a comment.  LMK if you know how to do this (I'm new to working with mark-down..).  For now, the URLs are listed, but you have to cut/paste...
