### ISSUE TITLE
RP multithreading has some problems in android

### ISSUE THREAD

**Issue by runner0353** [KhronosGroup/Vulkan-Samples#260]
My mobile phone is HUAWEI P40. This example is very stuck when it runs. cpu cycles is unavailable

**Comment by SaschaWillems** [comment]
Can you elaborate? Is the sample running slow, not working at all, or is it just missing some of the performance metrics displayed in the UI?

**Comment by runner0353** [comment]
very slow 
![Screenshot_20210406_050819_com khronos vulkan_samples](https://user-images.githubusercontent.com/36179001/113627541-431a7400-9696-11eb-992f-ab39a1767eea.jpg)

**Comment by r-potter** [comment]
Is this a debug build rather than a release build by any chance?

**Comment by runner0353** [comment]
yes

**Comment by r-potter** [comment]
The release build should provide large performance improvements on this particular sample. In my case I observed >10X speedups with a release build.

**Comment by marty-johnson59** [comment]
@runner0353, does this resolve the issue, or is there still work to do on this one?  Thanks
