### ISSUE TITLE
Add option to close console window after running sample using --benchmark on Windows

### ISSUE THREAD

**Issue by rumblehhh** [KhronosGroup/Vulkan-Samples#263]
WindowsPlatform::terminate currently pauses waiting for input after running the samples in benchmark mode on Windows i.e running:  "vulkan_samples --sample msaa --benchmark 100" will run the sample for 100 frames, exit the sample but keep the console window open waiting for user input - the enter key to be pressed.

Is there any possibility of adding a command line option or similar to avoid this behaviour?

**Comment by TomAtkinsonArm** [comment]
Currently partially implemented

**Comment by TomAtkinsonArm** [comment]
![image](https://user-images.githubusercontent.com/48598630/114473804-cf73ec00-9bec-11eb-9e2a-5bc0c4464c55.png)

Benchmark mode now doesn't stop by default. You can use the flag `--stop-on-close` to optionally halt the app after execution.

Desktop only as android doesn't support halting

**Comment by rumblehhh** [comment]
Amazing. I'm glad to see the default has been made "non-halt". Has this gone to master or is it sat in #254?

**Comment by TomAtkinsonArm** [comment]
Sat in #254 for now as this PR heavily changes how the CLI is maintained and how CLI features are implemented

If you would like to disable this behaviour sooner you may remove `benchmark_mode` at [windows_platform.cpp](https://github.com/KhronosGroup/Vulkan-Samples/blob/30e0ef953f9492726945d2042400a3808c8408f5/framework/platform/windows/windows_platform.cpp#L145). This will allow the app to continue as expected
