### ISSUE TITLE
VSync differences between samples based on different classes, no way to toggle vsync

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#266]
It looks like API-Samples are always running with uncapped framerates, where as the samples based on the ARM-framework always run with capped framerate.

There is currently no way to toggle this, and from a quick look at the framework, it looks like this requires a more complex change to make this work.

This should be unified in such a way that vsync can be enabled/disabled via a command line switch and the swap chain then picks the proper present mode, no matter what framework the sample is based on.

**Comment by TomAtkinsonArm** [comment]
Should be implemented by #254 or in a PR after. Should be disabled by default (Vulkan Samples call 12/04)

Possibly using `--vsync` / `--use-vsync` / `--vsync-enabled` to toggle its use
