### ISSUE TITLE
Texture and scene files are missing for the texture_mipmap_generation sample

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Samples#28]
The [cpp file](https://github.com/KhronosGroup/Vulkan-Samples/blob/af0dbc2ec3a872688265e355d997070fd50813ac/samples/api/texture_mipmap_generation/texture_mipmap_generation.cpp#L318) for this example references `textures/checkerboard_rgba.ktx` and `scenes/tunnel_cylinder.gltf` but these files are not present under the assets folder.  

Running the example throws an exception when the KTX loader fails to find the file.

**Comment by SaschaWillems** [comment]
The PR containing those files hasn't been merged into master yet: https://github.com/KhronosGroup/Vulkan-Samples-Assets/pull/5

@wasimabbas-arm: Can you take a look at this and merge the asset PR if possible?

**Comment by jherico** [comment]
@SaschaWillems thanks... I chekced the PRs on this repository and looked at the assets repo, but didn't think to check the PRs there.  This tends to be the problem with git submodules in my experience... keeping them in sync becomes a pain in the ass.

**Comment by ghost** [comment]
Asset now merged in the asset repo.

**Comment by jherico** [comment]
The upstream repository has had the file added, but _this_ repository hasn't had it's submodule commit ID updated.  Also, the current submodule commit 1c6c656 isn't in the master branch, so either 1c6c656 needs to get merged into master or master needs to be merged into 1c6c656, and the resulting commit added to the assets repo, and referenced in this repo.

**Comment by wasimabbas-arm** [comment]
https://github.com/KhronosGroup/Vulkan-Samples/pull/45 fixes that please close the issue if you agree.
