### ISSUE TITLE
Was this block of codes redundant?

### ISSUE THREAD

**Issue by QSXW** [KhronosGroup/Vulkan-Samples#282]
https://github.com/KhronosGroup/Vulkan-Samples/blob/04278ed5f0f9847ae6897509eb56d7b21b4e8cde/framework/core/device.cpp#L187
https://github.com/KhronosGroup/Vulkan-Samples/blob/04278ed5f0f9847ae6897509eb56d7b21b4e8cde/framework/core/device.cpp#L188-L194
Was this block of codes redundant? Because the checking of `present_supported`  has been done above using the member function, `is_present_supported()`, of `PysicalDevice`.

**Comment by SaschaWillems** [comment]
Yes, the second part is indeed redundant and not required at all. I think it's safe to remove it.
