### ISSUE TITLE
fail to parse sample id

### ISSUE THREAD

**Issue by nightingalei** [KhronosGroup/Vulkan-Samples#287]
Ubuntu 18.04
Vulkan-Samples cloned and built just now

Bug:
Fail to parse sample id.

Build Step
```
cmake -G "Unix Makefiles" -H. -Bbuild/linux -DCMAKE_BUILD_TYPE=Release
cmake --build build/linux --config Release --target vulkan_samples -- -j4
```

Run sample
```
./build/linux/app/bin/Release/x86_64/vulkan_samples --sample  hello_triangle
```
Result
```
[info] Logger initialized
[info] Window created
[error] [build/linux/app/main.cpp:80] Failed to find a create function for 
```

Reason
The assert macro evaluates to nothing in release build with NDEBUG is defined.
https://github.com/KhronosGroup/Vulkan-Samples/blob/47c5237be21209afc945e43d03ae409fa80a0155/framework/platform/parser.h#L220

**Comment by TomAtkinsonArm** [comment]
I was able to reproduce this. Moved the call outside of the assertion and retested the Samples in release. This change seems to fix the problem.

Please test #288 and let me know if the issue is resolved

Cheers :)

**Comment by nightingalei** [comment]
It works for me! 
Thank you very much :)
