### ISSUE TITLE
Default image usage bits for vkb::Swapchain wrapper appear incorrect

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Samples#29]
The predominate usage for a swapchain image is to attach it to a framebuffer and render directly to it, or the render to something else and blit to the swapchain image.  This corresponds to a usage of `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT` and `VK_IMAGE_USAGE_TRANSFER_DST_BIT`. 

However, the default flags in the swapchain constructors [here](https://github.com/KhronosGroup/Vulkan-Samples/blob/af0dbc2ec3a872688265e355d997070fd50813ac/framework/core/swapchain.h#L82) and [here](https://github.com/KhronosGroup/Vulkan-Samples/blob/af0dbc2ec3a872688265e355d997070fd50813ac/framework/core/swapchain.h#L95) are `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT` (correct) and `VK_IMAGE_USAGE_TRANSFER_SRC_BIT` (_incorrect_).

**Comment by ZandroFargnoli** [comment]
@jherico There is no need for us to be setting `VK_IMAGE_USAGE_TRANSFER_DST_BIT` by default. It should be only requested if it is needed on a per-sample basis, as there can be a performance hit to adding this flag. 

Furthermore, the reason we use `VK_IMAGE_USAGE_TRANSFER_SRC_BIT` is so we can copy the contents of the swapchain images to disk storage in a screenshot function, which is important for system testing.

I will close this issue, please feel free to reopen if you have an argument against this.
