### ISSUE TITLE
Feature Request: CLI Arguments for Khronos Validation Layer Options

### ISSUE THREAD

**Issue by samwalls-arm** [KhronosGroup/Vulkan-Samples#295]
I find that whenever I want to use the additional validation layer objects from the Khronos VL, I have to re-learn how to enable them, either through finding the appropriate `vk-layer-settings.txt` settings names and enums, or through finding out the appropriate environment variables.

I propose that we add CLI options to Vulkan-Samples which use the Khronos VL's "programmatic interface" to enable validation layer objects (such as best-practices, GPU-assisted validation, synchronisation etc.).

Something like:

```
--validation-best-practices
--validation-gpu-assisted
--validation-synchronisation
```
(there may be more appropriate and vulkan-consistent names to use)

Additionally, it may be a good idea to expose some additional object-specific options. For example, enabling Arm-specific best-practices. I'm not sure how much configuration is possible at the moment, with the programmatic interface.

With these changes, the validation layer options would be more visible and immediately-usable to anyone using Vulkan-Samples.

Let me know if you have any thoughts whether this is useful, and how to improve it.

Additional information, see the "programmatic interface" mentions on these pages:
- [best-practices validation](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/best_practices.md)
- [GPU-assisted validation](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/gpu_validation.md)

**Comment by samwalls-arm** [comment]
One objection to this feature request is that one can simply use Vulkan-Configurator. I think CLI args like this could still be easier for everyday development and quick testing, given that.

**Comment by marty-johnson59** [comment]
Addressed - did these w/ cmake args
