### ISSUE TITLE
Feature request: optimize the repository for search engines

### ISSUE THREAD

**Issue by JoseEmilio-ARM** [KhronosGroup/Vulkan-Samples#296]
Issue: currently Google Search does not seem to be indexing the sample tutorials, would need to find a way to optimize the repository for search engines.

A possible solution could be creating a set of [GitHub Pages](https://docs.github.com/en/pages) for the repository.

**Comment by TomAtkinsonArm** [comment]
Would we need two branches. One to store the generator such as hugo or jekyl project; The second to store the built static site?

**Comment by marty-johnson59** [comment]
Closed as the new Gighub Pages approach fixes this..
