### ISSUE TITLE
Automated tracking of MD changes to be translated

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#303]
As mentioned on the last few Samples calls, translation of markdown to languages other than English can be incorrect using translation APIs. A suggested solution is to notify translators when a change has occurred to markdown files and allow them to manually change the translated MD. This means that the format of how translations are saved is a decision by the group and wont be automated

### Simplest Solution

Add an item to the checklist to notify translators manually when a change to markdown has occurred

### Little Better

Create an action to look for changes in mark down and append comments to PRs which ping translators automatically (Only once per PR)

### Even Better (Less blocking off contributions)

Create an action to look for changes in mark down and append comments to an issue for a given PR. This means that PRs are not blocked by translations and they can be translated at a later date where the issue contains a history of the changes needed.

I haven't look into this being possible but GitHub has a full API that can be used with CI tokens to perform lots of different actions on a users behalf. This means there is a high chance that it is achievable.

**Comment by SaschaWillems** [comment]
I think we can completely rethink this with Antora. It has built-in language support.
