### ISSUE TITLE
Vulkan HPP Framework Discussion

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#304]
Hey @asuessenbach, It would be great to discuss the Vulkan HPP Framework changes before the next call :)

### Overview

> Demonstrate more use cases with the Vulkan HPP API. This may require the recreation of another framework using Vulkan HPP instead of the C style API. A selection of API and performance samples would be ported to show its benefits ~ paraphrased from previous conversations

My biggest concern with duplicating the framework is that when larger parts are refactored in one of the frameworks then these will need to be reflected in the other; the same applies for samples. Replicating existing samples would mean that contributors will need to take more factors into account - there is already an ever increasing check list on PRs.

### Is this a good direction?

I'm worried that direct ports of samples will generate more work in the future without providing much value for the developers looking at these samples. For instance, the inner workings of hello triangle have not been changed. We are simply seeing the same code written in a different style. This is similar to to-do list examples across programming languages in the sense that the added value for a developer is learning dramatically different syntax. In this case, the C style API covers all the Vulkan syntax that a developers needs and the HPP is "syntactic sugar".

It may be a better use of time to find how the HPP API can be used in comparison to the C style API when tackling specific problems in Vulkan. Are there any scenarios where we can show one API greatly simplifying concepts for developers or reducing the size of code footprints for specific features?

One example of this could be showing the benefits of: not using a shared context, current framework; using a shared context, shared pointer to a struct of common handles and using the HPP style API to not require tracking lower level handles - device, instance etc... Or possibly rethinking resource management with tracking structs of handles vs tracking hpp vulkan objects... Can hello triangle be written in a more simple way using HPP...

### Summary

Overall, I think it is great to add more HPP. It just may be more beneficial to demonstrate its pros/cons through new samples rather than maintain two copies of the current codebase

**Comment by marty-johnson59** [comment]
Folks can correct me if I get this wrong, but my take-away from last week's discussion is that we wanted to minimize the need for framework changes - just enough to support samples written with C++ bindings (as well as continuing to support C-binding samples) and then we'd re-implement a handful of samples using C++ (API samples and some perf samples) so folks can use their language-binding of choice and/or learn about pros/cons of each.  To manage the maintenance issues of having two versions of some of the samples, the team was hoping we could use CI to flag when one changes - to remind devs to make their changes in both.  Not sure if that's possible tho...hoping Tom can advise.

**Comment by asuessenbach** [comment]
@marty-johnson59 That's exactly my take-away as well.
It was considered to be better to have two separate branches, one for C-bindings and one for C++-bindings, with (more or less) corresponding content. Whenever something changes in the one branch, one should verify if that change should be ported to the other branch as well.
As both the framework and the (to-be-transcoded) samples were considered to be pretty stable, we did not expect substantial maintenance work.
@TomAtkinsonArm Maybe you have a wrong impression of what vulkan.hpp is. It does not manage resources or provide higher level functionality. It's still as verbose and detailed as the C-bindings. But it provides better type safety, more compile-time error checking, simplified function and structure handling, better readability, maybe more C++-feeling.
That is, transcoding existing samples from C-bindings to C++-bindings would exactly show the benefits.

**Comment by TomAtkinsonArm** [comment]
> It was considered to be better to have two separate branches, one for C-bindings and one for C++-bindings, with (more or less) corresponding content. Whenever something changes in the one branch, one should verify if that change should be ported to the other branch as well.

As I missed the call, the definition here for me is still a little hazy. It sounds like we are comparing the benefits of C++ and C - if, as stated, the C++ API provides no benefit other than having C++ properties (using namespaces and typed enums, etc) then what added value will porting a large amount of code bring other than show it written in a slightly different style?

It feels as though the benefits you listed would be better expressed through an in-depth tutorial showing why these are desirable and why the C++ API is better in some respects. Even better, making the hello triangle sample more robust by replacing some of the hard coded logic with more robust checks which the framework makes to demonstrate more of the C++ properties. This way we avoid the nightmare of tracking differences and maintaining a diverged codebase.

> To manage the maintenance issues of having two versions of some of the samples, the team was hoping we could use CI to flag when one changes - to remind devs to make their changes in both. Not sure if that's possible tho...hoping Tom can advise.

We could create an action to compare parts of both frameworks. It would be easier to add an item to the checklist stating that changes should be replicated in both frameworks as its heavily dependant on how the framework is ported - which elements are ported.

> we did not expect substantial maintenance work

This is dependant on how the port is done. If it is only the required components then its possible that we wont need to revisit it again for future contributions to the base project. If it is the majority of the project being ported then this will mean each contribution must be split into two PRs to target both branches with identical changes


<br /><br />


I just want to make sure we are taking into account that there will be future development on the project, things will inevitably change and this may lead to maintaining two branches with, essentially, identical code? The main questions that could clear this up for me are:

- Will porting several samples show any more difference than the port in hello triangle?
- Could we provide the same value without maintaining two of the same codebase?
- Could we port the framework in a way where only the original project would need continued maintenance?
- Will contributions to the second branch go through the same review process?

**Comment by wasimabbas-arm** [comment]
> just enough to support samples written with C++ bindings

I don't think this is trivial work though, with unclear ROI to me.

> It was considered to be better to have two separate branches, one for C-bindings and one for C++-bindings

Maintaining two different branches for any future framework/samples work is going to be painful. If anything I worry it will turn into a competition both branches developing like forks with different set of samples and framework features. Because of favourite languages and what not.

> transcoding existing samples from C-bindings to C++-bindings would exactly show the benefits.

This makes sense as a goal for the vulkan hpp project but does it apply to vulkan samples project?  Most of the performance samples are less about how to use an API but more about which ones to use amongs the different options available. Only the API samples would benefit from this so If anything I would recommend we have a sample of how to use `vulkan.hpp` as an API sample and leave it there. That makes more sense. (I am told there is already such thing in review). Regarding other benefits of vulkan.hpp, like type safety etc, we have already gone through that pain in the framework. So it probably doesn't bring any benefit to framework developers/maintainers.

**Comment by asuessenbach** [comment]
> what added value will porting a large amount of code bring other than show it written in a slightly different style?

That's what the samples are for: show it written in code. Such that any interested guy can grab it as a starting point. Up to now, there's close to no such starting point for the C++bindings.

>It feels as though the benefits you listed would be better expressed through an in-depth tutorial showing why these are desirable and why the C++ API is better in some respects.

Having such a tutorial is a good idea, indeed. And I don't see samples and tutorials as exclusive.

>avoid the nightmare of tracking differences and maintaining a diverged codebase.

I think, that's the most important point. In the meeting on 7/12, it was considered to be an acceptable burdon, but if we now come to the conclusion that it's too labor intensive, we should look for an alternative approach.

> If it is only the required components...

I don't have an in-depth knowledge of the framework, but it seems the parts there are very closely meshed. That is, probably a substantial part of the framework would need to be transcoded.

> Will porting several samples show any more difference than the port in hello triangle?

I think, at least a couple of the API samples would be good, to make sure different aspects are shown. And some of the perf samples would be great, to show any performance differences (if there are any).
When porting just the hello_triangle sample, the framework "port" could probably be pretty small.

> Could we provide the same value without maintaining two of the same codebase?

Without having thought about the details, it should probably be possible to refactor the framework to live with either the C-bindings or the C++-bindings. But that for sure would make it more complex, and all the current samples might need some adustments.

> Could we port the framework in a way where only the original project would need continued maintenance?

I don't understand this question. What do you imagine?

> I would recommend we have a sample of how to use vulkan.hpp as an API sample and leave it there

Yes, there is the transcoding approach on hello_triangle. But it can't be completely separated from the framework, as the vkb::Instance is instantiated there, and one platform makes more than trivial use of it.
I've modified that PR (https://github.com/KhronosGroup/Vulkan-Samples/pull/294) to run with some slightly extended framework files.

**Comment by asuessenbach** [comment]
After the short discussion on this issue in the last call, I think transcoding (most of) the framework is not considered an option any more. That is, the first now would be just the transcoded version of the hello_triangle sample (#294).
To conclude with that PR, I just have two questions:
1. Is the naming (hpp_hello_triangle) and the location (samples/api) ok?
2. Is the additional flavor of Window::create_surface, and DirectWindow::find_compatible_plane, and the "intrusion" of vulkan.hpp into the framework acceptable?

**Comment by asuessenbach** [comment]
And a third question:
3. How can we ensure that changes in hello_triangle are ported to hpp_hello_triangle, and vice versa.

**Comment by TomAtkinsonArm** [comment]
Are you still interested in creating an in-depth tutorial on Vulkan HPP? Would this be best in a separate PR?

> Is the naming (hpp_hello_triangle) and the location (samples/api) ok?

As it is showing API usage, this seems like a suitable place for the sample

> Is the additional flavor of Window::create_surface, and DirectWindow::find_compatible_plane, and the "intrusion" of vulkan.hpp into the framework acceptable?

These additions allow the sample to be run across supported platforms. The framework isn't in a state where these additions can be added in a better way. So for this PR, these additions are the best option for now

> How can we ensure that changes in hello_triangle are ported to hpp_hello_triangle, and vice versa.

We could add an item to the PR checklist, something like:

- [ ] Changes to Hello Triangle are reflected in HPP Hello Triangle

**Comment by asuessenbach** [comment]
> Are you still interested in creating an in-depth tutorial on Vulkan HPP? Would this be best in a separate PR?

Yes, to both questions. I can't tell, when I can start on that tutorial, though.

**Comment by TomAtkinsonArm** [comment]
Is #294 ready for a re-review?

**Comment by asuessenbach** [comment]
yep
