### ISSUE TITLE
VK_SUBOPTIMAL_KHR is handled incorrectly

### ISSUE THREAD

**Issue by olvaffe** [KhronosGroup/Vulkan-Samples#305]
When `VK_SUBOPTIMAL_KHR` is returned by `vkAcquireNextImageKHR`, the image is still acquired.

In `vkb::RenderContext::begin_frame` (and elsewhere), when `handle_surface_changes` skips swapchain recreation, it should not try to acquire another image.

**Comment by JoseEmilio-ARM** [comment]
Good point! perhaps `handle_surface_changes` could return a `bool` indicating that the swapchain was updated. Currently it looks like it's just `begin_frame` where we are acquiring twice. Would you be able to submit a PR with a fix?

**Comment by marty-johnson59** [comment]
Closing as I believe this should be addressed with PR #338.  Please re-open if needed.
