### ISSUE TITLE
Potential mismatch of PhysicalDevice in hello_triangle with DirectWindow on platform/unix

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#306]
In samples/api/hello_triangle, the VkPhysicalDevice to be used is just the first of the enumerated physical devices:

```
	// Select the first GPU we find in the system.
	context.gpu = gpus.front();
```

But in framework/platfrom/unix/direct_window.cpp, DirectWindow::create_surface, a "suitable" one is selected:

`	auto phys_dev = instance.get_suitable_gpu().get_handle();
`
which, in this case, is the first discrete gpu encountered.

Those two might be different.

**Comment by asuessenbach** [comment]
Seems, this is already resolved in direct_window.cpp.
Closing.

**Comment by asuessenbach** [comment]
No, it's not already resolved, just changed.
hello_triangle now tries to take the first VkPhysicalDevice that supports graphics and present.
DirectWindow::create_surface still takes the first discrete GPU.
Those might differ.

**Comment by TomAtkinsonArm** [comment]
Is this similar to the discussion at #234?

**Comment by marty-johnson59** [comment]
Per discussion today, we're closing this (and #234) as it's not clear if further action is needed.  Please re-open if there's more to do (and help us determine best path to address).  Thanks.
