### ISSUE TITLE
Update CI to use gradle for Android?

### ISSUE THREAD

**Issue by ggfan** [KhronosGroup/Vulkan-Samples#318]
Gradle is the default build script for Android, it would be good to use it in Action CI.  Gradle wrapper is preferred (Android Gradle Plugin and gradle version could be in locked step), so the needed gradle version could be downloaded automatically.

**Comment by TomAtkinsonArm** [comment]
Hi @ggfan, currently we configure the android project with CMake but the underlying build is undertaken by gradle using the android sdk. The exact versions used can be found in the dockerfile under `.github/docker/Dockerfile`. From what I see changing these to gradle commands such as `gradle assembleDebug` will not provide any added benefit?

I may have miss understood your meaning, could you elaborate more on this?

**Comment by ggfan** [comment]
Oh, sorry for the confusion: I need to follow up more on the Action code path. I could not import the generated build.gradle into Android Studio project: I probably missed something, may you help confirm Android Studio works with the generated build.gradle?  thank you so much!

**Comment by SaschaWillems** [comment]
Are you getting any errors? I can import the project from the generated gradle file just fine in Android Studio.

**Comment by ggfan** [comment]
on my linux system:
 - cmake inside  $PATH(generic CMake): 3.18.4
 - cmake in $sdk/cmake:  3.10.2, 3.18.1-g262b901
 "Open" project with Android Studio (it complains about cmake ' Invalid revision: 3.18.1-g262b901`);  then updated the agp version to 4.2.1, it would complain about gradle version (needs 6.7.1, rather than my 6.5), in this case I tried to create gradle/wrapper/gradle-wrapper.properties with 6.7.1 version in it. At this point, I could compile, the new error:
```
in file included from /usr/local/google/home/gfan/proj/vk-samples/Vulkan-Samples/app/vulkan_samples.h:23:
In file included from /usr/local/google/home/gfan/proj/vk-samples/Vulkan-Samples/build/android_gradle/build-native/cmake/debug/armeabi-v7a/app/samples.h:64:
/usr/local/google/home/gfan/proj/vk-samples/Vulkan-Samples/samples/extensions/ray_tracing_reflection/ray_tracing_reflection.h:84:25: error: cannot initialize a member subobject of type 'VkDeviceMemory' (aka 'unsigned long long') with an rvalue of type 'nullptr_t'
``` 
With given cmake detection, the behavior could be different: depends on your studio version, installed cmake versions in the 2 places mentioned above.

I have not tried with the newly released Android Studio, if the latest one works for you, kindly let me know.

**Comment by SaschaWillems** [comment]
Just updated my Android Studio copy and it no longer works for me too. So it seems that there is a problem with the most recent Android Studio. 

One additional question: What Android NDK version are you using?

**Comment by SaschaWillems** [comment]
I can confirm the compilation error. It looks like that was a warning and has been promoted to an error with recent Android NDK versions. This affects only one sample. I'll provide a PR to fix this.

**Comment by ggfan** [comment]
The ndkVersion used is: 21.4.7075529. It might be better to fix the version in the build script, as the used ndk is decided among:
- ndkVersion config in build.gradle ( i.e. ndkVersion '23.0.7599858' )
- default ndk version embedded [inside android gradle plugin](https://developer.android.com/studio/projects/install-ndk#default-ndk-per-agp), the version is the latest ndkVersion with which the specific Android Gradle Plugin version was tested: different AGP version will, for sure, have different NDK version embedded.
- ndk could be auto-installed at compile time (if license term has been agreed before on the machine you are building code).

The logic for ndk resolution is a little involved(ndk.dir, $sdk/ndk-bundle, $sdk/ndk/..., ndkVersion, default NDK version etc.), just fix it(similar to cmake.version you are doing) with:
- configure your used NDK with `android.ndkVersion`
so sample could have a more consistent behavior.

The cmake you are using may not be the version shipped inside $sdk: gradle takes cmake already inside $PATH with higher priority. CMake is also auto-downloadable from AGP 4.2.0, but complicated a bit:
-[ license has been accepted before](https://developer.android.com/studio/projects/install-ndk#install_ndk_and_cmake_automatically)
- $SDK supported version, literally 3.6.4111459, 3.10.2.4988404, 3.18.1 (i think)
$SDK shipped CMake version may have (slightly) different behavior from the same one at cmake.org, hopefully it will not affect this sample. 
With all of those, fix the cmake may be good; fix to a version you are using when generating android build script; use a version that is outside $sdk's cmake version would force to a version directly from cmake.org. 

hopefully by fixing ndk and cmake version in build.gradle, one could download and focus on sample rather than those build script things.

**Comment by TomAtkinsonArm** [comment]
@SaschaWillems is it worth me bumping the versions in the docker image?

**Comment by SaschaWillems** [comment]
Most probably yes. I think we should investigate a bit though. Android NDK seems so fragile and things break so often that we need to make sure to not break anything before updating to the latest releases.

**Comment by ggfan** [comment]
inside build.gradle.in, if update gradle plugin version to 4.2.2 (its default is Java11, not Java8 though), then ndkVersion could be specified explicitly [here](https://github.com/KhronosGroup/Vulkan-Samples/blob/b2fe4a4b89078b93985d838cd097ba17b06b4df7/bldsys/cmake/template/gradle/build.gradle.in#L24) with
  ndkVersion 'your-current-ndk-version'

The exact version string varies, but the revision string(used it as-is) in $your-ndk/source.properties should be ok.

(NDK version could be updated later after a new version is fully tested working with the sample, but AGP version has to be updated with 3.5+ in order to recognize `ndkVersion`, details are [here](https://developer.android.com/studio/projects/configure-agp-ndk?language=agp4-1#agp-version))
