### ISSUE TITLE
Make ImGui overlay usable in ray tracing samples

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#331]
As discussed on today's call, we want to make the ImGui overlay available to ray tracing samples so they can e.g. add option toggles. Right now this is not possible, as the ImGui overlay requires a render pass (which is not required for ray tracing). This is a tracking issue for documentation purposes, a PR to make this work will follow.

**Comment by QSXW** [comment]
Hi. Is it able to render the result of Ray Tracing as a color attachment of Framebuffer, and display the color attachment in the ImGui::Image() function? This is a common way that I used to render multiple targets in an editor, but I am not sure if it could work with Ray Tracing or suitable for your requirements.

**Comment by SaschaWillems** [comment]
My PR will do it differently.
