### ISSUE TITLE
Bump CI Android Versions

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#336]
As discussed a new wiki page has been populated with versions of android build dependencies which work for myself https://github.com/KhronosGroup/Vulkan-Samples/wiki/Known-Issues#android-studio-build-failures. If we need to change these versions then this is the issue to discuss this further.

Once we have agreed that these versions are currently the latest supported I will bump the versions in our docker image. Its worth noting that the build is successful for an S21 target, I do not have other devices to find failures in different SDK versions.

@SaschaWillems thoughts on the new wiki page and stated supported versions? Do you use any which are newer and also build?

**Comment by SaschaWillems** [comment]
The wiki page looks good. I slightly updated it, and also added a note on the broken CMake 3.18.1 version included with the Android SDK.
