### ISSUE TITLE
Crash after fullscreen

### ISSUE THREAD

**Issue by lukaprsina** [KhronosGroup/Vulkan-Samples#337]
When I press CTRL+F (Toggle fullscreen mode) on my arch linux desktop running GNOME 40, it fakes the fullscreen. The window is maximized and the top bar is hidden. When I try that on the app, it crashes.

In the file framework/rendering/render_context.cpp in the function RenderContext::begin_frame(), we acquire the next image. If the result is suboptimal or out of date, we check for updated extend and update the swapchain. Then back in begin_frame, we acquire the next image again and check the result. If it isn't successful, the frame is reset and we return. That than triggers an assert that the frame isn't ready.

https://github.com/KhronosGroup/Vulkan-Samples/blob/fd4dc37e5ce272a5ba0b34b5a8e259090231e12e/framework/rendering/render_context.cpp#L340

System specs (inxi -F):

```
System:
  Host: arch Kernel: 5.13.13-arch1-1 x86_64 bits: 64 Desktop: GNOME 40.4 
  Distro: Arch Linux 
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME H270M-PLUS v: Rev X.0x 
  serial: <superuser required> UEFI: American Megatrends v: 0320 
  date: 11/22/2016 
CPU:
  Info: Quad Core model: Intel Core i7-7700 bits: 64 type: MT MCP cache: 
  L2: 8 MiB 
  Speed: 800 MHz min/max: 800/4200 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 801 6: 801 7: 800 8: 800 
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 470.63.01 
  Device-2: Sonix USB 2.0 Camera type: USB driver: snd-usb-audio,uvcvideo 
  Display: x11 server: X.org 1.20.13 driver: loaded: nvidia 
  unloaded: modesetting resolution: <missing: xdpyinfo> 
  Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:
  Device-1: Intel 200 Series PCH HD Audio driver: snd_hda_intel 
  Device-2: NVIDIA GP104 High Definition Audio driver: snd_hda_intel 
  Device-3: Sonix USB 2.0 Camera type: USB driver: snd-usb-audio,uvcvideo 
  Sound Server-1: ALSA v: k5.13.13-arch1-1 running: yes 
  Sound Server-2: PulseAudio v: 15.0 running: yes 
  Sound Server-3: PipeWire v: 0.3.34 running: yes 
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e 
  IF: enp0s31f6 state: up speed: 100 Mbps duplex: full 
  mac: 2c:4d:54:56:d2:66 
Drives:
  Local Storage: total: 3.89 TiB used: 73.57 GiB (1.8%) 
  ID-1: /dev/sda vendor: Crucial model: CT275MX300SSD1 size: 256.17 GiB 
  ID-2: /dev/sdb vendor: Western Digital model: WD40EFRX-68N32N0 
  size: 3.64 TiB 
Partition:
  ID-1: / size: 48.87 GiB used: 30.16 GiB (61.7%) fs: ext4 dev: /dev/sda3 
  ID-2: /home size: 687.94 GiB used: 43.41 GiB (6.3%) fs: ext4 
  dev: /dev/sdb3 
Swap:
  ID-1: swap-1 type: file size: 1024 MiB used: 116 MiB (11.3%) 
  file: /swapfile 
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 287 Uptime: 1h 40m Memory: 15.57 GiB used: 5.57 GiB (35.8%) 
  Shell: fish inxi: 3.3.06 
```

**Comment by lukaprsina** [comment]
If I force set the result of the second acquire image call to VK_SUCCESS by adding a line below the second call

`result = VK_SUCCESS;`

vulkan crashes later at

`void Queue::submit(const std::vector<VkSubmitInfo> &submit_infos, VkFence fence) const`


`Validation Error: [ VUID-vkQueueSubmit-pWaitSemaphores-00069 ] Object 0: handle = 0x682e8d0000000236, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x5555568d6e98, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xef858864 | vkQueueSubmit(): pSubmits[0].pWaitSemaphores[0] Queue VkQueue 0x5555568d6e98[] is waiting on semaphore (VkSemaphore 0x682e8d0000000236[]) that has no way to be signaled. The Vulkan spec states: All elements of the pWaitSemaphores member of all elements of pSubmits must be semaphores that are signaled, or have semaphore signal operations previously submitted for execution (https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#VUID-vkQueueSubmit-pWaitSemaphores-00069)`

**Comment by gpx1000** [comment]
Hi Luka,

Thanks for the issue and suggest fix.  You're a few versions ahead of me in GNOME, however, is there any indication as to why after a screen resize the width and the height are maintained at the same size?  If that's the case it might point to an underlying issue that would manifest by having the wrong new resolution after the full screen event (things might look pixelated).
Is that the case for you when you run the fix you're proposing?  If it is then we're likely going to need to do a little more digging.  Maybe look into if you're using glfw, or the native unix windowing platform in your build.  One of those is likely not notifying that the swapchain should be at a new resolution.

Thanks,
Steve

**Comment by lukaprsina** [comment]
I added some log calls to keep track of the swapchain extent.  (586499d9fc7646ea2fc44c150ed2b1f032d181b0)

My fix is reverted by not using the force_update parameter in RenderContext::handle_surface_changes.

The output doesn't show any weird extent sizes. Everything look normal until acquire_next_image at once returns VK_ERROR_OUT_OF_DATE_KHR. By calling vkGetPhysicalDeviceSurfaceCapabilitiesKHR in the same scope as the assert I checked if the surface is weird but it all seems normal.

PS: The app doesn't crash immediately after fullscreen. Surprisingly, it takes a varying amount of frames. Sometimes a second, two or less or more.

The original commit is still the best attempt for now (c5b957a79715020054a4a81ecfd6bc285dc50d54).

[The output as html](https://drive.google.com/file/d/1JnGCQiXy7ibVP1d4KdDYKlXRw6CWsmKr/view?usp=sharing)

I tried to keep color with "aha", but it didn't work. Oh well...
Search for:
```
...

[warning] SW::CREATE: 1280, 720;

...
// Here I went fullscreen
[warning] RC::HANDLE_SURFACE_CHANGES current: 3440, 1440;
[warning] RC::HANDLE_SURFACE_CHANGES surface_extent: 1280, 720;

...

[warning] SW::CREATE: 3440, 1440;

...

[warning] RC::previous surface: 1280, 720;
[warning] RC::current surface: 3440, 1440;
[warning] RC::previous saved: 1280, 720;
[warning] RC::surface_extent saved: 3440, 1440;

...
```

Then it crashed.

SW::CREATE is from the swapchain create info and RenderContext::HANDLE_SURFACE_CHANGES is logged when the surfaces mismatch and the swapchain will be updated.

Render context current surface is directly from the vulkan call vkGetPhysicalDeviceSurfaceCapabilitiesKHR and surface_extent is a member variable. Previous versions are from previous frames. This got logged only if the previous frame had a different surface than the current one.

Cheers,
Luka

**Comment by gpx1000** [comment]
Does this happen on every sample?

**Comment by lukaprsina** [comment]
Yes it does happen no matter what. The issue probably isn't the app's fault. We need to rebuild the swapchain.

**Comment by gpx1000** [comment]
This is very interesting.  If I'm understanding you correctly, what's happening is that you transition to full screen one time, which is effectively one and only one resize event.  The proper windowing resize function is called and then it will crash some variable time later.
The logs seem to indicate if I'm understanding them correctly, that the surface is changing after the full screen event just randomly on its' own?!?  I'm not even sure how this is possible.
Lemme ask, do you see this behavior on normal resizes?
I think your PR is probably the right way to go for now.  But there's something deep here that I'm not understanding.

**Comment by lukaprsina** [comment]
Everything seems normal on window resize events, that is the resolution is correct, no errors or warnings of any kind and the swapchain is being created with success.

I don't really know where this is coming from, but maybe it is the x11 server or the gnome display manager GDM. It's GDM's job to handle making the pseudo fullscreen.

**Comment by danilw** [comment]
@lukaprsina this can be related https://github.com/KhronosGroup/Vulkan-Samples/issues/250
look there comment about Nvidia driver

solution - do not use Nvidia or do not use X11
