### ISSUE TITLE
Fragment shading rate loses device on resize

### ISSUE THREAD

**Issue by gpx1000** [KhronosGroup/Vulkan-Samples#341]
Resizing the window on the Fragment shading rate causes a lost device on next frame draw.

**Comment by SaschaWillems** [comment]
What platform does this happen? The sample resizes fine for me on Windows 10 with an RTX 2060. Do you get a validation layer message before the device lost?

**Comment by gpx1000** [comment]
Happens in Linux no validation error

**Comment by gpx1000** [comment]
I figured out the bug; we have the same one in our fragment shading rate dynamic sample we're working on.  The problem stems from invalidating the image views before calling the super class resize().  This is fine if the resize doesn't follow the easy out of checking to ensure the new size isn't the same as the previous size before calling the create_framebuffer() call which both of our samples override.
I have a fix I'm including in our sample and I went ahead and fixed it in the fragment shading rate sample too.
