### ISSUE TITLE
Updated CMake requirement may be problematic on Android

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#346]
With the merge of the plugins branch, the CMake requirement was raised from CMake 3.10 to 3.12.

Android Studio only offers CMake 3.6, 3.10 and 3.18. Sadly the CMake version 3.18 offered by google is broken, so right now there is no way to compile the samples with an up-to-date Android studio.

I'm not sure how we should handle this. The easiest way would be dropping the CMake requirement back to 3.10, though I'm not sure if that's possible.

**Comment by TomAtkinsonArm** [comment]
On it. 3.12 introduced some helpful macros, these can be reverted back to 3.10 for now until there is a more stable version supported by all platforms

**Comment by SaschaWillems** [comment]
Thanks a lot :) If you have Android Studio, can you test if CMake 3.18 fails for you too? I'm currently running with NDK r22, but last time I checked, CMake 3.18 was also broken in the most recent r23 NDK.

Update: Also happens with NDK r23.

**Comment by TomAtkinsonArm** [comment]
`Invalid revision: 3.18.1-g262b901-dirty`?
