### ISSUE TITLE
float16_t sample doesn't workaround basic issues that occur on Android and Nvidia

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/Vulkan-Samples#363]
I'm trying to enable float16_t use so that GLSL shaders when transpiled to Metal use half.  This is a trivial thing to write in MSL, but seemingly difficult aspect to address in Vulkan.   That all now works.

We now want float16_t use on Android and other platforms, but I've only so far found Mali devices that implement both the storage and shader extension used in the sample.   Adreno parts only implement the shader extension, and leave off storage.   And Nvidia parts have both, but don't implement inputOutput16.  I can't speak for PowerVR parts, but since iOS is so easy, I assume they are too.

So we're enabling the VK_KHR_shader_float16_int8, have --target-env=vulkan1.1, and have the corresponding GL extension at the top of the shaders.   This works fine on Mali, but on Adreno parts spits out the following.  It's unclear if this is due to missing fields in VK_KHR_shader_float_controls, the spirv codegen, etc.  There are far too many variables unlike MSL where half just works on all macOS and iOS devices.

I AdrenoVK-0: Shader compilation failed for shaderType: 1
I AdrenoVK-0: Info log: Assertion failed: false && "Unknown floating point rounding mode"

These are links to all the issues trying to get this to even work.  And then trying to pass half out of the vertex shader to save parameter buffer space, and then into the fragment shader is not possible without the 16bit_storage extension, or if present, if the inputOutput16 subfield of that is false.   

This is the Adreno issue
https://developer.qualcomm.com/forum/qdn-forums/software/adreno-gpu-sdk/68815

Here's an example of the Google Pixel 3a device that has float16_int8, but not 16bit_storage.  So the given sample wouldn't run.
https://vulkan.gpuinfo.org/displayreport.php?id=10427#properties_extensions

This was my first attempts to enable half on Vulkan, and the pitfalls.
https://github.com/google/shaderc/issues/1177#

This is the most realistic writeup of trying to use half with Vulkan on the web currently but for HLSL and not GLSL.
https://therealmjp.github.io/posts/shader-fp16/

**Comment by gpx1000** [comment]
It's certainly not a bad idea in the future to create a sample that would show float16 use; I don't think any of the samples exhibit this issue currently.

It also looks like you have the right person at Qualcomm in your issue link; you're already talking to.  I'd like to recommend we go ahead and close this issue here.  
@marty-johnson59 <-- including you as I don't want to click "Close" without someone else reviewing this to make sure the close recommendation is correct.

**Comment by marty-johnson59** [comment]
Just verifying before we close...is there no issue with the samples to fix here (just driver issues)?  Should we turn this into a request to add float16 sample(s) in the future?

**Comment by alecazam** [comment]
This is an issue with how you actually write half shaders given the minefield of missing functionality and extension in Vulkan.  The sample only handles compute shaders.

Nvidia doesn't have 16bit_storage.inputOutput16, AMD doesn't have 16bit_storage.pushConstant16, Adreno only has. 16bit_storage.storageBuffer16, Mali has all the fields of 16bit_storage.   It's so complex, that Adreno parts die with "unsupported rounding mode" crashes even though they advertise shader_float16_int8 support.

So how is one supposed to write shaders that work across all Vulkan platforms that use float16_t even if just that extension is present?  This involves casts into and out of the shaders, and multiple reflections of fp16 and fp32 uniform buffers.  For now, we'll ignore Nvidia and Adreno parts to simplify our shader portability.  Most samples I see are pure fp32, but that's not ideal for mobile.  So since nothing exercises these paths, they remain broken or underdeveloped.

**Comment by marty-johnson59** [comment]
All good points.  We discussed this with the samples team and unfortunately, this is not currently in scope for us.  Some of these issues seem driver specific. We definitely suggest working with vendor support to address driver issues (they're typically quite good ).  Of course, we always welcome contributions, so if you find a good way to navigate this and want to contribute a sample to illustrate, we would be more than happy to review!  In the meantime, I'll close this issue, but please re-open (or open a PR) if there's further we need to consider.  Thanks.
