### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by GainLee** [KhronosGroup/Vulkan-Samples#364]
### I use command "./gradlew assembleRelease" for building and get error below. Anyone help

Task :configureCMakeRelWithDebInfo FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':configureCMakeRelWithDebInfo'.
Cannot invoke "String.equals(Object)" because "line" is null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 922ms
15 actionable tasks: 2 executed, 13 up-to-date

**Comment by SaschaWillems** [comment]
Do you have a local CMake installation that's in your system's path? If so, please remove it from your path as gradle picks up that version instead of the one from the NDK, which doesn't work for android.

If that doesn't help, we have a lengthy discussion on Android build issues in #293.

**Comment by gpx1000** [comment]
It's also worth mentioning that Java should be at a min of 11.

**Comment by GainLee** [comment]
After setting my java to 11 and remove local cmake from path, with ndk 23.0.7599858, the issue has gone.

But now I'm in trouble in third_pary, like
CMake Error at <workspace>/Vulkan-Samples/third_party/CMakeLists.txt:348 (set_property):
    set_property could not find TARGET spdlog_headers_for_ide.  Perhaps it has
    not yet been created.

Are these third_pary necessary?

**Comment by SaschaWillems** [comment]
spdlog is included as a submodule. Did you clone the repo with submodules?

**Comment by GainLee** [comment]
> spdlog is included as a submodule. Did you clone the repo with submodules?

I clone with submodules failed, and I clone submodules manually. I'm trying to clone the repo with submodules again.

**Comment by GainLee** [comment]
> spdlog is included as a submodule. Did you clone the repo with submodules?

I cloned all submodules manually as my network speed is not well, and still get the error above about spdlog. Then I found that I need to check out these submodules' heads to linked commit. 
After doing that, it was built successfully.

Thanks all.  The issue will be closed.
