### ISSUE TITLE
[Windows] How can I log the output to the terminal?

### ISSUE THREAD

**Issue by expenses** [KhronosGroup/Vulkan-Samples#372]
Hi. I'm having a problem starting the raytracing_extended sample, but I can't give you any more information as the log output is sent to a spawned console that closes when the sample exits. Is there a way to not spawn this console window, and instead log to the terminal that runs `vulkan_samples.exe`? Thanks.

**Comment by SaschaWillems** [comment]
Sadly, there is currently no option to redirect that output to e.g. a file. But the window is actually supposed to wait for a key press and should not close without interaction. I guess the sample throws an error that's not properly handled.

Are you able to run it from your IDE?

**Comment by expenses** [comment]
I don't use an IDE - just Sublime Text and VSCode. Is there a way to run the samples on their own without `vulkan_examples.exe`? Perhaps by compiling them into executables instead of libraries?

**Comment by gpx1000** [comment]
You can run a debugger outside of visual studio and capture the output.

As you're in windows, the command I believe, is windbg.  Here's a link showing how to utilize that:
https://riptutorial.com/windbg/example/19170/important-commands

**Comment by SaschaWillems** [comment]
We recently added an option to output log messages to a log file:

`vulkan_samples.exe sample afbc --log-file afbc.txt`

Does that work for you?

**Comment by expenses** [comment]
Yep, that works!
