### ISSUE TITLE
Run sample error on android 11

### ISSUE THREAD

**Issue by GainLee** [KhronosGroup/Vulkan-Samples#374]
Error information blow

VulkanSamples: [error] [+:149] Error Message: Failed to open file: /storage/emulated/0/com.khronos.vulkan_samples/shaders/triangle.vert
 E VulkanSamples: [error] [+:150] Failed when running application hello_triangle

**Comment by SaschaWillems** [comment]
That sounds like the assets haven't been uploaded to the device. This is done during the build via adb, but only if the device is connected at that time (and only one device).

You can do that manually though, see [the build instructions](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#3d-models) on how to do that.

**Comment by GainLee** [comment]
> That sounds like the assets haven't been uploaded to the device. This is done during the build via adb, but only if the device is connected at that time (and only one device).
> 
> You can do that manually though, see [the build instructions](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#3d-models) on how to do that.

I found that the path on the doc does not match that the code used.
Path on doc: /sdcard/Android/data/com.khronos.vulkan_samples/files/ 
Path used by code: /storage/emulated/0/com.khronos.vulkan_samples

I synced files to "/storage/emulated/0/com.khronos.vulkan_samples" and it works
