### ISSUE TITLE
 OpenGL Interoperability crash in system with multiple GPU

### ISSUE THREAD

**Issue by danilw** [KhronosGroup/Vulkan-Samples#378]
OS Linux
First GPU AMD `VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU`
Second GPU Nvidia `VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU`

`vulkan_samples sample open_gl_interop` - on launch select Nvidia Discrete GPU for Vulkan, when AMD GPU used for OpenGL.
And Crash - **Segmentation fault**.

```
VUID-vkBindImageMemory-memory-02728(ERROR / SPEC): msgNum: 1038504645 - Validation Error: [ VUID-vkBindImageMemory-memory-02728 ] Object 0: handle = 0x380000000038, type = VK_OBJECT_TYPE_IMAGE; Object 1: handle = 0x390000000039, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x3de652c5 | vkBindImageMemory(): The VkDeviceMemory (VkDeviceMemory 0x390000000039[]) has an external handleType of VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT which does not include at least one handle from VkImage (VkImage 0x380000000038[]) handleType Unhandled VkExternalMemoryHandleTypeFlagBits. The Vulkan spec states: If the value of VkExportMemoryAllocateInfo::handleTypes used to allocate memory is not 0, it must include at least one of the handles set in VkExternalMemoryImageCreateInfo::handleTypes when image was created (https://vulkan.lunarg.com/doc/view/1.2.170.0/linux/1.2-extensions/vkspec.html#VUID-vkBindImageMemory-memory-02728)
    Objects: 2
        [0] 0x380000000038, type: 10, name: NULL
        [1] 0x390000000039, type: 8, name: NULL
```

**Comment by gpx1000** [comment]
I had this same issue, I thought this would fix it:
https://github.com/KhronosGroup/Vulkan-Samples/pull/321/files

Locally I'm testing this on:
OS Linux
First GPU Intel VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
Second GPU NVIDIA VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU

While I am seeing the validation error, I'm not seeing the crash.  Thus those are probably two separate issues.  Would it be possible to get a stack trace or more details on how to reproduce the crash?

**Comment by gpx1000** [comment]
@danilw If I can request, would you mind grabbing the  #381 and testing if the crash still occurs.  The validation error should be addressed.

**Comment by danilw** [comment]
@gpx1000 tested
Validation error gone 0 errors
`open_gl_interop` still crash with **Segmentation fault.**

full launch log:
```
[info] Logger initialized
[info] Initializing Vulkan sample
[info] VK_KHR_get_physical_device_properties2 is available, enabling it
[info] Enabled Validation Layers:
[info] Found GPU: AMD RADV RAVEN
[info] Found GPU: NVIDIA GeForce GTX 750
[info] Selected GPU: NVIDIA GeForce GTX 750
[info] Dedicated Allocation enabled
[info] Device supports the following requested extensions:
[info]   	VK_KHR_get_memory_requirements2
[info]   	VK_KHR_dedicated_allocation
[info]   	VK_KHR_swapchain
[info]   	VK_KHR_external_semaphore_fd
[info]   	VK_KHR_external_memory_fd
[info]   	VK_KHR_external_memory
[info]   	VK_KHR_external_semaphore
[info] Surface supports the following surface formats:
[info]   	VK_FORMAT_B8G8R8A8_UNORM, VK_COLORSPACE_SRGB_NONLINEAR_KHR
[info]   	VK_FORMAT_B8G8R8A8_SRGB, VK_COLORSPACE_SRGB_NONLINEAR_KHR
[info] Surface supports the following present modes:
[info]   	VK_PRESENT_MODE_FIFO_KHR
[info]   	VK_PRE
SENT_MODE_FIFO_RELAXED_KHR
[info]   	VK_PRESENT_MODE_IMMEDIATE_KHR
[warning] (Swapchain) Image extent (0, 0) not supported. Selecting (1280, 720).
[warning] (Swapchain) Surface format (VK_FORMAT_UNDEFINED, VK_COLORSPACE_SRGB_NONLINEAR_KHR) not supported. Selecting (VK_FORMAT_B8G8R8A8_SRGB, VK_COLORSPACE_SRGB_NONLINEAR_KHR).
[info] (Swapchain) Image usage flags: VK_IMAGE_USAGE_TRANSFER_SRC_BIT VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT 
[warning] (Swapchain) Composite alpha 'VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR' not supported. Selecting 'VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR.
[warning] (Swapchain) Present mode 'VK_PRESENT_MODE_MAILBOX_KHR' not supported. Selecting 'VK_PRESENT_MODE_IMMEDIATE_KHR'.
[info] (Swapchain) Surface format selected: VK_FORMAT_B8G8R8A8_UNORM, VK_COLORSPACE_SRGB_NONLINEAR_KHR
[info] Depth format selected: VK_FORMAT_D32_SFLOAT
[info] Depth format selected: VK_FORMAT_D32_SFLOAT
[info] Depth format selected: VK_FORMAT_D32_SFLOAT
[info] Depth format selected: VK_FORMAT_D32_SFLOAT
--Crash here--
```

maybe because in my case OpenGL memory in `INTEGRATED` GPU, when Vulkan memory in `DISCRETE` GPU, I have no idea if it "expected to work" in this setup, so **maybe this bug is "expected crash"**... idk

if it expected to "not work" when OpenGL memory and Vulkan not on same device then just close this bugreport

**Comment by gpx1000** [comment]
Ahhh that's the issue.  See what's happening is opengl has no method of selecting graphics card when more than one exists.  This it will always select the primary one.  In essence this is the same problem as if you had two separate vulkan queues on two separate GPU cards and address service memory allocated on the other card.
If you wanted to make this work, you must read the open gl memory from the presentation GPU, transfer it to vulkan queue running on that same card, copy it back to the host then copy it to the desecrate queue.
Or a much simpler method would be to use x to change which is your default display card (Nvidia settings handles this quite well). If open gl is on the same card as the vulkan queue then this sample can work.  Otherwise, not so much.

**Comment by danilw** [comment]
> If you wanted to make this work, you must read the open gl memory from the presentation GPU, transfer it to vulkan queue running on that same card, copy it back to the host then copy it to the desecrate queue.

I see, thanks!

> Otherwise, not so much.

So this behavior is expected, then can be closed I think.

**Comment by zefir1990** [comment]
It works for Nvidia with prime-run (forcing external GPU detection):
> prime-run ./build/linux/app/bin/Release/x86_64/vulkan_samples sample open_gl_interop

**Comment by danilw** [comment]
> It works for Nvidia with prime-run (forcing external GPU detection):
> 
> > prime-run ./build/linux/app/bin/Release/x86_64/vulkan_samples sample open_gl_interop

My context was - copy of memory from OpenGL application that **run on different physical GPU** and Vulkan app get this **copy on other different physical GPU**.

You - just launching entire application on single discrete GPU where OpenGL on Nvidia and Vulkan memory on single same Nvidia GPU.
