### ISSUE TITLE
16-bit arithmetic crash Nvidia driver

### ISSUE THREAD

**Issue by danilw** [KhronosGroup/Vulkan-Samples#379]
**Linux Nvidia driver 470.74**

In *16-bit Storage InputOutput* Sample `16bit_storage_input_output` - clicking *Enable 16-bit arithmetic* **does not crash GPU driver**.

**When I click *"Enable 16-bit arithmetic"* in *16-bit arithmetic* Sample Window - OS freeze, it look like Nvidia driver freeze or crash.**

This crash generate Validation errors, but I am not sure if this make sense because it "driver Crash" *(I think)*:
```
VUID-vkCmdDispatch-None-02698(ERROR / SPEC): msgNum: -357592467 - Validation Error: [ VUID-vkCmdDispatch-None-02698 ] Object 0: handle = 0x2ce49a8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x230000000023, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0xeaaf926d | Push-constant buffer: member:1 offset:4 in VK_SHADER_STAGE_COMPUTE_BIT of VkPipelineLayout 0x230000000023[] is not updated. The Vulkan spec states: For each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant value must have been set for the same pipeline bind point, with a VkPipelineLayout that is compatible for push constants, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://vulkan.lunarg.com/doc/view/1.2.170.0/linux/1.2-extensions/vkspec.html#VUID-vkCmdDispatch-None-02698)
    Objects: 2
        [0] 0x2ce49a8, type: 6, name: NULL
        [1] 0x230000000023, type: 17, name: NULL
VUID-vkCmdDispatch-None-02698(ERROR / SPEC): msgNum: -357592467 - Validation Error: [ VUID-vkCmdDispatch-None-02698 ] Object 0: handle = 0x3549948, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x230000000023, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0xeaaf926d | Push-constant buffer: member:1 offset:4 in VK_SHADER_STAGE_COMPUTE_BIT of VkPipelineLayout 0x230000000023[] is not updated. The Vulkan spec states: For each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant value must have been set for the same pipeline bind point, with a VkPipelineLayout that is compatible for push constants, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://vulkan.lunarg.com/doc/view/1.2.170.0/linux/1.2-extensions/vkspec.html#VUID-vkCmdDispatch-None-02698)
    Objects: 2
        [0] 0x3549948, type: 6, name: NULL
        [1] 0x230000000023, type: 17, name: NULL
VUID-vkCmdDispatch-None-02698(ERROR / SPEC): msgNum: -357592467 - Validation Error: [ VUID-vkCmdDispatch-None-02698 ] Object 0: handle = 0x3503288, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x230000000023, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0xeaaf926d | Push-constant buffer: member:1 offset:4 in VK_SHADER_STAGE_COMPUTE_BIT of VkPipelineLayout 0x230000000023[] is not updated. The Vulkan spec states: For each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant value must have been set for the same pipeline bind point, with a VkPipelineLayout that is compatible for push constants, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://vulkan.lunarg.com/doc/view/1.2.170.0/linux/1.2-extensions/vkspec.html#VUID-vkCmdDispatch-None-02698)
    Objects: 2
        [0] 0x3503288, type: 6, name: NULL
        [1] 0x230000000023, type: 17, name: NULL

```

**Comment by gpx1000** [comment]
470.63.01 -- works locally and I'm not seeing the validation errors.  What version of the SDK are you using?

**Comment by danilw** [comment]
Vulkan SDK 1.2.170.0

Nvidia driver *crash/freeze* **only when Nvidia GPU used as main GPU** (selected in UEFI as main).

When Nvidia GPU not main OS does not freeze completely, just 1-2 sec then everything fine, 16-bit arithmetic Sample crash.

`nvidia-smi` report `GPU 00000000:01:00.0: Detected Critical Xid Error`(other Vulkan apps that launched on same GPU also crash at same time).
[What Is an Xid Message](https://docs.nvidia.com/deploy/xid-errors/index.html).
```
Oct 20 18:54:04 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: Shader Program Header 9 Error
Oct 20 18:54:04 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: ESR 0x405840=0x82000200
Oct 20 18:54:04 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=25555, Graphics Exception: ChID 0038, Class 0000b097, Offset 00000f78, Data 00000001
Oct 20 19:12:28 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: Shader Program Header 9 Error
Oct 20 19:12:28 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: ESR 0x405840=0x82000200
Oct 20 19:12:28 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=27768, Graphics Exception: ChID 0040, Class 0000b097, Offset 00000f78, Data 00000001
Oct 20 19:13:43 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: Shader Program Header 9 Error
Oct 20 19:13:43 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: ESR 0x405840=0x82000200
Oct 20 19:13:43 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=27874, Graphics Exception: ChID 0040, Class 0000b097, Offset 00000f78, Data 00000001
Oct 20 19:23:18 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: Shader Program Header 9 Error
Oct 20 19:23:18 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: ESR 0x405840=0x82000200
Oct 20 19:23:18 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=29339, Graphics Exception: ChID 0040, Class 0000b097, Offset 00000f78, Data 00000001
Oct 20 19:26:31 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: Shader Program Header 9 Error
Oct 20 19:26:31 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: ESR 0x405840=0x82000200
Oct 20 19:26:31 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=29559, Graphics Exception: ChID 0040, Class 0000b097, Offset 00000f78, Data 00000001
Oct 20 19:37:54 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: Shader Program Header 9 Error
Oct 20 19:37:54 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=2183, Graphics Exception: ESR 0x405840=0x82000200
Oct 20 19:37:54 home-danil kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=30761, Graphics Exception: ChID 0040, Class 0000b097, Offset 00000f78, Data 00000001
```

> 13 - Graphics Engine Exception - a hardware problem, an NVIDIA software problem, or a user application problem.

Kernel log has errors only when OS freeze, when it does not freeze - no errors, so there errors only from yesterday when I had this freeze because `16-bit arithmetic Sample`.


**Video of this crash**(Nvidia is second GPU, this why OS does not crash): (alternative - [youtube link](https://youtu.be/44HWo_xjQs4))
https://user-images.githubusercontent.com/24825887/138270880-c6c1b5cd-b3a6-4e4e-907b-805dfa654efd.mp4


Only `16-bit arithmetic Sample` freeze Nvidia driver.
*16-bit Storage InputOutput* Sample does not freeze, and does not crash when I click checkbox.

It may be driver problem, idk.

**Comment by gpx1000** [comment]
Thanks for the video.  Sorry for taking so long to reply.  I'm noticing in your video that the GUI is showing the option as "un supported."  Unfortunately, I'm unable to reproduce this.  I have an NVIDIA RTX 2080 and an Intel Graphics 630.  I also am running the 470.74 NVIDIA driver.

When I run the sample I see the following:
[info] Device supports the following requested extensions:
[info]   	VK_KHR_get_memory_requirements2
[info]   	VK_KHR_dedicated_allocation
[info]   	VK_KHR_swapchain
[info]   	VK_KHR_shader_float16_int8
[info]   	VK_KHR_16bit_storage
[info]   	VK_KHR_storage_buffer_storage_class

Looking at the code:
https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/performance/16bit_arithmetic/16bit_arithmetic.cpp#L324
What I'm seeing is that while the Label correctly says it's a no-op if there's missing extensions.  If you do in fact go ahead and turn it on, it will try to run the wrong pipeline if that bool gets flipped to true here:
https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/performance/16bit_arithmetic/16bit_arithmetic.cpp#L237

I'd like to ask if you could verify that in your startup you're missing some of the above required extensions.  I'll create a PR that addresses the fact this isn't a no-op when it should be.

Thanks for the report.

**Comment by danilw** [comment]
> I'd like to ask if you could verify that in your startup you're missing some of the above required extensions. 

```
[info] Logger initialized
[info] Initializing Vulkan sample
[info] VK_KHR_get_physical_device_properties2 is available, enabling it
[info] Enabled Validation Layers:
[info] Found GPU: AMD RADV RAVEN
[info] Found GPU: NVIDIA GeForce GTX 750
[info] Selected GPU: NVIDIA GeForce GTX 750
[info] Dedicated Allocation enabled
[info] Device supports the following requested extensions:
[info]   	VK_KHR_get_memory_requirements2
[info]   	VK_KHR_dedicated_allocation
[info]   	VK_KHR_swapchain
[info]   	VK_KHR_shader_float16_int8
[info]   	VK_KHR_16bit_storage
[info]   	VK_KHR_storage_buffer_storage_class
[info] Surface supports the following surface formats:
[info]   	VK_FORMAT_B8G8R8A8_UNORM, VK_COLORSPACE_SRGB_NONLINEAR_KHR
[info]   	VK_FORMAT_B8G8R8A8_SRGB, VK_COLORSPACE_SRGB_NONLINEAR_KHR
[info] Surface supports the following present modes:
[info]   	VK_PRESENT_MODE_FIFO_KHR
[info]   	VK_PRESENT_MODE_FIFO_RELAXED_KHR
[info]   	VK_PRESENT_MODE_IMMEDIATE_KHR

```

> I'll create a PR that addresses the fact this isn't a no-op when it should be.

~~I just build your linked tree `16bit arithmetic disable unsupported from running ` 
Crash the same, nothing changed.
Maybe this is driver bug.~~

**Comment by gpx1000** [comment]
Wait, so you're seeing a checkbox on the PR branch?  What label does the checkbox have next to it?

**Comment by danilw** [comment]
> Wait, so you're seeing a checkbox on the PR branch? What label does the checkbox have next to it?

Sorry for misinformation, look like in previous message I launched "old build".
In new `16bit arithmetic disable unsupported from running` build **checkbox not appears and I can not click it so there no crash**
![1](https://user-images.githubusercontent.com/24825887/140890903-a8be280a-aea5-419f-97c9-cd8b3e04abf9.png)
.
I noticed if I righclick `16-bit arithmetic` window - application crash with segfault.

This can be closed I think.

**Comment by gpx1000** [comment]
Application crash on right click.  I hit right click a few times and got it to happen here too so I think it's unrelated but something else that needs fixing.  Thanks for that!

If you don't mind I'd prefer if we leave this issue open until the PR gets merged.  It helps us with tracking.

**Comment by gpx1000** [comment]
The crash on right click should be fixed in the same PR, thanks for reporting.
