### ISSUE TITLE
may sample 'open_gl interop' will support Android?

### ISSUE THREAD

**Issue by paul1992li** [KhronosGroup/Vulkan-Samples#383]
For many mobile development scenarios, especially applications that use Opengl，developer should support interop with vulkan. A very common example, A very common example, after the new module is completed using vulkan, use the third-party module of opengl to continue processing.   May 'open_gl interop' sample support Android，thank you very much.

**Comment by SaschaWillems** [comment]
I guess you are referring to OpenGL **ES**? OpenGL (without ES) is not available on Android.

**Comment by paul1992li** [comment]
yes, opengl es. I See that the Android platform is defined in the macro  in _offscreen_context.cpp_ , but it is commented out.
Some extensions are not supported in Android, can I use other extensions such as _VK_ANDROID_external_memory_android_hardware_buffer_ to instead. may demo support android in future or give me some advice to modify
