### ISSUE TITLE
Missing call to command_buffer.begin_render_pass() in VulkanSample::draw_renderpass ?

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#384]
At the end of `VulkanSample::draw_renderpass` in framework/vulkan_sample.cpp, `command_buffer.end_render_pass()` is called, but at the beginning, there's no call to `command_buffer.begin_render_pass()`.

**Comment by SaschaWillems** [comment]
That begin call is actually there, it's just a bit hidden away in `RenderPipeline::draw`, which is called from the `render` function invoked in `draw_renderpass`.

**Comment by asuessenbach** [comment]
Ah ok, just didn't find that. Thanks.
That is, it just seems to be a bit unfortunate, that `begin` and `end` are on different levels of the function call hierarchy, with no obvious connection between them. And that `begin` is guarded by a check against `render_pipeline`, while `end` is not.
