### ISSUE TITLE
Usage examples not working.

### ISSUE THREAD

**Issue by jiaxiongjiao** [KhronosGroup/Vulkan-Samples#386]
On macOS, I tried to run the command line examples from the usage section. However, none of them worked for me. 
For example, 

`vulkan_samples swapchain_images` should really be `./build/mac/app/bin/Release/x86_64/vulkan_samples sample swapchain_images` (The original example missing the option `sample`)

and 

`vulkan_samples sample afbc --benchmark 5000`  would report that 5000 is not expected.

**Comment by SaschaWillems** [comment]
Thanks for noticing. We recently switched argument handling and haven't updated all use-cases in the the readme yet.

**Comment by SaschaWillems** [comment]
The benchmark mode currently doesn't properly work. @TomAtkinsonArm can you take a look?

**Comment by TomAtkinsonArm** [comment]
Ah these will need updating.

Plugins attempted to introduce better CLI practices which in turn left a more explicit CLI and most features CLI options where changed.
