### ISSUE TITLE
Android: APK is not stand-alone (need 3D models upload on the side)

### ISSUE THREAD

**Issue by hevrard** [KhronosGroup/Vulkan-Samples#39]
As documented in https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#3d-models, the 3D models assets are uploaded **by Gradle at compilation time**. This means that running a demo from an APK installed on a device *that was not plugged at compilation time* leads to errors such as:

```
Failed to open file: /storage/emulated/0/Android/data/com.khronos.vulkan_samples/files/shaders/triangle.vert
```

To ease the usage of such demos on test labs, it would be much easier to have a standalone APK which embeds the assets. Is there any non-technical reason to not do this?

**Comment by ghost** [comment]
Hi @hevrard, 

We discussed this as a group and it has a number of technical hurdles and is likely a large amount of work to make this change. For now we have decided to stick with the current system.
