### ISSUE TITLE
`raytracing_extended` sample fails with a scratch buffer alignment problem

### ISSUE THREAD

**Issue by expenses** [KhronosGroup/Vulkan-Samples#393]
Hello. I'm currently unable to run the `raytracing_extended` sample on my AMD Radeon RX 6900 XT and Windows 10.

I did a validation capture and picked up the 3 following errors:

`VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03710(ERROR / SPEC): msgNum: 1677691140 - Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03710 ] Object 0: handle = 0x299797ac020, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x63ff8904 | vkCmdBuildAccelerationStructuresKHR:For each element of pInfos, its scratchData.deviceAddress member must be a multiple of VkPhysicalDeviceAccelerationStructurePropertiesKHR::minAccelerationStructureScratchOffsetAlignment. The Vulkan spec states: For each element of pInfos, its scratchData.deviceAddress member must be a multiple of VkPhysicalDeviceAccelerationStructurePropertiesKHR::minAccelerationStructureScratchOffsetAlignment (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03710)`

`VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03710(ERROR / SPEC): msgNum: 1677691140 - Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03710 ] Object 0: handle = 0x299797ac020, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x63ff8904 | vkCmdBuildAccelerationStructuresKHR:For each element of pInfos, its scratchData.deviceAddress member must be a multiple of VkPhysicalDeviceAccelerationStructurePropertiesKHR::minAccelerationStructureScratchOffsetAlignment. The Vulkan spec states: For each element of pInfos, its scratchData.deviceAddress member must be a multiple of VkPhysicalDeviceAccelerationStructurePropertiesKHR::minAccelerationStructureScratchOffsetAlignment (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03710)`

`VUID-VkShaderModuleCreateInfo-pCode-01091(ERROR / SPEC): msgNum: -1480880714 - Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x299797ac020, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (SampledImageArrayNonUniformIndexing) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)`

I personally believe the scratch buffer alignment problem is what's causing it to fail to load.

I've actually encountered this in my personal project and I've worked around it by [ignoring the `alignment` value returned by `vkGetBufferMemoryRequirements` when allocating the buffer](https://github.com/expenses/ray-tracing-gallery/blob/e54ce7079f3e3fb9c0e5d8b2041b7bf25d27b1e8/src/util_structs.rs#L614-L633) and [using the value from `VkPhysicalDeviceAccelerationStructurePropertiesKHR` instead](https://github.com/expenses/ray-tracing-gallery/blob/e54ce7079f3e3fb9c0e5d8b2041b7bf25d27b1e8/src/util_structs.rs#L438-L461).

**Comment by gpx1000** [comment]
Thanks for the report.

If I can ask is the scratch alignment validation bug happening with the USE_FRAMEWORK_ACCELERATION_STRUCTURE set to true or false.

Also, please see if the PR #390 fixes the validation and issues you are experiencing.  My guess is likely not as I didn't see the alignment validation error come up.  Running locally, I'm also not seeing it in my validation.  I'll try to fix it regardless; just wanted to sanity check that it's still broken for you.

**Comment by expenses** [comment]
Hmm, #390 does seem to fix the problem actually!
