### ISSUE TITLE
choose_present_mode chooses lowest priority when available

### ISSUE THREAD

**Issue by sbash64** [KhronosGroup/Vulkan-Samples#396]
I think the function `choose_present_mode` is selecting the lowest priority of `present_mode_priority_list` if `request_present_mode` is not found.
https://github.com/KhronosGroup/Vulkan-Samples/blob/ae6e4a3712cebde49a29e5996a3bd2f403566890/framework/core/swapchain.cpp#L85-L99

A comment suggests that the first element of `present_mode_priority_list` has highest priority.
https://github.com/KhronosGroup/Vulkan-Samples/blob/ae6e4a3712cebde49a29e5996a3bd2f403566890/framework/core/swapchain.h#L158

Am I understanding this correctly, and is this intended?

**Comment by JoseEmilio-ARM** [comment]
Thank you for pointing this out! 

Agree, looks like we are missing a `break` here? Created https://github.com/KhronosGroup/Vulkan-Samples/pull/409, please let me know what you think
