### ISSUE TITLE
looking for an example about Asynchronous Timewarp

### ISSUE THREAD

**Issue by qingtian1771** [KhronosGroup/Vulkan-Samples#397]
I found there is an example about Asynchronous Timewarp at:
https://github.com/KhronosGroup/Vulkan-Samples-Deprecated/tree/master/samples/apps/atw

Do we have new example about Asynchronous Timewarp or related tech?

Thanks!

**Comment by gpx1000** [comment]
ATW or newer algorithms like ASW are implemented in OpenXR run times.  Monando is an open source OpenXR runtime.  OpenXR also supports Vulkan.  Does this knowledge solve your needs or are you looking for something more explicit?

**Comment by qingtian1771** [comment]
gpx1000,

Thanks a lot! your information is very helpful! 
Could you please give me more explicit information, for example, where can I find the codes about ATW and ASW.

Thanks!

**Comment by gpx1000** [comment]
https://monado.freedesktop.org/  That's an open source OpenXR implementation.  There should be links there that will take you to the github project.

**Comment by gpx1000** [comment]
Hi Wanted to follow up and ensure you have all your questions answered.  I'm going to close this for now, but please reopen it if there's anything still outstanding with this issue with regards to Vulkan Samples.
