### ISSUE TITLE
Compile Failed in Windows after get latest files

### ISSUE THREAD

**Issue by sunxdc15** [KhronosGroup/Vulkan-Samples#402]
* What went wrong:
Execution failed for task ':configureCMakeRelWithDebInfo'.
> C/C++: F:\GitHub\Vulkan-Samples\CMakeLists.txt release|armeabi-v7a : CMake Error at F:\GitHub\Vulkan-Samples\framework\CMakeLists.txt:407 (add_library):
    Cannot find source file:

      F:/GitHub/Vulkan-Samples/third_party/opencl/CL/opencl.h

**Comment by SaschaWillems** [comment]
OpenCL is included as a submodule. So please initialized or update your submodules.

**Comment by sunxdc15** [comment]
thanks, after run "git submodule init" and "git submodule update" from the command line, the error goes away.
