### ISSUE TITLE
fragment_shading_rate_dynamic extension sample: missing texture file "vulkan_logo_full.ktx"

### ISSUE THREAD

**Issue by didito** [KhronosGroup/Vulkan-Samples#405]
`vulkan_logo_full.ktx` referenced in https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/extensions/fragment_shading_rate_dynamic/fragment_shading_rate_dynamic.cpp#L625

I guess needs a submodule update once this PR gets merged: https://github.com/KhronosGroup/Vulkan-Samples-Assets/pull/14

**Comment by Valakor** [comment]
The new multi_draw_indirect sample also is missing assets - those assets have been submitted to the Vulkan-Samples-Assets repo but the assets submodule in this repo has not been updated to reference a newer commit containing the new assets.

**Comment by Valakor** [comment]
Unfortunately I don't believe #407 actually updated the submodule to include all the relevant new assets (I'm still missing vulkan_logo_full.ktx and the entire assets/scenes/vokselia directory.
