### ISSUE TITLE
Caching should check for the current version of the project

### ISSUE THREAD

**Issue by ZandroFargnoli** [KhronosGroup/Vulkan-Samples#41]
> Wondering if this will become a common problem when infrastructure changes are made, and if a check is needed to ensure the cache matches the current version of the APK?

Indeed. I agree that some version checking is probably needed.

_Originally posted by @gary-sweet in https://github.com/KhronosGroup/Vulkan-Samples/pull/24#issuecomment-572612384_

**Comment by gary-sweet** [comment]
This isn't just Android related. I've had to delete the cache files again today as it started crashing again.

**Comment by ghost** [comment]
@ZandroFargnoli - Did this get resolved with #24?

**Comment by SaschaWillems** [comment]
Closing this for now. I've had this problem too in the past, but haven't seen anything in this regards in the last few years.
