### ISSUE TITLE
android build/install instruction can be improved by talking explicitly about copying asset files

### ISSUE THREAD

**Issue by spacejumpunreal** [KhronosGroup/Vulkan-Samples#414]
There is an implicit process during gradle assembleRelease, during which the com.khronos.vulkan_samples is created on android device and assets/output/shaders directories are created. I got no problem running the sample following the build instructions or lauching from Android Studio, but when I sent the apk to other people for testing they got crash running every sample, and it took me quite a while to figure out what is wrong since:
1. the crash site is quite misleading(complaining about having no privileage to write to logs directory, which is unfortunately identical to issue #369)
2. when trying to debug the crash using Android Studio, the launch process will do the gradle build process and the missing files will be copied and the crash just disappears

So I think to it might be better to mention this implicit resource copy process in the build instructions to prevent such caveat from bugging other people.

**Comment by TomAtkinsonArm** [comment]
Hey,

Do the instructions here solve the issue? https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#3d-models

If so, I can add a note under the android section along the lines of "If you are experiencing runtime crashes before a sample loads on Android. First make sure assets are on the device, this should be done implicitly but in some situations may not work. [See here for more guidance](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#3d-models)"

**Comment by spacejumpunreal** [comment]
> Hey,
> 
> Do the instructions here solve the issue? https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#3d-models
> 
> If so, I can add a note under the android section along the lines of "If you are experiencing runtime crashes before a sample loads on Android. First make sure assets are on the device, this should be done implicitly but in some situations may not work. [See here for more guidance](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#3d-models)"

adb push --sync will solve the problem, sorry that I didn't read about this section
