### ISSUE TITLE
[Linux] Crash in GlfwWindow::get_dpi_factor when there is no monitor attached

### ISSUE THREAD

**Issue by werman** [KhronosGroup/Vulkan-Samples#415]
I'm running the samples on a board without monitor attached (I use vnc to see the output) thus `glfwGetPrimaryMonitor` returns null. In a default path `glfwGetPrimaryMonitor` only used in `GlfwWindow::get_dpi_factor`; I think that there should be a check for its result and to return `1.0f` if there is no monitor.

Also there is `glfwGetPrimaryMonitor` in `GlfwWindow::GlfwWindow` but I'm not sure how to handle this case.

**Comment by TomAtkinsonArm** [comment]
Hi,

There is definitely some work to be done here such as choosing headless as a fall back window if another window fails to load.

But for now, have you seen the `--headless` flag?

**Comment by werman** [comment]
Yes, `--headless` works but I needed the window. Anyway, I just handled the lack of monitor in `get_dpi_factor` and got what I wanted.

**Comment by marty-johnson59** [comment]
Looks like this is resolved now, so closing.  @werman, please reopen if there's more to do.  Thanks!
