### ISSUE TITLE
multithreading_render_passes draws random geometry to the screen

### ISSUE THREAD

**Issue by staviq** [KhronosGroup/Vulkan-Samples#420]
Linux 5.10.76-gentoo-r1, Nvidia drivers 510.39.01

Samples build from source from 11a0eef ( latest commit when I'm writing this )

In multithreading_render_passes demo, enabling threaded rendering ( selecting Multithreading mode: Primary, or Secondary ) causes random geometry to be drawn on the screen on top of the scene. Disabling threads ( selecting Multithreading mode: None ) makes things go back to normal.

Here you can see it, it's very hard to capture via screenshot, and renderdoc does not seem to be able to capture it at all, there are many more "random" objects visible to the eye flickering very fast:

I moved away from the main scene so you can see the problem against the black background

https://i.imgur.com/z8RRVHo.png

https://i.imgur.com/mUd7cMb.png

Edit: I managed to capture one in renderdoc:

https://i.imgur.com/XvoBiJT.png

**Comment by gary-sweet** [comment]
I'm seeing similar issues with the latest code. I'll try to bisect to find the offending commit, as it used to work.

**Comment by gary-sweet** [comment]
The bisect points at 513c9028576f4fa97b0635e2faa3a76c248ea572 as the change that introduced this issue.
That was done on the PR - https://github.com/KhronosGroup/Vulkan-Samples/pull/406

@PaoloJovon-arm Can you see if you can reproduce this problem and track it down since this was your change? Thanks

**Comment by PaoloJovon-arm** [comment]
I'll have a look whenever I get a chance to!

**Comment by gary-sweet** [comment]
I've actually found the problem, so no need to investigate @PaoloJovon-arm 

I'll push a PR with the fix shortly.

**Comment by gary-sweet** [comment]
@staviq Can you check that PR #424 fixes the problem you are seeing too please?

**Comment by staviq** [comment]
> 

That seems to have fixed it. Thanks!

Just a small unrelated suggestion, you might want to consider upping camera speed on some demos, because it literally takes half a minute to turn around.

**Comment by gary-sweet** [comment]
> Just a small unrelated suggestion, you might want to consider upping camera speed on some demos, because it literally takes half a minute to turn around.

Please raise a new issue if you feel this is important. Thanks.
