### ISSUE TITLE
make: *** No rule to make target 'vulkan_samples'.

### ISSUE THREAD

**Issue by rumplestilzken** [KhronosGroup/Vulkan-Samples#422]
When building i my cmake command cannot find target "vulkan_samples"

`
cmake --build build/linux/ --config Release --target vulkan_samples -- -j4
make: *** No rule to make target 'vulkan_samples'.  Stop.
`

I can see the project in the in my CMakeLists.txt, but it doesn't seem to want to build.

**Comment by TomAtkinsonArm** [comment]
Hey @rumplestilzken, this is the correct command but you may be using it in the wrong directory. 

Please read through the [Linux build section](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#linux) and get back to me with how it goes.

All commands should be executed from the root project directory

**Comment by rumplestilzken** [comment]
@TomAtkinsonArm 

nick@zbook:~/development/external_git/Vulkan-Samples$ cmake --G "Unix Makefiles" -H. -Bbuild/linux -DCMAKE_BUILD_TYPE=Release
CMake Error at third_party/CMakeLists.txt:231 (add_subdirectory):
  The source directory

    /home/nick/development/external_git/Vulkan-Samples/third_party/glslang

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:244 (target_compile_options):
  Cannot specify compile options for target "glslang" which is not built by
  this project.


CMake Error at third_party/CMakeLists.txt:248 (target_compile_options):
  Cannot specify compile options for target "SPIRV" which is not built by
  this project.


CMake Error at third_party/CMakeLists.txt:253 (set_property):
  set_property could not find TARGET glslang.  Perhaps it has not yet been
  created.


CMake Error at third_party/CMakeLists.txt:254 (set_property):
  set_property could not find TARGET OGLCompiler.  Perhaps it has not yet
  been created.


CMake Error at third_party/CMakeLists.txt:255 (set_property):
  set_property could not find TARGET OSDependent.  Perhaps it has not yet
  been created.


CMake Error at third_party/CMakeLists.txt:256 (set_property):
  set_property could not find TARGET SPIRV.  Perhaps it has not yet been
  created.


CMake Error at third_party/CMakeLists.txt:259 (add_subdirectory):
  The source directory

    /home/nick/development/external_git/Vulkan-Samples/third_party/spirv-cross

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:261 (set_property):
  set_property could not find TARGET spirv-cross.  Perhaps it has not yet
  been created.


CMake Error at third_party/CMakeLists.txt:262 (set_property):
  set_property could not find TARGET spirv-cross-core.  Perhaps it has not
  yet been created.


CMake Error at third_party/CMakeLists.txt:263 (set_property):
  set_property could not find TARGET spirv-cross-glsl.  Perhaps it has not
  yet been created.


CMake Error at third_party/CMakeLists.txt:264 (set_property):
  set_property could not find TARGET spirv-cross-cpp.  Perhaps it has not yet
  been created.


CMake Error at third_party/CMakeLists.txt:265 (set_property):
  set_property could not find TARGET spirv-cross-hlsl.  Perhaps it has not
  yet been created.


CMake Error at third_party/CMakeLists.txt:266 (set_property):
  set_property could not find TARGET spirv-cross-msl.  Perhaps it has not yet
  been created.


CMake Error at third_party/CMakeLists.txt:267 (set_property):
  set_property could not find TARGET spirv-cross-reflect.  Perhaps it has not
  yet been created.


CMake Error at third_party/CMakeLists.txt:268 (set_property):
  set_property could not find TARGET spirv-cross-util.  Perhaps it has not
  yet been created.


CMake Error at third_party/CMakeLists.txt:271 (add_subdirectory):
  The source directory

    /home/nick/development/external_git/Vulkan-Samples/third_party/hwcpipe

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:273 (set_property):
  set_property could not find TARGET hwcpipe.  Perhaps it has not yet been
  created.


CMake Error at third_party/CMakeLists.txt:340 (add_subdirectory):
  The source directory

    /home/nick/development/external_git/Vulkan-Samples/third_party/glfw

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:342 (set_property):
  set_property could not find TARGET glfw.  Perhaps it has not yet been
  created.


CMake Error at third_party/CMakeLists.txt:347 (add_subdirectory):
  The source directory

    /home/nick/development/external_git/Vulkan-Samples/third_party/spdlog

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:348 (set_property):
  set_property could not find TARGET spdlog_headers_for_ide.  Perhaps it has
  not yet been created.


CMake Error at third_party/CMakeLists.txt:367 (add_subdirectory):
  The source directory

    /home/nick/development/external_git/Vulkan-Samples/third_party/cli11

  does not contain a CMakeLists.txt file.


-- Unix platform detected
-- Warnings as Errors Enabled
-- Sample `compute_nbody` - BUILD
-- Sample `dynamic_uniform_buffers` - BUILD
-- Sample `hdr` - BUILD
-- Sample `hello_triangle` - BUILD
-- Sample `hlsl_shaders` - BUILD
-- Sample `hpp_dynamic_uniform_buffers` - BUILD
-- Sample `hpp_hello_triangle` - BUILD
-- Sample `hpp_texture_loading` - BUILD
-- Sample `instancing` - BUILD
-- Sample `separate_image_sampler` - BUILD
-- Sample `terrain_tessellation` - BUILD
-- Sample `texture_loading` - BUILD
-- Sample `texture_mipmap_generation` - BUILD
-- Sample `buffer_device_address` - BUILD
-- Sample `conservative_rasterization` - BUILD
-- Sample `debug_utils` - BUILD
-- Sample `descriptor_indexing` - BUILD
-- Sample `dynamic_rendering` - BUILD
-- Sample `fragment_shading_rate` - BUILD
-- Sample `fragment_shading_rate_dynamic` - BUILD
-- Sample `open_gl_interop` - BUILD
-- Sample `push_descriptors` - BUILD
-- Sample `ray_queries` - BUILD
-- Sample `ray_tracing_reflection` - BUILD
-- Sample `raytracing_basic` - BUILD
-- Sample `raytracing_extended` - BUILD
-- Sample `synchronization_2` - BUILD
-- Sample `timeline_semaphore` - BUILD
-- Sample `16bit_arithmetic` - BUILD
-- Sample `16bit_storage_input_output` - BUILD
-- Sample `afbc` - BUILD
-- Sample `async_compute` - BUILD
-- Sample `command_buffer_usage` - BUILD
-- Sample `constant_data` - BUILD
-- Sample `descriptor_management` - BUILD
-- Sample `layout_transitions` - BUILD
-- Sample `msaa` - BUILD
-- Sample `multi_draw_indirect` - BUILD
-- Sample `multithreading_render_passes` - BUILD
-- Sample `pipeline_barriers` - BUILD
-- Sample `pipeline_cache` - BUILD
-- Sample `render_passes` - BUILD
-- Sample `specialization_constants` - BUILD
-- Sample `subpasses` - BUILD
-- Sample `surface_rotation` - BUILD
-- Sample `swapchain_images` - BUILD
-- Sample `texture_compression_basisu` - BUILD
-- Sample `texture_compression_comparison` - BUILD
-- Sample `wait_idle` - BUILD
-- Plugin `batch_mode` - BUILD
-- Plugin `benchmark_mode` - BUILD
-- Plugin `file_logger` - BUILD
-- Plugin `force_close` - BUILD
-- Plugin `fps_logger` - BUILD
-- Plugin `screenshot` - BUILD
-- Plugin `start_sample` - BUILD
-- Plugin `stop_after` - BUILD
-- Plugin `window_options` - BUILD
-- Configuring incomplete, errors occurred!
See also "/home/nick/development/external_git/Vulkan-Samples/build/linux/CMakeFiles/CMakeOutput.log".
nick@zbook:~/development/external_git/Vulkan-Samples$ cmake --build build/linux --config Release --target vulkan_samples -- -j4
make: *** No rule to make target 'vulkan_samples'.  Stop.

**Comment by SaschaWillems** [comment]
Just a guess, but did you init the submodules? Most of the messages refer to third party code, which is included via git submodules.

**Comment by marty-johnson59** [comment]
Hi @rumplestilzken, I'm closing this as it seems like these suggestions should fix your problem, but if I'm wrong, by all means, please re-open and add any further details needed to help address.  Thanks!
