### ISSUE TITLE
Is there a valid open_gl_interop sample for android?

### ISSUE THREAD

**Issue by LSYGFX** [KhronosGroup/Vulkan-Samples#423]
OpenGL interoperability is valid in Windows with GL extensions and Vulkan extensions. Is there a valid open_gl_interop sample for android? The current open_gl_interop uses GL_EXT_semaphore_win32 and I have no idea that whether GL_EXT_semaphore_fd  is valid for android.

In [GPUInfo](https://opengles.gpuinfo.org/listreports.php?extension=GL_EXT_semaphore_fd), GL_EXT_semaphore_fd  is only 0.36% coverage and all supported devices is desktop-like device.

**Comment by TomAtkinsonArm** [comment]
> Hey @LSYGFX, this is the correct command but you may be using it in the wrong directory. 
> 
> Please read through the [Linux build section](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/docs/build.md#linux) and get back to me with how it goes.
> 
> All commands should be executed from the root project directory

Oops, sorry this was a mistake and was meant for another issue.

Ill get back to you on this subject later. I have asked around for some more ideas on OpenGL interop android support

**Comment by TomAtkinsonArm** [comment]
Hey @LSYGFX,

@PavelRudko-ARM, the creator of the [Vulkan-OpenCL](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/samples/extensions/open_cl_interop) Sample got back to me with his outlook of the situation.

Essentially, the state of GLES and Vulkan interoperability is lacking device support across the board. As you have stated, `GL_EXT_semaphore_fd` is available on <1% of devices. While `GL_EXT_memory_object_fd` is present on <13% of devices. Both are required to perform interop.

This lack of support means that OpenGL interop on Android is not feasible at this time.

**Comment by marty-johnson59** [comment]
Closing as it looks like there's nothing further to do on this one.  @LSYGFX, please re-open if you have further questions or thoughts on this topic.  Thanks.
