### ISSUE TITLE
FI: Scene Graph

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#435]
### What is the Problem?

The Scene Graph is a Tree containing positional Nodes which can have 1 or more components attached to them. The node hierarchy suffers from following the glTF structure to the letter. The issue with this is that not all models are made equal. Accounting for all possible combinations of glTF resources can make code less readable which is not great for an educational project.

### What is the proposed Solution?

Remove sub-meshes - Our implementation of sub-meshes cause havoc with no real benefit
Allow for Scene Optimization Passes - This would be similar to a compile pass where you traverse the tree and can cull or optimize nodes as you see fit.
Allow for custom component backing stores - One size fits all is never a great solution. We should be able to replace how scenes save components
Scene Graph -> Scene View - Currently it is hard to merge multiple models into the same scene due to its ownership of resources and its assumption that only one model will be loaded.

### Examples

TBC

### Issues

- Adjusting the scene may have repercussions on all samples

**Comment by SaschaWillems** [comment]
Closing this for now. I don't think we're going to implement this.
