### ISSUE TITLE
FI: Move CLI Parsing Framework into a Separate Library

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#439]
### What is the Problem?

Not so much a problem at the moment but if the platform class is removed with #438 then the CLI Parsing should be moved to event handlers which take in reference to all resources they modify. At the moment the platform triages all.

### What is the proposed Solution?

Port Plugins to the new framework paradigm

### Examples

```cpp
in main(){
  EventBus bus;
  
  PluginSet plugins;
  plugins.add(SomePluginWhichChangesTheWindow(window));
  plugins.add(SomePluginWhichControlsLogging());
  
  bus.import(plugins.handlers());
}
```

### Issues

- Plugins is in a good state to port but it would mean that handling applications on desktop would need to change

**Comment by SaschaWillems** [comment]
With the mentioned #438 having been closed some time ago, do we still need/want this?

**Comment by SaschaWillems** [comment]
Closing this for now. I don't think we're going to implement this.
