### ISSUE TITLE
Having a problem with HOW to START learning these best-practice samples. 

### ISSUE THREAD

**Issue by wednesday818** [KhronosGroup/Vulkan-Samples#44]
I've built the code, and it works fine. 

However, there is not much tutorial about how to study those samples code. For example, should I start with Hello_Triangle? What is the key API I should be attention to while I reading the code? And which chapter should I study next? 

The Tutorial Chapter currently in the README is more about background knowledge of Vulkan. Which is great!! Just hope you could add the other material which would let us know how to start with these samples and explain more about the Vulkan API themselves through the samples.

Thank you.

**Comment by sfricke-samsung** [comment]
Hey @wednesday818 thanks for bringing up the issue.

Vulkan is a large ecosystem and the Vulkan Samples aim to help those from beginners to even more knowledge Vulkan developers.

I would suggest if you are really new to Vulkan to start with a quick glance at the [Vulkan Guides](https://github.com/KhronosGroup/Vulkan-Guide) we have as that will explain the more non-code information.

As for "how to study" and "where to start", I hate to say its the cliche "it depends", but it kinda does here. If you are brand new to graphics in general, Vulkan Samples will not spend time teaching you about concepts such as "What a vertex shader is", this level of knowledge is assumed (if it isn't explicitly stated on the main readme, I should add that then). These samples are for showing usages of Vulkan. One might try writing their own practice example of these, some might be happier just changing a few lines and see what happens, really depends on the person

The Hello_Triangle is the "Hello World" for most graphic related things, so I would personally suggest looking there first to get a start on what a Vulkan sample looks like.

Last thing I will state, is another big goal of the Vulkan Samples is we wanted a way to allow a developer to attempt playing around with Vulkan for any supported OS without having to worry about how to get everything to build at first.

Hope this helps and happy to answer any further questions!

**Comment by wednesday818** [comment]
Thank you for taking time to respond this issue. You explained clearly the purpose these samples. :) 

I have read [https://github.com/KhronosGroup/Vulkan-Guide](https://github.com/KhronosGroup/Vulkan-Guide) and also finished step by step of [https://vulkan-tutorial.com/](https://vulkan-tutorial.com/) this tutorial while ago. Just wondering what is next?

I will try to dig more into these samples and as you suggested maybe change a few lines to get more familiar with Vulkan. 

Thank you again.

**Comment by sfricke-samsung** [comment]
Glad to hear! Another suggestion is it is much easier learning Vulkan if you have a goal of what to create as Vulkan is at the end of the day a tool with many possible ways to do the same task.

If you are starting out, maybe start with trying to create a 3D cube that changes color every second and every other second a new cube appears... something like this as a goal makes it easier to learn as you have something to actually try and apply these samples code too. Best of luck!

**Comment by wednesday818** [comment]
This is a very useful advice. I'll definitely do it. Thank you :)
