### ISSUE TITLE
Possible bug in Ray Queries shader

### ISSUE THREAD

**Issue by JoseEmilio-ARM** [KhronosGroup/Vulkan-Samples#452]
If an intersection was found, then the returned value would be the `committed` intersection's value, as opposed to the `candidate` intersection. Should

https://github.com/KhronosGroup/Vulkan-Samples/blob/4e905dd5c2c9b4e260bbffc659156a46b4066a5b/shaders/ray_queries/ray_shadow.frag#L69

be replaced with 

`dist = rayQueryGetIntersectionTEXT(query, true);`

?

**Comment by gpx1000** [comment]
hmm...  I think you may be right about that.  Thanks for noticing, I'll give it a test and a quick PR.
