### ISSUE TITLE
Bump C++ Version to C++17

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#454]
It seems that most compilers support most of C++17 features including Android. There are lots of benefits of moving to C++17 beyond just language features. We can replace parts of the project with better external libraries.

For instance, one pain point has been the scene graph. We can replace this with just the spatial tree (transform, AABB, parent -> n child). The component store can be backed by EnTT which provides efficient views over components in a given registry and is much more robust than our own component store implementation. EnTT would also allow for samples to define their own components to attach to the spatial tree which may help simplify samples for those reading the source code, especially if these samples require some bespoke behavior which is not in the framework.

This is one example, I'm sure others can think of many more improvements where C++17 can help improve the project.

The decision boils down to the implications of bumping C++ versions. What platforms or devices are effected by the change? Which users may not be able to compile the project? There are definitely many more questions to answer here.

It would be great to get everyone's opinion on this

**Comment by marty-johnson59** [comment]
This will be part of the framework changes coming shortly
