### ISSUE TITLE
Sample fragment_shading_rate_dynamic has additional render happening over UI

### ISSUE THREAD

**Issue by steven-jackson** [KhronosGroup/Vulkan-Samples#461]
![UI-covered](https://user-images.githubusercontent.com/63823368/170387247-c720617d-a230-4235-b379-112748dea54d.png)

**Comment by SaschaWillems** [comment]
Can you please add some details on your setup? What operating system, what GPU and what driver version are you running on?

**Comment by marty-johnson59** [comment]
Closing for now as there seems to be no action happening.  Please re-open if there are more details we can use to diagnose.  Thanks!
