### ISSUE TITLE
FI: Use std::filesystem

### ISSUE THREAD

**Issue by gpx1000** [KhronosGroup/Vulkan-Samples#467]
#462 is a great implementation that depends upon platform specific code for filesystem classes (i.e. windowsFileSystem, unixFileSystem class etc).  I would suggest that we can switch to using std::filesystem to provide a common class that takes away the need for platform dependent code.

**Comment by TomAtkinsonArm** [comment]
I like the idea of doing this. The main thing id want to keep is a standard way of defining **virtual paths** in the project. I guess now we are using c++17 we might be able to use https://en.cppreference.com/w/cpp/filesystem/path

I dont know enough information about this to implement it.

How hard would this be with the current #462? And can #462 merge without this change and the C++17 Filesystem be added as a separate PR?

**Comment by gpx1000** [comment]
I think it's fair to do it as a separate PR.  It feels like it's a different task and it depends upon C++17 to get fully merged first so why add an extra hurdle to #462?
