### ISSUE TITLE
Use VK_EXT_debug_utils instead of VK_EXT_debug_report

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#47]
The current framework still uses the old VK_EXT_debug_report extension and functionality for validation layer output. We should instead use the newer VK_EXT_debug_utils as described per [this document from LunarG](https://www.lunarg.com/wp-content/uploads/2018/05/Vulkan-Debug-Utils_05_18_v1.pdf).

**Comment by Andreyogld3d** [comment]
VK_EXT_debug_utils doesn't support for Vulkan 1.0 for old Android Devices, so I think we need to support both extensions.

**Comment by SaschaWillems** [comment]
See PR #56 

The new extension will only be used if it's supported, so on older devices, the old VK_EXT_debug_report extension will be used instead.
