### ISSUE TITLE
Add cross-vendor Vulkan/OpenCL interop sample

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#474]
We already have a Vulkan/OpenCL interop sample, but that's vendor-specific to ARM and only works on Windows. With the recently released OpenCL cross-vendor extensions `cl_khr_external_memory` and `cl_khr_external_semaphore` it's now possible to do vendor-neutral Vulkan/OpenCL interop. Having a sample that makes use of it would be a great fit for our repo.

**Comment by blapalp** [comment]
Hi, you set 

`cl_img_desc.image_slice_pitch = cl_img_desc.image_row_pitch * cl_img_desc.image_height;`

with image_row_pitch not set (0), which implies optimal tiling in OpenCl, far as I know.
So it seems the image tiling both in Vulkan and OpenCL are the same, but not within spec.
I didn't have time to go through the whole conversation:
[https://github.com/KhronosGroup/OpenCL-Docs/issues/861](https://github.com/KhronosGroup/OpenCL-Docs/issues/861)

**Comment by SaschaWillems** [comment]
Can you elaborate? I do all of this in my spare time, and that conversation you linked look like it's a lot to read and follow. Is this a problem with the sample? If so, how does it need to be addressed?

**Comment by blapalp** [comment]
Why do you set image_slice_pitch, which is used for 2d image arrays? 
I'm not an expert either, but I gathered that the image tiling/swizzling format has to be the same between the 2 APIs.
If you set the image pitch to 0, the only meaningful assumption is that it is an optimal (nonlinear) format.
Conversely, if the image has a pitch specified, it has to be linear.
In the sample, the image is allocated as VK_IMAGE_TILING_OPTIMAL. OpenCl also, with image_row_pitch being 0, assumes optimal tiling. My assumption is that it is not specified that OpenCL and Vulkan use the same image tiling, as 'optimal tiling' just subsumes all optimal implementation tilings. With the sample working, they're obviously the same, but this might be coincidence (or do OpenCL/Vulkan implementations from the same vendor always use the same optimal tiling?).

**Comment by blapalp** [comment]
So the issue is unresolved:
https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_issues_2
You could use linear tiling, but that would probably be slower.

**Comment by SaschaWillems** [comment]
That's sad. I don't feel like using linear tiling, esp. as we already have an ARM specific sample that also works just fine with optimal tiling.

**Comment by blapalp** [comment]
I can ask Nvidia/Intel. Maybe they can give any guarantees on their driver combinations.
