### ISSUE TITLE
Question: Will dynamic rendering transition image layout implicitly?

### ISSUE THREAD

**Issue by Inori** [KhronosGroup/Vulkan-Samples#494]
Almost all public samples mentions that we need to transition attachment image layout from `COLOR_ATTACHMENT_OPTIMAL` to `PRESENT_SRC_KHR` after rendering and back from `PRESENT_SRC_KHR` to `COLOR_ATTACHMENT_OPTIMAL` before next rendering.
Just like [this](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/extensions/dynamic_rendering/dynamic_rendering.cpp#L371).

But that is for swapchain images which require `PRESENT_SRC_KHR` layout before present.

For more general cases, we don't need the image to be in `PRESENT_SRC_KHR` layout,
e.g. when render to texture then sample from it in next draw, we need the image in `SHADER_READ` layout.
So in such case, do we really need to transition image layout to `COLOR_ATTACHMENT_OPTIMAL` before rendering manually?

I notice that there is a `imageLayout` member in `VkRenderingAttachmentInfo`, just like `layout` member in `VkAttachmentReference` for creating traditional render pass object.
We typically set `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL` for this member, will this translate the attachment image's layout from any other to `COLOR_ATTACHMENT_OPTIMAL` implicitly? And then back to its' original layout after the rendering.

I did some test myself, e.g. transition image layout to `SHADER_READ` before calling `vkCmdBeginRendering`, the validation layer doesn't show any warnings or errors, but I'm still not sure and can't find any public explanations.

And if my guess is true, we can transition the swapchain images' layout to `PRESENT_SRC_KHR` right after the swapchain
was created, such that we don't need to do transition every time a dynamic rendering begin and end? 
(I did this and get no errors from validation layer.)

**Comment by SaschaWillems** [comment]
No, the dynamic rendering extension does not do any implicit layout transitions (like render passes do). If you use dynamic rendering, you have to manually transition all your image layouts.

**Comment by Inori** [comment]
OK, thanks for your time.
