### ISSUE TITLE
GLFW couldn't be initialized 

### ISSUE THREAD

**Issue by flo-th** [KhronosGroup/Vulkan-Samples#504]
Hi all,

I am trying to launch vulkan samples on linux device without connected monitor, but i am encountering the error "GLFW couldn't be initialized".
How could i pass these errors, considering that i just want to check if a am able to create a vulkan device, without rendering checking (i means with a check of connected monitor) ?

Thanks.

**Comment by gpx1000** [comment]
You can try the headless build if that services your needs?

**Comment by marty-johnson59** [comment]
Hi @flo-th, are we good here, or is there more to do before closing?  Thanks!
