### ISSUE TITLE
Samples Exception Class or Macros

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#507]
We should decide on an exception type which makes sense for all platforms.

I think __FILE__ out of box provides paths that are way to long and dirty the log. In the main branch we use ROOT_FILE_PATH to shorten the length, but this does not behave well on all platforms see #173

Any design ideas for fixing this?

**Comment by tomadamatkinson** [comment]
Exceptions was chosen
