### ISSUE TITLE
Base example requires assests from khronos fork, not khronos maintained repo

### ISSUE THREAD

**Issue by andrewschueler** [KhronosGroup/Vulkan-Samples#509]
I downloaded the repository using this command:
```
git clone --recurse-submodules https://github.com/KhronosGroup/Vulkan-Samples.git
cd Vulkan-Samples
```
I then ran the Linux specific compilation instructions for the examples verbatim (though I can change the number of threads accessible to Make no problem).
I then ran the samples with this command:
```
Vulkan-Samples$ ./build/linux/app/bin/Release/x86_64/vulkan_samples batch
```
I then ran into an issue where the `Buggy.gltf` asset was missing. I was able to figure out where the file was because it is actually located on a fork of the Khronos maintained assets repository.
These are the commands I used to fix the issue:
```
pushd Vulkan-Samples/assets/scenes
git remote add complete_origin https://github.com/SaschaWillems/Vulkan-Samples-Assets.git
git pull complete_origin 
git pull complete_origin conditional_rendering
git checkout conditional_rendering
```
This is not a sustainable fix in the long term. Can you guys add in this asset to the Khronos repository?
Thanks
Andrew

**Comment by andrewschueler** [comment]
I found the model through this PR.
https://github.com/KhronosGroup/Vulkan-Samples-Assets/pull/17/commits/995f0dee77a104200da54368f99962508074632e
I don't think it matters, but I am running Ubuntu 22.04 running Cuda 11.7 and Graphics Driver 515.43.04.
vulkaninfo
```
vulkaninfo  | head
WARNING: [Loader Message] Code 0 : loader_icd_scan: Can not find 'ICD' object in ICD JSON file /usr/share/vulkan/icd.d/nvidia_layers.json.  Skipping ICD JSON
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.216


Instance Extensions: count = 20
===============================
	VK_EXT_acquire_drm_display             : extension revision 1
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
```

**Comment by gpx1000** [comment]
Looks like we didn't take the PR in assets before taking the PR here.

@marty-johnson59 Think we can go ahead and merge the https://github.com/KhronosGroup/Vulkan-Samples-Assets/pull/17

**Comment by marty-johnson59** [comment]
Done, thx.

**Comment by SaschaWillems** [comment]
@marty-johnson59: Can you also merge https://github.com/KhronosGroup/Vulkan-Samples/pull/511? This needs to be merged to update the reference to the asset submodule.

**Comment by marty-johnson59** [comment]
Done

**Comment by andrewschueler** [comment]
It appears that the resource is now available in given the repository changes. I think this ticket is done now.
