### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by jcortell68** [KhronosGroup/Vulkan-Samples#523]
The readme incorrectly has the option "-es" in the Android cmdline, for  launching the app to invoke a specific sample.

It should be either -e or --es. 
-es does not work. The app gets an extras with a key of "s", which will not accomplish anything useful :-)

**Comment by jcortell68** [comment]
Oh...and it's more than that problem. The second argument needs to have two set of quotes if you're going to use --es (or -e) with the key being "cmd". Here's the full cmdline that will work
`adb shell am start-activity -n com.khronos.vulkan_samples/com.khronos.vulkan_samples.SampleLauncherActivity --es cmd "'sample swapchain_images'"
`

Alternatively, you could do 
`adb shell am start-activity -n com.khronos.vulkan_samples/com.khronos.vulkan_samples.SampleLauncherActivity --esa cmd sample,swapchain_images
`

But honestly, both of these are unnecessarily complicated. The most concise way of doing it is
`adb shell am start-activity -n com.khronos.vulkan_samples/com.khronos.vulkan_samples.SampleLauncherActivity -e sample swapchain_images`

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. We'll change the readme accordingly.
