### ISSUE TITLE
Crash with API samples on minimizing the window

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#535]
All but two API samples (hello_triangle and hpp_hello_triangle) are crashing on minimizing the window.

**Comment by gpx1000** [comment]
Hi @asuessenbach, I just tested this bug locally and didn't get a crash.  Which OS are you on and which sample is giving a crash?  I'm testing in Ubuntu so am guessing this bug happens in windows?  I tested the instancing sample will test a few others.

**Comment by asuessenbach** [comment]
As said, I get the crash with all but two samples. And you're guessing right, it's on Win10.
First, the validation layer fires on `vkCreateSwapchainKHR` in swapchain.cpp, line 419:
`Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01689 ] Object 0: handle = 0x17332c7e680, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x13140d69 | vkCreateSwapchainKHR(): pCreateInfo->imageExtent = (0, 0) which is illegal. The Vulkan spec states: imageExtent members width and height must both be non-zero (https://vulkan.lunarg.com/doc/view/1.3.231.1/windows/1.3-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01689)`

Then it throws a `runtime_error` in `find_image_type` (core/image.cpp).

**Comment by SaschaWillems** [comment]
I can reproduce this. To avoid this in my samples, I don't resize or update if the window is minimized. I think we need to add that to our framework too.
