### ISSUE TITLE
Native code library failed to load.

### ISSUE THREAD

**Issue by Simoncl** [KhronosGroup/Vulkan-Samples#538]
I'm building all from scratch in android studio. Android Studio Dolphin | 2021.3.1 Patch 1

It builds fine but during emulation, I get the Native code library failed to load.

I have C++ Vulkan projects all running fine and this project also builds and runs fine. https://developer.android.com/ndk/guides/graphics/getting-started

Any help would be appricated.

Cheers

Simon

**Comment by orientate** [comment]
Same mistake here, failed to load library cause samples object did not init, and cause the app broken. After analyse the apk, I find there is no lib directory in the apk which include so files.

**Comment by SaschaWillems** [comment]
Are you getting any build errors in Android studio? This sounds like the native build step fails and as such there is no native library generated and therefore missing from the final APK.

**Comment by Simoncl** [comment]
Hi Sascha. No, I do not get any build errors.

**Comment by orientate** [comment]
> Are you getting any build errors in Android studio? This sounds like the native build step fails and as such there is no native library generated and therefore missing from the final APK.

I didn't get any build error too. My building enviroment Lists:
 Android Studio Dolphin 2021.3.1
Android SDK version: 30.0
NDK version: 25.0.8775105
cmake: 3.18.1

**Comment by Simoncl** [comment]
Orientate. Does the app run for you? Or do you get the native code library failed to load error?

**Comment by orientate** [comment]
> Are you getting any build errors in Android studio? This sounds like the native build step fails and as such there is no native library generated and therefore missing from the final APK.

I rebuid my apk without debug mode, the lib directory appears, and the apk structure is like this:
<img width="796" alt="捕获" src="https://user-images.githubusercontent.com/64951800/197091238-032b6195-aef3-4c0a-a491-b08f13cbef24.PNG">
When I run apk which is not builded  in debug mode in my android phone, the message shows parsing package failed. 
When I run apk in debug mode, the lib directory is disappeared and the structue is like this:
<img width="594" alt="捕获1" src="https://user-images.githubusercontent.com/64951800/197092140-426267c6-ba0c-4cb9-a5ec-c392772e5b1e.PNG">
And the code line `System.loadLibrary(native_lib_name);` in debug mode cause the error message: dlopen failed: library "libvulkan_samples.so" not found

**Comment by orientate** [comment]
> Orientate. Does the app run for you? Or do you get the native code library failed to load error?

 I get the same error with you. It seems in debug mode, the lib directory and .so file is not included in apk.

**Comment by orientate** [comment]
Looks like I solve this problem, set your configuration like this, the so file will include in your apk in debug mode:
<img width="751" alt="123" src="https://user-images.githubusercontent.com/64951800/197095721-46478c0a-4d1e-4653-824f-26d0edacb297.PNG">

**Comment by Simoncl** [comment]
I still get the error

**Comment by ggfan** [comment]
May you check your emulated device to be ARM images, not x86 ones(default)? the sample only builds for [ARM ABIs](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/bldsys/cmake/create_gradle_project.cmake#L39) by default.

If it is the case, find your local build tree, in file build/android_gradle/app/build.gradle, just add needed abi to the list:
  //"x86" "x86_64" for x86 ABIs, probably remove the ARM ones if your targets are not ARM to save build time.
` abiFilters.addAll( 'arm64-v8a', 'armeabi-v7a' )`

Just a guess, please confirm and update: we could follow up more for this (it should have some compiler errors, but not totally sure).

**Comment by marty-johnson59** [comment]
If there's no further action here, I'll close.  We can re-open if needed
