### ISSUE TITLE
m-gpu for device group

### ISSUE THREAD

**Issue by funnygyc** [KhronosGroup/Vulkan-Samples#540]
Hi, I want to write a multi-gpu program using device groups but I do not how to use  it.
Are there any samples or guides can help me to learn this extensions ?
thanks!

**Comment by SaschaWillems** [comment]
Multi-GPU has become quite a niche, so there's not that much material available in regards to Vulkan. I don't know of any tutorial or samples that make use of it, but reading up on those extensions may be a good starting point:

- [VK_KHR_device_group](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_device_group.html)
- [VK_KHR_device_group_creation](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_device_group_creation.html)

**Comment by funnygyc** [comment]
thanks a lot. I will try that.

**Comment by marty-johnson59** [comment]
Thanks for the request.  We're currently not planning to do an m-gpu sample (too much on our plate), but this may change in the future.  For now, I'll close this issue - but if there's strong arguments we should hear, please re-open.  Thanks!
