### ISSUE TITLE
Add image format selection to the HDR sample

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#545]
The HDR hast the `VK_FORMAT_R32G32B32A32_SFLOAT` hardcoded. But some implementations do not support blending on that format (see https://github.com/KhronosGroup/Vulkan-Samples/pull/542). The sample needs to implement a proper runtime format selection.

**Comment by gary-sweet** [comment]
Thanks Sascha, I was just about to raise the same issue. I originally thought that it was a wider problem than just the hdr and hpp_hdr samples, but I no longer think that's true. Everything else uses attachment formats where blending support is mandatory. It's just the 32-bit-component formats where blending isn't mandatory, so it should only be these two examples.
