### ISSUE TITLE
glTF Model Animations Sample

### ISSUE THREAD

**Issue by RisaStenr** [KhronosGroup/Vulkan-Samples#55]
Sascha said you were accepting feature requests and so I was wondering if there were any plans for a glTF skeletal animation project performance project showing best practices for implementing them?

**Comment by ghost** [comment]
Call 02/03 - In consideration, more of a tutorial than a sample and probably out of scope for this repo. Would require framework changes.

**Comment by RisaStenr** [comment]
OK well ill close this then.
