### ISSUE TITLE
Replace usage of std::vector::at() with std::vector::operator[], where appropriate

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#577]
There are lots of places in this repository, where std::vector::at() is used, but std::vector::operator[] would be a better fit, as it has already been verified that the specified location exists (inside a loop, or a previous explicit check).
std::vector::at() does bounds checking, even in release builds. For the samples here, that probably doesn't matter at all. But code from this repository is probably used "as is" in other peoples code, where that redundant check might matter.
Using std::vector::at() in most cases here is kind of "premature pessimization".

**Comment by marty-johnson59** [comment]
@tomadamatkinson can you take a look at this one too?  We are worried about making FW changes w/o your involvement.  Thx
