### ISSUE TITLE
Replace VK_QUEUE_GRAPHICS_BIT with VK_QUEUE_TRANSFER_BIT in framework/gltf_loader.cpp

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#578]
The transfer queue is probably the better choice here.

**Comment by marty-johnson59** [comment]
@tomadamatkinson - last one (I think)

**Comment by marty-johnson59** [comment]
Closing as the benefit here doesn't warrant the effort ATM
