### ISSUE TITLE
Replace vbk::BufferPool by using VMA

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#581]
`vkb::BufferPool` is used by `vkb::RenderFrame` only.
That could be replaced by using VMA, which is used for buffer allocation in other parts of the framework as well.

**Comment by TomAtkinsonArm** [comment]
Under the hood, VMA is doing something similar to `vkb::BufferPool`. I wonder how difficult this would be

**Comment by marty-johnson59** [comment]
@tomadamatkinson, can you open a PR for this fix?  Thx
