### ISSUE TITLE
An app was not requested, can not continue

### ISSUE THREAD

**Issue by KaxelOleg** [KhronosGroup/Vulkan-Samples#582]
Hello, I have a problem with the launch vulkan_samples.exe I have Windows 11 and when I went through all the steps to build the solution, I decided to perform the third step and run the program. As a result, it immediately closed at startup. Then I tried to create an assembly in Visual Studio itself with the Debug version, and the error was already more informative there. The following wrote to me: [info] Logger initialized
[info] An app was not requested, cannot continue
Does anyone know what the problem is here? I will be very grateful if you help me.

**Comment by SaschaWillems** [comment]
You need to specify the sample you actually want to run. See https://github.com/KhronosGroup/Vulkan-Samples#usage.

**Comment by KaxelOleg** [comment]
> You need to specify the sample you actually want to run. See https://github.com/KhronosGroup/Vulkan-Samples#usage.

I probably look silly, but I can't figure out where I should run these commands, the ones in the Usage section. I tried to run via Dev Com Prompt VS from the main directory of the project and the vulkan_samples command is nowhere to be found, can you please tell me where I made a mistake?

**Comment by SaschaWillems** [comment]
Easiest way is to supply the command line arguments from the IDE.

In VS you can do that in the project settings:

![image](https://user-images.githubusercontent.com/10283127/207323457-c67d7a85-342c-4808-b02f-6142f008c073.png)

Another more flexible option is using an Addon like https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments

**Comment by KaxelOleg** [comment]
> Easiest way is to supply the command line arguments from the IDE.
> 
> In VS you can do that in the project settings:
> 
> ![image](https://user-images.githubusercontent.com/10283127/207323457-c67d7a85-342c-4808-b02f-6142f008c073.png)
> 
> Another more flexible option is using an Addon like https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments

Thank You!
