### ISSUE TITLE
The name of the function vkb::is_depth_stencil_format is misleading

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#584]
I would expect to get `true`, if the format has both depth and stencil components. But it also gets you `true`, if it has just the depth component.
Should be renamed to `is_depth_format`?

**Comment by TomAtkinsonArm** [comment]
Completely agree. We should have `is_depth_stencil_format` and `is_depth_format`

**Comment by marty-johnson59** [comment]
@tomadamatkinson , are you willing to open a PR For this?

**Comment by SaschaWillems** [comment]
Been doing some framework changes, so I'll take a stab at this.
