### ISSUE TITLE
Please rename default branch from 'master' to 'main' per Khronos policy

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Samples#595]
To repository owners: please rename the default branch of this repository from 'master' to 'main', using the [Github renaming tool](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch). This request is per policy set by the Khronos Promoters in May 2021, to follow Github community practice for respectful naming.

The Github renaming tool sets up URL redirections and retargets outstanding pull requests, so the impact on repository users is minimal. The most visible issue is that people with local repo clones will probably want to rename their clone's 'master' branch, following the popup instructions that will be seen when browsing the github repository after the change; or just delete 'master' and pull the new 'main', if it's purely a tracker with no local content.

You may wish to coordinate with @outofcontrol if you are doing auto-updates from this repository to another location, whether via push/pull mirroring or other mechanisms. The redirects setup by Github should accommodate most such uses transparently, but it's still good practice.

Based on experience with other KhronosGroup repositories which have undergone this renaming already, this is a reasonable approach:

* Agree on a date for the renaming within the Working Group or other owners of the repository, and document that date here.
  * Date can be adjusted to avoid interaction with major releases in flight.
* Provide notice to repository users outside Khronos, insofar as possible (adding a comment in the repo README with the switchover date is one way).
* Once the renaming is done, edit the new 'main' branch to replace hardwired references to 'master' with (preferably) 'default branch' or 'main'.
* Update the repo README to note the change.

If you have questions or issues about this, please raise them on Khronos internal gitlab 'khronos-general' issue 106 if possible. If not possible, you can @-tag me here.

While we will not force any WG into acting precipitously, this is our agreed policy. Please try to accommodate renaming relatively soon.

Note that this issue is automatically generated, due to the large number of KhronosGroup repositories it's being raised in.

**Comment by tomadamatkinson** [comment]
@marty-johnson59 this is a fairly streamlined process. I don't believe we have any auto-updates set up with other repositories. Maybe @outofcontrol can correct me on this? The only thing we need to change when moving to `main` is a few tiny tweaks in the CI AFAIK

**Comment by allcreatures** [comment]
For Vulkan-Samples, no auto-updates that I am aware of. If there are any, the breakage will be apparently quite quickly and easily adjusted for.

**Comment by tomadamatkinson** [comment]
Cool! We should be able to switch to main at any point and I will merge a CI patch. We can add a note to users in the readme that we have recently changed. However, it looks like the rename tool will also prompt the user that we have made the change through git

**Comment by oddhack** [comment]
> Cool! We should be able to switch to main at any point and I will merge a CI patch. We can add a note to users in the readme that we have recently changed. However, it looks like the rename tool will also prompt the user that we have made the change through git

Yes, it puts up a popup with transition instructions. People who don't go to the website and just work via their local clones might be taken unaware, though.

**Comment by marty-johnson59** [comment]
BTW, I see we also have the Vulkan-Samples-Assets repo that's currently set to 'master'.  @tomadamatkinson, can we change that one too?

**Comment by SaschaWillems** [comment]
Changing that on the assets repo should be easy. After the name change we need to point the submodule in this repo to main. I can do a PR for that.

**Comment by tomadamatkinson** [comment]
Changed Samples see #601. I will transition assets later in the week if all goes well and there are no issues :)

**Comment by SaschaWillems** [comment]
@tomadamatkinson : Can we do the name change for the assets repo? If you're short in time I could take a look at it.

**Comment by tomadamatkinson** [comment]
Renamed. Do you want to give a clean build a test? Should work but if not we will need to update the submodule

**Comment by SaschaWillems** [comment]
Doesn't work for me for both an existing repo as well as a new clean check out.

When checking out the repo from scratch, the assets sub module is stuck on an older revision that lacks e.g. recent assets:

![image](https://user-images.githubusercontent.com/10283127/233676864-59a5753f-ab04-4b16-bc99-60fcca2ab0fd.png)

Similar for an existing copy of the repo where I haven't been able to get the assets submodule to update to the latest comit.

**Comment by tomadamatkinson** [comment]
Thanks for checking Sascha!

So we now know that although GitHub is clever with naming. This doesn't quite work for submodules.

I will revert the rename and checkout main. Then update the submodule accordingly.

We can then eventually remove master after we are happy it has been a long enough time where people will be using the latest changes in Vulkan Samples main

**Comment by tomadamatkinson** [comment]
Just checked out a clean build and the assets pulled correctly. They where out of date, but it looks like the submodule has been pointing at out of date assets for a while.

Bumped the submodule in #676

Fixed by #676
