### ISSUE TITLE
The HelloTriangle example handles VK_FORMAT_UNDEFINED, which is not allowed by the spec

### ISSUE THREAD

**Issue by tuket** [KhronosGroup/Vulkan-Samples#604]
In this example:

https://github.com/KhronosGroup/Vulkan-Samples/blob/7e26046720669d82d19d4525f2bb7308efd4b55b/samples/api/hello_triangle/hello_triangle.cpp#L444

It calls `vkGetPhysicalDeviceSurfaceFormatsKHR` and then checks if the first entry is `VK_FORMAT_UNDEFINED`.

However, according to the [spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceSurfaceFormatsKHR.html) of `vkGetPhysicalDeviceSurfaceFormatsKHR`:

> The number of format pairs supported must be greater than or equal to 1. pSurfaceFormats must
> not contain an entry whose value for format is VK_FORMAT_UNDEFINED.

So that check is not needed.

**Comment by SaschaWillems** [comment]
Thanks for raising this. This is probably a left-over from the very early days of Vulkan, where this wasn't explicitly defined in the spec.
