### ISSUE TITLE
functions get_clear_all_store_swapchain & get_clear_value defined but not used

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Samples#62]
https://github.com/KhronosGroup/Vulkan-Samples/blob/d91d527366bdf6c48dc6f607c7cbc9ad47f84250/samples/performance/render_subpasses/render_subpasses.cpp#L286

A previous refactoring moved several functions to the vk_common module, but their original definitions in render_subpasses.cpp didn't all get cleaned up.

**Comment by ghost** [comment]
Fixed by #63
