### ISSUE TITLE
Colliding paths on case insensitive file system (macOS)

### ISSUE THREAD

**Issue by LostInCompilation** [KhronosGroup/Vulkan-Samples#621]
Cloning the repo with Git on macOS results in the following warning:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'samples/extensions/memory_budget/images/memory_budget_UI_overlay.png'
  'samples/extensions/memory_budget/images/memory_budget_ui_overlay.png'
```

macOS uses a case insensitive file system. Maybe consider renaming the file in question.

**Comment by SaschaWillems** [comment]
Thanks for pointing this it. It's also problematic on Windows when e.g. creating your own branches as git will always register this as a change.
