### ISSUE TITLE
AfterCaseLabel from clang-format 9 is added to .clang-format

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Samples#628]
In 6076d7403e557f8e2f741ad02147b50d133e2d0a, `AfterCaseLabel: true` is added to `.clang-format`. AFAICT, this was introduced in clang-format 9. The documentation still requires source formatting with clang-format 8, which currently fails to read `.clang-format`

**Comment by Karina-Murawko-Wisniewska-Mobica** [comment]
FYI https://github.com/KhronosGroup/Vulkan-Samples/pull/596#issuecomment-1420414424
