### ISSUE TITLE
github pages now fails after feb 28th

### ISSUE THREAD

**Issue by gpx1000** [KhronosGroup/Vulkan-Samples#632]
https://github.blog/changelog/2023-02-21-github-pages-deprecating-symlinks-in-non-actions-builds/

Sadly this caught us.  CLI11 has a symlink.  Creating an issue to ensure I don't forget to create a fix for this.

**Comment by tomadamatkinson** [comment]
@gpx1000 fixed by moving our GitHub Pages workflow to a GitHub Action instead of the inbuilt behavior.
