### ISSUE TITLE
How to set the presentMode property of the swapchain to support exclusive fullscreen?

### ISSUE THREAD

**Issue by yijianshuangdiao** [KhronosGroup/Vulkan-Samples#645]
I saw the branch code for exclusive fullscreen support in the gpx1000 project ([https://github.com/gpx1000/Vulkan-Samples/tree/vk_Full_Screen_Exclusive/samples/extensions/full_ screen_exclusive](https://github.com/gpx1000/Vulkan-Samples/tree/vk_Full_Screen_Exclusive)). Unfortunately, I didn't find an entry to communicate with the author. I have one question, why does the presentMode property of VkSwapchainCreateInfoKHR need to select VK_PRESENT_MODE_FIFO_KHR when creating a fullscreen swapchain, instead of the other 3 modes? I tried to create a swapchain in 3 other modes on my own device, but it failed when I switch to exclusive full screen mode with vkAcquireFullScreenExclusiveModeEXT. Is it convenient to provide information or explanation about this?thanks.

**Comment by gpx1000** [comment]
It doesn't *need* to select VK_PRESeNT_MODE_FIFO.  That's just one mode that's required to exist.  One could select any mode that the surface returns as valid for a full screen exclusive swapchain.

**Comment by yijianshuangdiao** [comment]
@gpx1000  Thank you for your response. I have verified that both VK_PRESENT_MODE_FIFO_KHR and VK_PRESENT_MODE_IMMEDIATE_KHR modes can successfully switch to exclusive fullscreen. However, I have encountered a similar problem when implementing exclusive fullscreen functionality in the [SaschaWillems/Vulkan](https://github.com/SaschaWillems/Vulkan) project.In order to better describe my problem, I forked the project and added the relevant code for exclusive fullscreen at this location: [yijianshuangdiao/SaschaWillems_Vulkan](https://github.com/yijianshuangdiao/SaschaWillems_Vulkan/tree/full_screen_exclusive). In my code, exclusive fullscreen mode can be requested by enabling the windowedfullscreen and fullscreen switches in [base/vulkanexamplebase.h](https://github.com/yijianshuangdiao/SaschaWillems_Vulkan/blob/946222d0aee29db98683417e1866d0f59c7b6ed0/base/vulkanexamplebase.h#L182):
```c++
/** @brief Set to true if windowedfullscreen mode has been requested via command line */
bool windowedfullscreen = true;
/** @brief FullScreen Exclusive */
bool fullscreen = true;
```
I selected VK_PRESENT_MODE_FIFO_KHR to create the swapchain and requested exclusive mode in [base/VulkanSwapChain.cpp](https://github.com/yijianshuangdiao/SaschaWillems_Vulkan/blob/946222d0aee29db98683417e1866d0f59c7b6ed0/base/VulkanSwapChain.cpp#L284):
```C++
VkPresentModeKHR swapchainPresentMode = VK_PRESENT_MODE_FIFO_KHR;
// If v-sync is not requested, try to find a mailbox mode
// It's the lowest latency non-tearing present mode available
if (!vsync && !exclusivefullscreen)
{
   //Match other present modes.
}
```
If I modify the swapchain creation to use the VK_PRESENT_MODE_MAILBOX_KHR mode, using vkAcquireFullScreenExclusiveModeEXT to request exclusive mode returns VK_ERROR_INITIALIZATION_FAILED error. I have also replicated this issue in your branch project. In order to locate the issue, I have done a lot of work, including changing the relevant settings of the swapchain, switching Vulkan versions, and checking the device drivers, but still cannot find the cause of this problem. If you know what is causing this issue, could you please provide a specific explanation? Thank you again.

**Comment by gpx1000** [comment]
Sadly, I'm the wrong person to answer this further as I don't have a windows computer at my home office.  @SaschaWillems or @marty-johnson59 anyway you guys can direct this to the correct person to help figure this out?  I'm happy to help if I can.

**Comment by SaschaWillems** [comment]
@yijianshuangdiao: I haven't taken a deep look at it yet, but this sounds like a vendor specific problem. It's up to the implementation. What GPU and OS are you running this on?

**Comment by yijianshuangdiao** [comment]
@SaschaWillems The GPU I'm using is NVIDIA GeForce RTX 3070, and the operating system is Windows 10 Professional 22H2.

**Comment by SaschaWillems** [comment]
It's probably best to contact NVIDIA then. If they do something that doesn't adhere to the spec it's an implementation issue that should be fixed in their drivers.

**Comment by yijianshuangdiao** [comment]
@SaschaWillems Before contacting NVIDIA, I would like to confirm that the issue is not caused by my non-compliant programming. Can you reproduce the issue on your device as well?

**Comment by SaschaWillems** [comment]
Sorry for the late reply. I'm no longer on Windows 10, so I can't test anything related to exclusive full screen. If the issue still persists, feel free to contact your driver vendor.
