### ISSUE TITLE
Sample Demo for VK_EXT_shader_object

### ISSUE THREAD

**Issue by nikeinikei** [KhronosGroup/Vulkan-Samples#656]
It would be nice to have a full example for the [VK_EXT_shader_object](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_EXT_shader_object.adoc) extension, which removes the need to create VkPipeline objects.
There already are [nvidia beta drivers](https://developer.nvidia.com/vulkan-driver) available which support this extension.

**Comment by camelliafangirl** [comment]
That'd be super usefull to have, +1

**Comment by SaschaWillems** [comment]
Thanks for your suggestion. We'll be doing a sample on this.

**Comment by SaschaWillems** [comment]
See #717

**Comment by SaschaWillems** [comment]
The sample has been merged.
