### ISSUE TITLE
Issues after I upgraded Vulkan SDK (to 1.3.243)

### ISSUE THREAD

**Issue by lang-sec** [KhronosGroup/Vulkan-Samples#661]
Hello,
When I built and ran samples here on Vulkan SDK version 1.3.239, everything was all right

Yesterday, I upgrade Vulkan SDK to 1.3.243 (newest), there are several problems

1. Swapchain size for general size not working
For example, I ran command below
vulkan_sample sample debug_utils --width 3100 --height 1800 --vysnc off
Then, swapchain size is just the default size (not 3100 x 1800)

2. Mouse effect not working probably
If I clicked the screen and drag to rotate the screen, the objects which were shown disappeared

3. For sample fragment_shading_rate
Only black screen is shown

Please help me with this issue
Thank you

**Comment by SaschaWillems** [comment]
I tried with SDK 1.3.243 myself and did not see any of these problems. Is your repo up-to-date? We renamed master to main some time ago. Also make sure that you don't have any faulty implicit layers installed.

**Comment by lang-sec** [comment]
> I tried with SDK 1.3.243 myself and did not see any of these problems. Is your repo up-to-date? We renamed master to main some time ago. Also make sure that you don't have any faulty implicit layers installed.

From the sources built under 1.3.239, I copied some files whose class inherited directly from vkb::Application and which is essentially the same as the sample "ray_tracing_reflection" and whose name is "main_app", done by me.
That "main_app" runs all right after building under 1.3.243

So I will check tomorrow about this again (It is midnight here now)

Thank you and if I find something interesting, I will write down here

**Comment by marty-johnson59** [comment]
Hi @bioorg, is there anything we need to address in the samples, or are we OK to close this now?  Thanks!

**Comment by lang-sec** [comment]
> Hi @bioorg, is there anything we need to address in the samples, or are we OK to close this now? Thanks!

Hello, I will return in a few days. I will check. Thank you

**Comment by lang-sec** [comment]
Hello, sorry for the delay

I just checked again regarding all the errors I informed you of
I just reinstalled the vulkan-sample github with Vulkan API 1.3.243.0 and rebuild everything
Now everything is OK. They ran very well
(I didn't check with API 1.3.246 though)
Thank you for your help and have a nice day!
