### ISSUE TITLE
HPP terrain tessellation sample reports wrong statistics

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#674]
The terrain tessellations sample displays statistics using a pipeline statistics query:

![image](https://user-images.githubusercontent.com/10283127/233646771-6d2e3f94-4cf4-47e5-9283-101c2ff2926f.png)

The HPP version of that sample does the same, but displays wrong values:

![image](https://user-images.githubusercontent.com/10283127/233646850-a337b875-3046-4e46-af61-328511399fe2.png)

When debugging, I can see the correct values in the HPP ones after getting the query pool results, but they seem to get lost between this and the display. I wasn't able to find out why.

Maybe you can take a look at this @asuessenbach?

**Comment by asuessenbach** [comment]
I'm sorry, but I can't repro this issue. The statistics look correct on my end.
Maybe someone else can test this as well?

**Comment by SaschaWillems** [comment]
Thanks for testing this. I can actually also reproduce this on Android with my Pixel 4a. While the non hpp version displays proper statistics, the hpp one always shows the same (probably wrong) values.

**Comment by SaschaWillems** [comment]
As noted in #832 this issue is still present.

It only happens in the hpp version and for two completely different setups:

- My old setup with an RTX 2060 and Windows 10
- My new setup with an RTX 4070 and Windows 11

I expect a sync/timing problem, as it seems to be more visible with hight framertates. On another setup with an integrated Intel GPU where I can't get vsync to disable I always see correct values.

**Comment by asuessenbach** [comment]
As already noted, I can't repro this issue.
If anybody else could check on his setup and report here?

**Comment by SaschaWillems** [comment]
Just to rule out anything related to my PC setup: I can also reproduce this on my Google Pixel 4a. It's actually even a bit different there: The HPP version of the sample always displays the same (wrong) values that never change, no matter where i look, whereas the non-HPP version works fine:

![Screenshot_20231102-184022](https://github.com/KhronosGroup/Vulkan-Samples/assets/10283127/e5a4152b-ee36-494b-b0b4-4a98bd87ffde)
![Screenshot_20231102-183958](https://github.com/KhronosGroup/Vulkan-Samples/assets/10283127/54262e37-0923-4872-90d2-38109d9be4d1)

**Comment by SaschaWillems** [comment]
This is still happening for me, even with the recent change that limits gui updates.
