### ISSUE TITLE
Possible use of numeric_limits<T>::min(), numeric_limits<T>::max()

### ISSUE THREAD

**Issue by r2d2Proton** [KhronosGroup/Vulkan-Samples#695]
Utils.h
`
#include < chrono >
#include < cfloat >
#include < random >

using std::string;

namespace Utils {
extern std::random_device randomDevice;
extern std::mt19937 generator;

std::random_device& GetRandomDevice();

std::mt19937& GetGenerator();

template<typename T>
T GetRandomINT(T lo = std::numeric_limits<T>::min(), T hi = std::numeric_limits<T>::max());

template<typename T>
T GetRandomUINT(T lo = 0, T hi = std::numeric_limits<T>::max());

template<typename T>
T GetRandomReal(T lo = std::numeric_limits<T>::min(), T hi = std::numeric_limits<T>::max());
}
`

And Utils.cpp
`
#include "Utils.h"
#include < codecvt >
#include < locale >

static std::random_device Utils::randomDevice;
static std::mt19937 Utils::generator;

std::random_device& Utils::GetRandomDevice()
{
    return Utils::randomDevice;
}

std::mt19937& Utils::GetGenerator()
{
    return Utils::generator;
}

template<typename T>
T Utils::GetRandomINT(T lo, T hi)
{
    std::uniform_int_distribution<T> dist(lo, hi);
    return dist(Utils::generator);
}

template<typename T>
T Utils::GetRandomUINT(T lo, T hi)
{
    std::uniform_int_distribution<T> dist(lo, hi);
    return dist(Utils::generator);
}

template<typename T>
T Utils::GetRandomReal(T lo, T hi)
{
    std::uniform_real_distribution<T> dist(lo, hi);
    return dist(Utils::generator);
}

const std::chrono::time_zone* Utils::GetTimeZone()
{
    return std::chrono::current_zone();
}

std::chrono::local_time<std::chrono::system_clock::duration> Utils::GetLocalTime()
{
    return Utils::GetTimeZone()->to_local(std::chrono::system_clock::now());
}
`

**Comment by SaschaWillems** [comment]
Can you please add a description? What is this issue about? It only contains a code snippet without an actual question.
