### ISSUE TITLE
Move platform to self contained executable

### ISSUE THREAD

**Issue by tomadamatkinson** [KhronosGroup/Vulkan-Samples#697]
`vkb::Platform` acts as the core runtime of the application. It abstracts both the application lifecycle and platform specific implementations. It is also the center of the samples -> framework -> samples cyclical dependency.

There was some work carried out in the past labelled as `Plugins`. This helped group command line usage into individual Plugins and then reduced the amount of code this effected throughout the application. Plugins failed to remove the cyclical dependency which meant that compile times continued to get worse.

When reviewing the platform and plugins closer, it is almost like these components are not related to the rest of the samples. These components form their own entity, the `vulkan_samples` launcher. If we where able to replace the platform in its entirety using components we would be able to break the cyclical dependency and the compile graph will look more like:

```
components  -> existing framework -> samples -> vulkan_samples launcher
```

This will provide better compile times and allow us to maintain the samples launcher separate to the samples them selves

**Comment by SaschaWillems** [comment]
Do we still need/want this? Compile times have been improved over time by multiple PRs.
