### ISSUE TITLE
Image barrier sync issue in dynamic rendering sample

### ISSUE THREAD

**Issue by billgan1024** [KhronosGroup/Vulkan-Samples#721]
In the dynamic rendering sample, the following image barrier is used to transition the swapchain image:
```
vkb::insert_image_memory_barrier(draw_cmd_buffer,
swapchain_buffers[i].image,
0,
VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
VK_IMAGE_LAYOUT_UNDEFINED,
VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, range);
```

But this causes a write-after-read issue:
			                                 
```
[error] [framework/core/instance.cpp:42] 929810911 - SYNC-HAZARD-WRITE-AFTER-READ: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0x564690db2e50, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x376bc9df | vkQueueSubmit: Hazard WRITE_AFTER_READ for entry 0, VkCommandBuffer 0x564692b7b900[], Recorded access info (recorded_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 7). Access info (prior_usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_ACQUIRE_READ_SYNCVAL, read_barriers: VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT, , batch_tag: 87, vkAcquireNextImageKHR aquire_tag:87: VkSwapchainKHR 0xf56c9b0000000004[], image_index: 0image: VkImage 0xe7f79a0000000005[])
```
			                                 
 From the spec: 	                              
			                                 
![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/17630457/347bedeb-6262-40fb-bda7-b0b8a25ec089)

so I think srcStageMask should be `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT`.

**Comment by SaschaWillems** [comment]
What version of the SDK are you using?

**Comment by billgan1024** [comment]
I'm using Vulkan 1.3.250.

**Comment by SaschaWillems** [comment]
Sorry for the late reply, but I'm not able to reproduce this with the latest SDK. Sync validation is clean for me. Can you check if the issue is still present for you in the latest SDK? If so, we might incorporate your proposed fix.

**Comment by billgan1024** [comment]
The issue seems to be resolved in the latest SDK.
