### ISSUE TITLE
validation layer fires on [hpp_]hlsl_shaders

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#724]
Running on Win10 with NVIDIA GPU, I get this validation layer error when running the API sample [hpp_]hlsl_shaders:

`Validation Error: [ VUID-vkCmdDrawIndexed-SampledType-04471 ] Object 0: handle = 0x74d977000000004a, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0x5eb05e000000003b, name = View on textures/metalplate01_rgba.ktx, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x444bbaa8 | vkCmdDrawIndexed: Descriptor set VkDescriptorSet 0x74d977000000004a[] in binding #1 index 0 has a 32-bit component ImageView format (VK_FORMAT_R8G8B8A8_SRGB) but the OpTypeImage's Sampled Type has a width of 0. The Vulkan spec states: If a VkImageView with a VkFormat that has a component width less than 64-bit is accessed as a result of this command, the SampledType of the OpTypeImage operand of that instruction must have a Width of 32 (https://vulkan.lunarg.com/doc/view/1.3.243.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-SampledType-04471)
`

**Comment by SaschaWillems** [comment]
Can you update to the latest SDK (1.3.250.0) and check if the message is still present? I sadly can't reproduce it with the latest SDK.

**Comment by asuessenbach** [comment]
Indeed, it's gone.
Closing.
