### ISSUE TITLE
Exception thrown in sample full_screen_exclusive

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#731]
When running the sample full_screen_exclusive, I get an exception: read access violation.
In `FullScreenExclusive::prepare`, `window->create_surface` is called, with `window` being `nullptr`.
Produced on Win10 with NVIDIA GPU.

**Comment by SaschaWillems** [comment]
Same here. the window is null for me too. I did approve the sample and I'm 100% sure it worked back then.

Maybe broken due to #716. @tomadamatkinson can you take a look?
