### ISSUE TITLE
validation layer fires on raytracing_basic

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#734]
Running on Win10 with NVIDIA GPU, I get this validation layer error when running the extensions sample raytracing_basic:
`Validation Error: [ VUID-VkRenderPassBeginInfo-renderPass-00904 ] Object 0: handle = 0x7f79ad0000000050, type = VK_OBJECT_TYPE_RENDER_PASS; Object 1: handle = 0xa7c5450000000023, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x335edc9a | vkCmdBeginRenderPass: RenderPasses incompatible between render pass w/ VkRenderPass 0x7f79ad0000000050[] and framebuffer w/ VkRenderPass 0xa7c5450000000023[]: First dstStageMask is VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, but second dstStageMask is VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT. The Vulkan spec states: renderPass must be compatible with the renderPass member of the VkFramebufferCreateInfo structure specified when creating framebuffer (https://vulkan.lunarg.com/doc/view/1.3.243.0/windows/1.3-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-renderPass-00904)`

Followed by this one:
`Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x7f79ad0000000050, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x5c0ec5d6 | vkCmdBeginRenderPass: Hazard WRITE_AFTER_WRITE vs. layout transition in subpass 0 for attachment 1 aspect depth during load with loadOp VK_ATTACHMENT_LOAD_OP_CLEAR.`

**Comment by SaschaWillems** [comment]
Those messages seem to be caused by the UI overlay render pass and will probably also trigger in all other RT samples that use the UI overlay. Best to fix this in the framework.

**Comment by SaschaWillems** [comment]
I was about to fix these, but can no longer reproduce them with the latest SDK and sync validation enabled. It's possible that this was fixed with another PR/commit. Can you recheck on your side with SDJ 1.3.268?

**Comment by asuessenbach** [comment]
I can't reproduce this issue anymore. Closing it.
