### ISSUE TITLE
Issues with Vulkan-Samples setup for Android development

### ISSUE THREAD

**Issue by Llewi** [KhronosGroup/Vulkan-Samples#744]
I am trying to set up the Vulkan Samples as described in the Android developer guide (https://developer.android.com/ndk/guides/graphics/getting-started). I have a fresh install of Android studio (version 2022.2.1 Patch 2), and installed NDK and CMake via SDK Manager -> SDK Tools; their versions are 25.2.9519653 and 3.22.1, respectively. The env variables ANDROID_HOME and ANDROID_NDK_HOME are set as described in the guide, pointing to <...>/Android/Sdk and <...>/Android/Sdk/ndk/<versionnumber>. I also updated Path to include the Cmake bin directory. The git directory of Vulkan-Samples was cloned recursively, the generate script ran successfully.

However, when I open the project in Android studio (opening build.gradle), while the project setup does look like it should, I get an error message about a "C/C++ Configuration Problem" - not being very familiar with C++, I have no idea how to read it, but I have looked at all linked web resources and followed all setup instructions about C++ setup. The Android NDK sample also runs fine.

```

vulkan_samples.app.main | debug | arm64-v8a Compiler exited with error code 1: C:\Users\Maximilian\AppData\Local\Android\Sdk\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe -xc++ --target=aarch64-none-linux-android30 --sysroot=C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DENABLE_HLSL -DENABLE_OPT=0 -DGLSLANG_OSINCLUDE_UNIX -DROOT_PATH_SIZE=44 -DVKB_DEBUG -IC:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -DDEBUG=0 -fno-limit-debug-info -fPIC -Wall -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Wno-reorder -fno-rtti -fno-exceptions -std=c++11 -Winvalid-pch -Xclang -include-pch -Xclang C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch -Xclang -include -Xclang C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx -fpch-preprocess -v -dD -E Android (9352603, based on r450784d1) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6) Target: aarch64-none-linux-android30 Thread model: posix InstalledDir: C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin (in-process) "C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" -cc1 -triple aarch64-none-linux-android30 -E -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name compiler-file2955910248713869079 -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu generic -target-feature +neon -target-feature +v8a -target-feature +fix-cortex-a53-835769 -target-abi aapcs -fallow-half-arguments-and-returns -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a -resource-dir C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.7 -D ENABLE_HLSL -D ENABLE_OPT=0 -D GLSLANG_OSINCLUDE_UNIX -D ROOT_PATH_SIZE=44 -D VKB_DEBUG -I C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/include -D ANDROID -D _FORTIFY_SOURCE=2 -D DEBUG=0 -D ___CIDR_DEFINITIONS_END -isysroot C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -internal-isystem C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 -internal-isystem C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.7/include -internal-isystem C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include -internal-externc-isystem C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android -internal-externc-isystem C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include -internal-externc-isystem C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -Wformat -Wall -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Wno-reorder -Winvalid-pch -std=c++11 -fdeprecated-macro -fdebug-compilation-dir=C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a -ferror-limit 19 -stack-protector 2 -fno-rtti -fno-signed-char -fgnuc-version=4.2.1 -dD -include-pch C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch -include C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx -target-feature +outline-atomics -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o - -x c++ "C:\\Users\\Maximilian\\AppData\\Local\\Temp\\compiler-file2955910248713869079" clang -cc1 version 14.0.7 based upon LLVM 14.0.7git default target x86_64-w64-windows-gnu error: unable to read PCH file C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch: 'No such file or directory' ignoring nonexistent directory "C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include" #include "..." search starts here: #include ...> search starts here: C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/include C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.7/include C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include End of search list. 1 error generated. 
```

[log.txt](https://github.com/KhronosGroup/Vulkan-Samples/files/11995031/log.txt)

Android Studio still lets me "make" the project successfully, but when I run it on a device, it crashes immediately (presumably as a consequence of the C++ configuration problem).

Any tips on how to fix this?

**Comment by SaschaWillems** [comment]
This looks like the glsl third party library can't be found. Did you clone the repo with submodules?

**Comment by Llewi** [comment]
Yes, I cloned the repo recursively - I just checked again and the third party folders (including glslang) are populated.

Upon further inspection, the error message includes the following segment:
unable to read PCH file C:/Users/Maximilian/projects/Vulkan-Samples/build/android_gradle/app/build-native/Debug/1f3r1f41/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch: 'No such file or directory' ignoring nonexistent directory "C:/Users/Maximilian/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include"

Checking up on those paths, "cmake_pch.hxx.pch, it exists, but is empty, containing only a comment "generated by cmake".
The directory <...>/sysroot/include does not, there is only <...>/sysroot/usr/include.

**Comment by SaschaWillems** [comment]
That's odd. The file should not be empty. From my own experience I remember Android Studio having trouble when certain cmake versions were manually installed in path. Can you make sure that Android Studio only uses it's bundled version? E.g. by removing a manually installed cmake version, or removing it from the path.

**Comment by marty-johnson59** [comment]
Hi @Llewi, any updates on this one? Can we close this or is there more to do?  Thanks!

**Comment by Llewi** [comment]
Hey, I didn't make any progress on this anymore - I  did not have any other cmake versions, and further path modifications didn't lead anywhere.

Thanks for your input on this regardless - I'm currently caught up in other projects, feel free to close.

**Comment by AshenvaleZX** [comment]
I met the same problem: 

> vulkan_samples.app.main | debug | arm64-v8a Compiler exited with error code 1: C:\Users\zx\AppData\Local\Android\Sdk\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe -xc++ --target=aarch64-none-linux-android30 --sysroot=C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DENABLE_HLSL -DENABLE_OPT=0 -DGLSLANG_OSINCLUDE_UNIX -DROOT_PATH_SIZE=25 -DVKB_DEBUG -IF:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -DDEBUG=0 -fno-limit-debug-info -fPIC -fno-strict-aliasing -Wall -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -fno-rtti -fno-exceptions -pthread -std=c++17 -Winvalid-pch -Xclang -include-pch -Xclang F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch -Xclang -include -Xclang F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx -fpch-preprocess -v -dD -E Android (9352603, based on r450784d1) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6) Target: aarch64-none-linux-android30 Thread model: posix InstalledDir: C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin (in-process) "C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" -cc1 -triple aarch64-none-linux-android30 -E -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name compiler-file17718466973502322727 -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=non-leaf -relaxed-aliasing -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu generic -target-feature +neon -target-feature +v8a -target-feature +fix-cortex-a53-835769 -target-abi aapcs -fallow-half-arguments-and-returns -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a -resource-dir C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.7 -D ENABLE_HLSL -D ENABLE_OPT=0 -D GLSLANG_OSINCLUDE_UNIX -D ROOT_PATH_SIZE=25 -D VKB_DEBUG -I F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a/include -D ANDROID -D _FORTIFY_SOURCE=2 -D DEBUG=0 -D ___CIDR_DEFINITIONS_END -isysroot C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -internal-isystem C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 -internal-isystem C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.7/include -internal-isystem C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include -internal-externc-isystem C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android -internal-externc-isystem C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include -internal-externc-isystem C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -Wformat -Wall -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Winvalid-pch -std=c++17 -fdeprecated-macro -fdebug-compilation-dir=F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a -ferror-limit 19 -pthread -stack-protector 2 -fno-rtti -fno-signed-char -fgnuc-version=4.2.1 -dD -include-pch F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch -include F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx -target-feature +outline-atomics -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o - -x c++ "C:\\Users\\zx\\AppData\\Local\\Temp\\compiler-file17718466973502322727" clang -cc1 version 14.0.7 based upon LLVM 14.0.7git default target x86_64-w64-windows-gnu error: unable to read PCH file F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch: 'No such file or directory' ignoring nonexistent directory "C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include" #include "..." search starts here: #include ...> search starts here: F:/GitHub/Vulkan-Samples/build/android_gradle/app/build-native/Debug/e2l72412/arm64-v8a/include C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/14.0.7/include C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android C:/Users/zx/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include End of search list. 1 error generated.

**Comment by SaschaWillems** [comment]
@AshenvaleZX With #1228 we updated the Android build setup to new components, also including the Android NDK. We now require NDK 27. Looking at your error message, it seems you're still on NDK 25. Try updating and see if that fixes things.
