### ISSUE TITLE
command line arguments don't work

### ISSUE THREAD

**Issue by lobneroO** [KhronosGroup/Vulkan-Samples#760]
I wanted to check out the raytracing_basic sample, but I can't get it to run. According to the readme:

> \# For the entire usage use
> vulkan_samples --help
>
> \# For subcommand usage use
> vulkan_samples <sub_command> --help

But (on Windows 11) starting the vulkan_samples.exe with --help shows no output at all. Using a subcommand, e.g. `./vulkan_samples.exe sample --help` has the same lack of effect.

In VS 2022 I set vulkan_samples as the start up project and don't get anything either. It logs 

> An app was not requested, can not continue

and then exits the application.

**Comment by SaschaWillems** [comment]
I can reproduce this. Right now, running the help command will spawn a new console window that will immediately close. We'll take a look.

If you want to run e.g the ray tracing sample, the syntax would be:

`sample raytracing_basic`
