### ISSUE TITLE
Native code library failed to load Problems

### ISSUE THREAD

**Issue by SZU-WenjieHuang** [KhronosGroup/Vulkan-Samples#764]
<img width="973" alt="image" src="https://github.com/KhronosGroup/Vulkan-Samples/assets/82434538/987dad48-6616-45d4-a815-b46ebebd6f3e">
I built Android APK in debug mode, and there were no errors during the build process, but when running it on my phone, I encountered an issue of 'native code library failed to load', which prevented the app from opening properly.

The lib folder of the APK only contains libc++_shared.so and libVkLayer_khronos_validation.so. 
Does this mean that some files are missing? How can I solve this problem? Any advice is appreciated. Thanks.

**Comment by SaschaWillems** [comment]
Please see https://github.com/KhronosGroup/Vulkan-Samples/issues/538

You probably need to adjust your configuration

**Comment by SZU-WenjieHuang** [comment]
> Please see #538
> 
> You probably need to adjust your configuration

Hi Sascha, I still get the error after following the solution for this issue. It has lib folders in apk, but seems some .so files are missing

**Comment by SZU-WenjieHuang** [comment]
> <img alt="image" width="973" src="https://user-images.githubusercontent.com/82434538/256293808-987dad48-6616-45d4-a815-b46ebebd6f3e.png"> I built Android APK in debug mode, and there were no errors during the build process, but when running it on my phone, I encountered an issue of 'native code library failed to load', which prevented the app from opening properly.
> The lib folder of the APK only contains libc++_shared.so and libVkLayer_khronos_validation.so. Does this mean that some files are missing? How can I solve this problem? Any advice is appreciated. Thanks.

I fixed the problem by generating the gradle project again using”./scripts/generate.py android“.   

The problem seems to be caused by the lack of ***libvulkan_samples.so*** due to the third-party folder not being compiled.  

Thanks everyone :)  

Wenjie
