### ISSUE TITLE
vulkan_samples.exe don't start

### ISSUE THREAD

**Issue by PeterSikachev** [KhronosGroup/Vulkan-Samples#776]
The windows just closes immediately. When I try to run thru MSVS debug, I am stepping into the "An app was not requested, can not continue". Adding "sample raytracing_basic" to the command line doesn't help

**Comment by tomadamatkinson** [comment]
Hey @PeterSikachev if you are using the latest main branch the `raytracing_basic` has been renamed to `ray_tracing_basic`. See #735

**Comment by PeterSikachev** [comment]
> Hey @PeterSikachev if you are using the latest main branch the `raytracing_basic` has been renamed to `ray_tracing_basic`. See #735

Thanks!
I am now crashing on VK_CHECK with VK_LAYER_KHRONOS_validation, but the release is working

**Comment by tomadamatkinson** [comment]
There is a validation PR up as well see #774

**Comment by SaschaWillems** [comment]
This should be fixed now, with #774 merged. If not, feel free to open a new issue.
