### ISSUE TITLE
Does Vulkan support an analog to DX SV_'s for conservative rasterization?

### ISSUE THREAD

**Issue by PeterSikachev** [KhronosGroup/Vulkan-Samples#777]
Particularly, SV_InnerCoverage?

**Comment by DadSchoorse** [comment]
If `VkPhysicalDeviceConservativeRasterizationPropertiesEXT::fullyCoveredFragmentShaderInputVariable` is true you can use the `FullyCoveredEXT` builtin from SPV_EXT_fragment_fully_covered, it's SV_InnerCoverage as a bool.

**Comment by marty-johnson59** [comment]
Looks like this is resolved?  Closing - please re-open if there's more to be done.  Thanks!
