### ISSUE TITLE
Vulkan Instance creation is broken when using VK_EXT_VALIDATION_FEATURES_EXTENSION_NAME

### ISSUE THREAD

**Issue by lobneroO** [KhronosGroup/Vulkan-Samples#783]
I am trying to run the vulkan ray_tracing_extended sample. This used to work a few weeks back (when it was still named raytracing_extended), but I pulled the new version today and now instance creation does not work anymore. This probably is not a problem of the sample but of the entire framework though.

The error I get is:
 > [error] [framework\platform\platform.cpp:169] Error Message: Could not create Vulkan instance : ERROR_EXTENSION_NOT_PRESENT

The problematic extension seems to be VK_EXT_VALIDATION_FEATURES_EXTENSION_NAME:
If I comment out `enabled_extensions.push_back(VK_EXT_VALIDATION_FEATURES_EXTENSION_NAME);` in Vulkan-Samples/framework/core/instance.cpp (on my current main branch, this is line 226), the instance creation throws no error.
I thought this was a driver issue at first, since the querying of the extension looks correct to me, but I have tried on the following hardwarde (both on Windows 11, Visual Studio 2022):

NVidia RTX A1000 Laptop GPU, Driver version 536.96 and
NVidia RTX 2080 Ti, Driver version 536.40

The behaviour is the same on both machines: it only works, if I comment out the push_back line.

**Comment by SaschaWillems** [comment]
Thanks for raising this issue. We are already aware of it and will fix this soon with #774.

**Comment by SaschaWillems** [comment]
#774 has been merged, and this should be fixed. If not, please feel free to open a new issue.
