### ISSUE TITLE
Descriptor buffers extension is misused in a sample.

### ISSUE THREAD

**Issue by VladyslavSan** [KhronosGroup/Vulkan-Samples#792]
For complete info please check reddit post I've created https://www.reddit.com/r/vulkan/comments/1609xw5/vk_ext_descriptor_buffer_question_related_to/

@SaschaWillems you've implemented so tagging you here.

TLDR:
You use vkCmdSetDescriptorBufferOffsetsEXT function to tell that for next draw call this set layout of pipeline layout is by X offset. However, offsets you feed have distance between them of the size of one binding set has. However, set layout size != descriptor binding size.

In docs it says that set layout size >= sum of sizes of all descriptors in a set. If you query the sizes you would see that descriptor binding size is 64 but set layout size is 256 so technically you should offset them by 256 bytes and not 64. At least that's what I get when run sample on windows.

Set layout can have some internal data at bytes 65-255 that you are overwriting with the data of next set's binding.

**Comment by SaschaWillems** [comment]
Can you elaborate? The sample does not have multiple bindings per set. 

Is the sample crashing for you? If so, on what implementation?

**Comment by SaschaWillems** [comment]
And if it needs fixing, feel free to do a PR. I can't tell when I'll be able to take a closer look at this.

**Comment by VladyslavOdobesku-TomTom** [comment]
> Can you elaborate? The sample does not have multiple bindings per set.
> 
> Is the sample crashing for you? If so, on what implementation?

I've described in the comment that it works but it does not comply with the Vulkan docs. Long story short. There you assume in the code that descriptor set layout size matches the descriptor binding size in case if set layout has only one binding. However, it's not correct.

If you take a peak at the code you use `descriptor_layout_sizes` only for allocation of the GPU buffers for storing descriptors. But then when you write them you use not `descriptor_layout_sizes` but `uniform_descriptor_offset = aligned_size(descriptor_buffer_properties.uniformBufferDescriptorSize, descriptor_buffer_properties.descriptorBufferOffsetAlignment);` to calculate offsets.

Instead you should use `descriptor_layout_sizes` for getting offset of a set layout and then result of this [vkGetDescriptorSetLayoutBindingOffsetEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetDescriptorSetLayoutBindingOffsetEXT.html) to get additional offset.

I can make the PR, looks pretty easy.

**Comment by VladyslavSan** [comment]
> And if it needs fixing, feel free to do a PR. I can't tell when I'll be able to take a closer look at this.

Fix is pretty simple, I think I'll create and PR so that you can see what I'm talking about.

**Comment by VladyslavSan** [comment]
@SaschaWillems 
I've created a PR so that you can see the code and what I've meant by misuse.
https://github.com/KhronosGroup/Vulkan-Samples/pull/810

**Comment by SaschaWillems** [comment]
Closed via #810
