### ISSUE TITLE
Can't build the android apk for vulkan sample

### ISSUE THREAD

**Issue by wleebo** [KhronosGroup/Vulkan-Samples#795]
vulkan_sample/samples/extensions/shader_object/shader_object.h:28:3: error: unknown type name 'VkShaderEXT'

There is no define for the structure VkShaderEXT ???

**Comment by SaschaWillems** [comment]
Make sure to update the submodules, so the Vulkan headers are up-to-date. If that's the case and you still get the error, check CMake and make sure that you use the headers from this repo and not e.g. the ones from an outdated Vulkan SDK install.
