### ISSUE TITLE
The link in the About section is 404

### ISSUE THREAD

**Issue by yknishidate** [KhronosGroup/Vulkan-Samples#798]
The link in the About section of this repository(https://github.khronos.org/Vulkan-Samples/) is 404.

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. We are in the process of integrating the samples into the Vulkan documentation project site and will change linkage once that's live.

**Comment by SaschaWillems** [comment]
@KhronosWebservices : This refers to the link in the github about section of this repo, which I'm not allowed to change:

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/10283127/4bdf3ba3-e860-4331-bd26-0255002b19d0)

We should just remove that link completely. Could you do that?

**Comment by allcreatures** [comment]
Thank you for the heads up @SaschaWillems This link has been removed.

**Comment by SaschaWillems** [comment]
Thank you very much :)
