### ISSUE TITLE
Validation reporting broken

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Samples#80]
Validation errors are no longer reported, even when running with VKB_VALIDATION_LAYERS enabled.

#60 modified the code to add `VkDebugReportCallbackCreateInfoEXT` structure to the `pNext` for the instance create info, adding support for reporting validation errors during instance creation.  However, it also _removed_ the calls to `vkCreateDebugReportCallbackEXT`, presumably in the belief that the instance creation change was a replacement for this logic.  It is not.  While the structure chaining during instance creation gives the driver enough to report validation errors in creation, it provides no way to populate `VkDebugReportCallbackEXT debug_report_callback` for later manipulation of the reporting.

**Comment by SaschaWillems** [comment]
I noticed that too while working on the debug utils branch, this is definitely wrong and needs fixing. This also affects PR #56.
