### ISSUE TITLE
Create issues to convert GLSL to HLSL

### ISSUE THREAD

**Issue by tomadamatkinson** [KhronosGroup/Vulkan-Samples#805]
We can either use this ticket as a bucket to convert all GLSL to HLSL or we can create an issue per set of shaders. The end goal would be to have an HLSL counterpart for as many shaders as possible

Acceptance Criteria
- Decide how we want to break down the workload
- Close when GLSL shaders have a HLSL counterpart

**Comment by SaschaWillems** [comment]
I think we can close this. I already converted lots of shaders to HLSL and document my progress in #961.

**Comment by SaschaWillems** [comment]
Closing this for now, see #1014
