### ISSUE TITLE
Windows RTX 3090 latest driver GLFW error...  This should work?

### ISSUE THREAD

**Issue by pemgithub** [KhronosGroup/Vulkan-Samples#807]
```
[info] Found GPU: NVIDIA GeForce RTX 3090
[error] [framework\platform\glfw_window.cpp:40] GLFW Error (code 65542): Vulkan: Window surface creation extensions not found
[error] [framework\platform\platform.cpp:169] Error Message: Failed to create window surface.
[error] [framework\platform\platform.cpp:170] Failed when running application hello_triangle
```
The error is with any sample including hello_triangle

**Comment by SaschaWillems** [comment]
Can you add some details? What platform are you running on? What driver version? Do other Vulkan applications work?

**Comment by pemgithub** [comment]
Windows 11.  NVIDIA GeForce RTX 3090 driver version 31.0.15.3734 (Latest game ready NVIDIA driver).

Baldur's Gate 3 in Vulkan mode works.  vkcube works.

**Comment by pemgithub** [comment]
Update.  It started working after I delete GLFW and did a fresh (git pull --recurse-submodules) (git submodules init) (git submodules update), (cmake -G "Visual Studio 17 2022" -A x64 -S . -Bbuild/windows), rebuild all in vs2022.  Oops

**Comment by pemgithub** [comment]
Must've been something broken or corrupted about my setup...
