### ISSUE TITLE
Antora build is finding a bunch of broken links

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Samples#824]
This might duplicate #820, not sure - see e.g. https://github.com/KhronosGroup/Vulkan-Site/actions/runs/6452777410/job/17525321493#step:20:164 :

> [12:07:15.309] ERROR (asciidoctor): target of xref not found: docs/pull_request_template.md  
>    file: /home/runner/work/Vulkan-Site/Vulkan-Site/Vulkan-Samples/antora/modules/ROOT/pages/CONTRIBUTING.adoc  
>    source: /home/runner/work/Vulkan-Site/Vulkan-Site/Vulkan-Samples (branch: main <worktree> | start path: antora)

FWIW I have found it *immensely* helpful with the API spec to make all include:: / image: paths absolute, parameterized by asciidoctor attributes with the shared path prefix (e.g. include::{chapters}/filename.adoc[]). Then for Antora I make all of those attributes point into partials/ or images/ and symlink the actual top-level files from partials/ into pages/.

**Comment by oddhack** [comment]
Just to note that this problem still persists - there are about 27 errors reported for the Samples component in the most recent Antora build.

**Comment by SaschaWillems** [comment]
Yeah, afaik one outstanding problem that causes ost of these are the Vulkan.hpp based samples that partially duplicate contents and link to relative images, which doesn't seem to work with Antora.

We've been discussing on what to do with the Vulkan.hpp samples documentation, but haven't found a solution yet.

**Comment by SaschaWillems** [comment]
This will be fixed with #905. With that applied I get no more antora errors when building the docs site.
