### ISSUE TITLE
Wrong pragma under GCC

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/Vulkan-Samples#826]
Hi,
I saw that the macro VKBP_DISABLE_WARNINGS  has wrong behavior when compiling using GCC https://github.com/KhronosGroup/Vulkan-Samples/blob/main/framework/common/error.h#L43.

Shouldn't be GCC instead of clang?

Thanks

**Comment by tomadamatkinson** [comment]
Looks like your right!
