### ISSUE TITLE
Use Vulkan's performance counter extension in addition to hwcpipe?

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-Samples#84]
Some GPUs, like Broadcom's for example, support Vulkan's performance counter extension, but have no support in hwcpipe which is currently used for the graphs in the UI.

It would be nice if the samples could use the Vulkan extension, where available, to gather the stats for the graph.

**Comment by ghost** [comment]
I agree, we need all vendors counters working whether they use HWCPipe, the performance counter extension or something else.

**Comment by wasimabbas-arm** [comment]
I don't think it can be an _instead of_ solution. We could think about the right type of abstraction for this one but AFAIK `hwcpipe` gathers way more information than performance query extension can provide and most of our samples rely on that level of data.
