### ISSUE TITLE
M-GPU example?

### ISSUE THREAD

**Issue by zezba9000** [KhronosGroup/Vulkan-Samples#85]
Would it be possible to get a multi-gpu/m-gpu/linked-gpu example for Vulkan?

Direct3D has one: https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12LinkedGpus

Would be a good addition for people new to the API.

**Comment by ghost** [comment]
02/03 - In consideration, potential compatibility concerns.
