### ISSUE TITLE
Samples no longer compiling with Visual Studio 2022 17.8

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#852]
I just updated my VS2022 installation to the latest version 17.8 and the samples no longer compile. The new version adds some new warnings in the STL and since we treat warnings as errors, the build fails for me with this error:

```
35>V:\Vulkan-KHR-Samples\Vulkan-Samples-Fork-Private\third_party\spdlog\include\spdlog\fmt\bundled\format.h(378,18): warning C4996: 'stdext::checked_array_iterator<T*>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
```

If anyone knows how to fix this it would be very much appreciated. Maybe it's enough to update spdlog?

As a stop-gap, disabling VK_WARNINGS_AS_ERRORS works, but we should fix this as soon as possible.

**Comment by OptimisticMonkey** [comment]
Getting this as well - how to disable VK_WARNINGS_AS_ERRORS ?

**Comment by OptimisticMonkey** [comment]
Trying to build samples for first time - not sure how to disable treating the warning as an error.

**Comment by tomadamatkinson** [comment]
@OptimisticMonkey at the configure stage try to set it to OFF

cmake -Bbuild -S. -DVKB_WARNINGS_AS_ERRORS=OFF

**Comment by gpx1000** [comment]
I wonder if we should ignore C4996 warnings?

Honestly, the easiest thing to do is build in release mode; that should remove all warnings as errors.

**Comment by OptimisticMonkey** [comment]
Still struggling to build - I am using Windows and Visual Studio.  Looks like the Visual Studio Project properties have "No" set  for "Treat Warnings As Errors".  But I think it is pretty much ignoring the visual studio settings?.  Was hoping to use as a learning tool and set breakpoints and run from Visual Studio and step through code.  Seems like everything setup to use CMake instead and just run from command line?  Would be great ot be able to launch from Visual Studio and use like a regular project .....  Thanks for any advice/tips

**Comment by SaschaWillems** [comment]
Until this is fixed, the easiest way is to use cmake-gui, a UI front-end to cmake. Configure and then search for "warnings" and untick the checkbox:

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/10283127/77b811b9-33b4-4795-97a3-6b1918ddf283)

Then generate the build files again.

**Comment by OptimisticMonkey** [comment]
Thanks Sascha - cmake-gui seemed to work, I was able to generate the files with VKB_WARNINGS_AS_ERRORS off.  But when I open the sln and try to launch something like hello_triangle, I still get "error C2220: the following warning is treated as an error" all over.  

(side question - I am setting hello_triangle as startup project - is this the correct way to launch one of the examples?)

**Comment by tomadamatkinson** [comment]
I get no errors with `MSBuild version 17.7.2+d6990bcfa for .NET Framework`. Ill download the latest version of Visual Studio and try again. Are you using any other flags when building?

**Comment by SaschaWillems** [comment]
The error happens with Visual Studio 17.8, 17.7 is fine. Not sure how this related to MSBuild only or of MS already updated that.

**Comment by tomadamatkinson** [comment]
`MSBuild version 17.8.3+195e7f5a3 for .NET Framework` shows the errors 🎉 

Looks specific to the version of fmt included with spdlog... I tried bumping spdlog without success. Using an external fmt also doesn't work as it looks like spdlog is quite far behind in fmt versions... Or at least thats what it looks like from the logs

@gpx1000 suggestion of disabling the specific warning might be the best way forward for the near future

**Comment by tomadamatkinson** [comment]
Ah wait. I checked out master which is 5 years old... My bad. Ill try the more up to date branches

**Comment by tomadamatkinson** [comment]
Using spdlog v2.x latest works. We need to bump our CXX_STANDARD to 17 and I had to remove a small part of their CMake as their usage assumed that their project was the root project

The broken spdlog commit was `cc343cd1`

**Comment by tomadamatkinson** [comment]
Try building this when you get a chance https://github.com/KhronosGroup/Vulkan-Samples/pull/854 😄

I just checked out the commit before the broken one. I will submit an issue for a proposed fix to spdlog

**Comment by tomadamatkinson** [comment]
`spdlog v1.12.0` also works for me. This version doesn't require a CXX bump and so i have opted for this over v2
