### ISSUE TITLE
Compiling on Linux makes my PC freeze.

### ISSUE THREAD

**Issue by BadWinston** [KhronosGroup/Vulkan-Samples#885]
I followed your instructions from https://github.com/KhronosGroup/Vulkan-Samples/blob/main/docs/build.adoc#linux.
I cloned the repository to my pc.
I ran command: cmake -G "Unix Makefiles" -Bbuild/linux -DCMAKE_BUILD_TYPE=DEBUG
Pass, no errors.
I ran command: cmake --build build/linux --config Release --target vulkan_samples -j$(nproc)
At 48% compiling progress my pc was not responding anymore.
I rebooted and launched the linux taskmanager and ran the second command again.
My pc froze at 52% compiling progress with a 100% memory usage.
I have 8 GB of memory, that should be enough to compile examples, I think.
Apparently there are gcc processes who never terminate each of approx. 500 MB.

**Comment by tomadamatkinson** [comment]
Hey @BadWinston, this is likely due to nproc reading empty on your system. Try running the command with a fixed number of threads like 4 or 8. For instance `cmake --build build -- -j 8`

**Comment by BadWinston** [comment]
Command
cmake --build build/linux --config Release --target vulkan_samples -j 4
worked indeed.
Thank you for your time and quick correct response!

**Comment by BadWinston** [comment]
Command
cmake --build build/linux --config Release --target vulkan_samples -j 4
worked indeed.
Thank you for your time and quick correct response!
