### ISSUE TITLE
CMake configuration order of operations is incorrect

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Samples#896]
The [code](https://github.com/KhronosGroup/Vulkan-Samples/blob/5e4e3d20b3a86f7814e026042341cf34ef530edd/CMakeLists.txt#L31) near the beginning of the root CMakeLists.txt reads as follows

```cmake
if(DEFINED CMAKE_C_COMPILER_LAUNCHER)
if(WIN32)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        string(REPLACE "/Zi" "/Z7" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
        string(REPLACE "/Zi" "/Z7" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
    elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
        string(REPLACE "/Zi" "/Z7" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
        string(REPLACE "/Zi" "/Z7" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
    elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
        string(REPLACE "/Zi" "/Z7" CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
        string(REPLACE "/Zi" "/Z7" CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
    endif()
endif()
endif()
```

However, these lines are all placed before `project(vulkan_samples)`, which is when the compiler is detected and all of these `CMAKE_<LANG>_FLAGS_<TYPE>` flags are initialized.

Additionally, MSVC is a multi-config build system, so `CMAKE_BUILD_TYPE` is almost never populated at configure time.  When the project is actually built, for instance with `cmake --build`, this code won't even be processed because it's only triggered at configure time.

**Comment by SaschaWillems** [comment]
Fixed with #897.

@jherico : If you put a line like "Fixes #896" into the PRs description, any related issue will be closed automatically when the respective PR is merged.
