### ISSUE TITLE
Missing link in extensions readme

### ISSUE THREAD

**Issue by jeroenbakker-atmind** [KhronosGroup/Vulkan-Samples#898]
https://docs.vulkan.org/samples/latest/samples/extensions/README.html contains a missing link to https://docs.vulkan.org/samples/latest/samples/README.adoc#extension-samples

As the samples are now navigatable via docs.vulkan.org listing them might still be useful for people who search directly in github.

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. This is also the case for other samples folders like performance. I'll fix this.
