### ISSUE TITLE
Difference in Memory Budget

### ISSUE THREAD

**Issue by Sukriti-sood** [KhronosGroup/Vulkan-Samples#919]
I’m currently utilizing the Memory Budget extension on my system. However, I’ve noticed a significant discrepancy between the usage displayed in the output and the actual value indicated by the Task Manager. Could this be an error, or is there another explanation for this difference?

![Difference](https://github.com/KhronosGroup/Vulkan-Samples/assets/55010599/fe74baa4-38c4-4c9c-a0a8-e183ed35cc3a)

**Comment by SaschaWillems** [comment]
Don't use the task manager for GPU statistics. It's often wrong or misleading. Compare with a proper tool, e.g. nvidia's overlay.

Also values reported VK_EXT_memory_budget may have some limitations, see https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_memory_budget.html (see "current process").

**Comment by Sukriti-sood** [comment]
Okay Thanks @SaschaWillems . Got it.
