### ISSUE TITLE
Having issue with cmake and building

### ISSUE THREAD

**Issue by ThorMalleuson** [KhronosGroup/Vulkan-Samples#92]
I have followed the instructions for the Window build.  Have Python in PATH and have the updated LLVM (9.0.0) and am using the Visual Studio Developer Powershell to build.  This is what I see on the console.  I am not sure what I am doing wrong.
PS C:\VulkanSamples> cmake .\CMakeLists.txt
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.24.28319.0
-- The CXX compiler identification is MSVC 19.24.28319.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Debug VC++ CRT: MDd
-- Using Release VC++ CRT: MD
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPythonInterp.cmake:126 (execute_process):
  execute_process attempted to output into a file: into a source directory.
Call Stack (most recent call first):
  third_party/spirv-cross/CMakeLists.txt:133 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/VulkanSamples/CMakeFiles/CMakeOutput.log".

**Comment by TomAtkinsonArm** [comment]
Hi @ThorMalleuson,
This looks like the third party submodules have not been initialised. Can you confirm that you have run `git submodule update --init`

**Comment by MichaelParkinWhite** [comment]
I also had issues with spirv-cross when not specifically using CMake 3.10.2, no idea why, didn't have the time to thoroughly investigate, but newer versions kicked up odd errors, though this error seems different in nature.

**Comment by ThorMalleuson** [comment]
@TomAtkinsonArm 
Yes, I have.  Same error.  I deleted everything and recloned too via "git clone --recurse-submodules https://github.com/KhronosGroup/Vulkan-Samples.git". Same error.

**Comment by ThorMalleuson** [comment]
> I also had issues with spirv-cross when not specifically using CMake 3.10.2, no idea why, didn't have the time to thoroughly investigate, but newer versions kicked up odd errors, though this error seems different in nature.

If I go to the third party directory for spirv-cross and run CMake there it builds the project files for Visual Studio fine and alll of the various projects build without error.

**Comment by TomAtkinsonArm** [comment]
Hi, as Micheal said it is known to build with CMake 3.10.2. I am using 3.16.0 without issue. Try downgrading and seeing if you can get the project to run. In the mean time we are investigating this further :)

Hope this helps

**Comment by ThorMalleuson** [comment]
Thank you Tom.  Will try the downgrade later this afternoon and will report results.  Thanks again.

**Comment by TomAtkinsonArm** [comment]
Any news on this @ThorMalleuson?

**Comment by ThorMalleuson** [comment]
Downgraded to both 3.10.2 and 3.16.7 (there wasn't a 3.16.0 available) and it still will not create the projects.

PS C:\Vulkan-Samples> cmake .\CMakeLists.txt
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Debug VC++ CRT: MDd
-- Using Release VC++ CRT: MD
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPythonInterp.cmake:126 (execute_process):
  execute_process attempted to output into a file: into a source directory.
Call Stack (most recent call first):
  third_party/spirv-cross/CMakeLists.txt:133 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Vulkan-Samples/CMakeFiles/CMakeOutput.log".

**Comment by SaschaWillems** [comment]
You need to specify a separate build directory instead of trying to create the build files in the root directory of the project.

**Comment by ThorMalleuson** [comment]
Got it.  The issue was is that I copied and pasted the command "cmake -G"Visual Studio 15 2017 Win64" -H. -Bbuild/windows" from the home page (changing the version of Visual Studio".  It was not working due to the "." after the "-H" switch.

Thank you.

**Comment by ghost** [comment]
Resolved.
