### ISSUE TITLE
GUI scaling issues

### ISSUE THREAD

**Issue by JoseEmilio-ARM** [KhronosGroup/Vulkan-Samples#93]
![image](https://user-images.githubusercontent.com/33630720/76942557-d7803000-68f5-11ea-97ff-5a3727b136b9.png)

All samples show the GUI incorrectly on a system with RX 5700 XT, windows, 4K and 200% scaling.
Setting the system to 100% scaling fixes it.

**Comment by JoseEmilio-ARM** [comment]
Hi @aurolou I can't remember for certain but I think you also experienced this issue? If so could you please check if this patch fixes it? https://github.com/KhronosGroup/Vulkan-Samples/pull/156

**Comment by aurolou** [comment]
yes, it does fix it for me! :)

**Comment by JoseEmilio-ARM** [comment]
Great thanks for checking :)
