### ISSUE TITLE
cmake fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by mutantbob** [KhronosGroup/Vulkan-Samples#930]
After installing the dependencies I 
`cmake -G "Unix Makefiles" -Bbuild/linux -DCMAKE_BUILD_TYPE=Release`
unfortunately, it gives a great many errors, starting with 
```
CMake Error at third_party/CMakeLists.txt:232 (add_subdirectory):
  The source directory

    /home/thoth/vendor/Vulkan-Samples/third_party/glslang

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:245 (target_compile_options):
  Cannot specify compile options for target "glslang" which is not built by
  this project.
```

I am not sure if this is a mistake in the build system, or if the build instructions left out a step, or if Ubuntu 20 is not supported.

[explode.txt](https://github.com/KhronosGroup/Vulkan-Samples/files/14365848/explode.txt)

[CMakeOutput.log](https://github.com/KhronosGroup/Vulkan-Samples/files/14365849/CMakeOutput.log)

**Comment by SaschaWillems** [comment]
This looks like you forgot to initialize/fetch the submodules. Either use `--recurse-submodules` when cloning, or (afterwards) do a `git submodule init` and `git submodule update`.
