### ISSUE TITLE
Render subpasses sample issues on some platforms

### ISSUE THREAD

**Issue by JoseEmilio-ARM** [KhronosGroup/Vulkan-Samples#94]
Render Subpasses sample shows flickering and fails to render using renderpasses on some platforms (Adreno 540).

Seems to get fixed after forcing a swapchain re-creation.
Video: [render_passes_bug.zip](https://github.com/KhronosGroup/Vulkan-Samples/files/4348900/render_passes_bug.zip)

**Comment by carlosadcq** [comment]
Thanks for reporting this Jose, we have reproduced this internally and are investigating it.

**Comment by ghost** [comment]
@carlosadcq - did this get resolved?

**Comment by carlosadcq** [comment]
I'm not sure how this only  has manifested on Adreno GPUs. The main problem is that the resource_cache system only uses the ImageView for the hash. When switching between toggles (for example transient attachments enable/disable) the FBO's get recreated which includes images and image views being destroyed and recreated. This can lead to situations where handles are reused and a new ImageView is created with same handle but using a different Image. With the fix linked above this is 'fixed' but I think we may need to clear the cache every time the render context is recreated. I don't know where's the best place to put this though as I'm not 100% familiar with the framework yet. My initial thoughts were that maybe at the end of the `void RenderContext::recreate()` function it may make most sense to clear the cache (device.get_resource_cache().clear_framebuffers();) as at that point the original images and image views have been destroyed and recreated.

**Comment by MikalRodli-ARM** [comment]
@carlosadcq 
I have tried out the fix/workaround above and I am still noticing flickering/artifacts on Adreno650 when toggling between the render techniques.
Toggling between the other options multiple times also causes similar issues.

**Comment by carlosadcq** [comment]
Thanks for testing this @MikalRodli-ARM, I've replied with some findings in the PR but just to summarize, this seems like it is more than one issue which all manifest in flickering. Older devices/drivers seem good now with the changelist but not on newer ones (as you pointed out). I'll continue to investigate and hopefully fix this asap.
