### ISSUE TITLE
mobile_nerf references non-existent assets

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Samples#943]
https://github.com/KhronosGroup/Vulkan-Samples/blob/216e0652efe7b302b7b1eeb6b12116c34b102eb3/samples/general/mobile_nerf/mobile_nerf.cpp#L215

**Comment by SaschaWillems** [comment]
It seems we forgot to update the assets submodule. Thanks for noticing.

**Comment by jherico** [comment]
The assets submodule points to this commit which doesn't have the assets

https://github.com/KhronosGroup/Vulkan-Samples-Assets/tree/f55f67fd3c5a9f9208ab9e646b02ff11917fa4ce/scenes
