### ISSUE TITLE
An app was not requested, can not continue

### ISSUE THREAD

**Issue by yuhenmeili** [KhronosGroup/Vulkan-Samples#955]
see ![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/8412761/36270fe3-f115-41d3-8fb0-5a7f54682cb3)
enviroment: windows 10 debug x64 with vs 2022
code branch: master

**Comment by SaschaWillems** [comment]
How do you run the samples? You need to specify a sample to run as an argument, e.g. `sample hello_triangle`

**Comment by yuhenmeili** [comment]
> How do you run the samples? You need to specify a sample to run as an argument, e.g. `sample hello_triangle`

ok, i got it ,thanks,i need add argument in vs 2022

**Comment by yuhenmeili** [comment]
close

**Comment by tomadamatkinson** [comment]
Reopened this issue as we should make this warning more suitable. Samples users should be given a help prompt if the application could not continue
