### ISSUE TITLE
Remove tests/system_test

### ISSUE THREAD

**Issue by tomadamatkinson** [KhronosGroup/Vulkan-Samples#959]
The system tests are rarely used and do not really test anything useful to the samples. The closest feature we have to a full system test is `vulkan_samples batch` mode. 

Framework V2 intends to encourage the addition of unit tests. Vulkan framework unit tests can be added and ran locally in the future.

Due to the system tests not being used and likely future implementations of a system test will be built on top of batch mode or as units should we remove this folder?

**Comment by SaschaWillems** [comment]
I'm fine with removing it. I guess that would also remove the CI steps, thus resulting in faster CI builds?

**Comment by tomadamatkinson** [comment]
Doesn't impact our current CI as these tests are not used in practice. It will simplify some of the projects code though so i think it is still worth it
