### ISSUE TITLE
I am a beginner, emmmmm.

### ISSUE THREAD

**Issue by GongXiangXYZ** [KhronosGroup/Vulkan-Samples#966]
I just git clone，cmake, open the .sln and F5, it can run，but I can see no sample.
（My pc is ok, it can run https://github.com/SaschaWillems/Vulkan）

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/160806913/f27a0965-5ab2-40c4-8c83-ff143291a183)

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/160806913/7b279ec9-9570-4680-8d75-ab075929091b)

**Comment by SaschaWillems** [comment]
You need to specify the sample you want to run as an argument, e.g.

```sample hello_triangle```

We're working on improving the help message to make this more clear. The message currently displayed isn't very helpful.

**Comment by GongXiangXYZ** [comment]
ok, I got it. 

It would be better that push F5 then see some samples.   :)

**Comment by SaschaWillems** [comment]
That's technically not possible. This repo is differently structured than my samples (where each sample is a separate project). But we'll try to improve at least the messaging, so users can easily see how they can run a sample and what samples are available. The current wall of text in cases like yours aren't very helpful.

**Comment by GongXiangXYZ** [comment]
> That's technically not possible. This repo is differently structured than my samples (where each sample is a separate project). But we'll try to improve at least the messaging, so users can easily see how they can run a sample and what samples are available. The current wall of text in cases like yours aren't very helpful.

that error line make me nervous, "Why ? I did nothing.", BTW thanks for your reply.

**Comment by SaschaWillems** [comment]
Yes, that error is misleading. We'll fix that with #968
