### ISSUE TITLE
./scripts/generate.py android build.gradle does not compile on android studio 2023.2.1

### ISSUE THREAD

**Issue by goofyseeker311** [KhronosGroup/Vulkan-Samples#975]
command: "./scripts/generate.py android" generated build.gradle does not build directly on android studio 2023.2.1.

why does not the download of the repo contain the files it claims to contain in the third party directory in github.
those were not extracted at all. or are not in the zip file at all. oh was not a deep link copy download.

this is a github feature by design not a bug?

errors more specifically:

CMake Error at third_party/CMakeLists.txt:232 (add_subdirectory):
  The source directory

    C:/stuff/data/projects/androidprojects/Vulkan-Samples-main/third_party/glslang

  does not contain a CMakeLists.txt file.

CMake Error at third_party/CMakeLists.txt:271 (add_subdirectory):
  The source directory

    C:/stuff/data/projects/androidprojects/Vulkan-Samples-main/third_party/spirv-cross

  does not contain a CMakeLists.txt file.

**Comment by SaschaWillems** [comment]
> this is a github feature by design not a bug?

That's a github problem and nothing we can do anything about. The source code download provided by github never contains submodules.

Best is to checkout the repo with submodules just as noted in our build documentation.

**Comment by goofyseeker311** [comment]
which requires install even more software, like git-scm. I reported this to the github feedback section, a deep copy option from the web would prevent extra work for all.

**Comment by SaschaWillems** [comment]
Let's hope they do something about it. But it's (sadly) nothing we can change on our end.

**Comment by goofyseeker311** [comment]
actually you can do a local copy of the third party dependencies. you know they can break the whole repo with one change.

self-contained releases would not be broken by random linked changes. much better to be integrated than sparse.

**Comment by tomadamatkinson** [comment]
Submodules are pinned to a specific commit and haven't caused any issues for this projects lifetime. They also make it easy to bump dependencies - no need to copy source.

There are alternatives such as vcpkg or CPM which can pull dependencies automatically. But these rely on either well maintained CMake third parties or well maintained ports in vcpkg.

We don't actively support GitHub Releases or GitHub source downloads other than with git

**Comment by goofyseeker311** [comment]
if the web interface does not provide all the functionality then why make a web interface? well just arguing for web instead of tools. nothing more to add here.

so you chose sparse instead of integrated approach. for the record I hate the sparse dependent model of everything. just imho.
the whole download as deep clone zip is 2gigs tho.

 why 2gigs worth of dependencies? where are they needed. not at runtime package. reason for bloat in the sparse model is clear. everything is included. also that what is not necessary for the app.
edit: final compiled repo with all dependencies is 4gigs compressed.

and the git checkout does not even include everything, like what is downloaded by checkout_glslang_spirv_tools.sh and build_glslang_spirv_tools.sh.

edit: at least the vulkan-samples repo now compiles and launches on android.

edit: more complex approach (sparse) results in more support requests, when things dont just work.
