### ISSUE TITLE
Third-party folder isn't excluded from CI checks

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Samples#98]
I'm trying to add a new example that depends on GLAD, but it's failing the CI check because of the copyright-headers, clang-tidy and clang-format checks, which should not be applied to content in the third-party folder.

**Comment by SaschaWillems** [comment]
All third party libraries must be included as sub modules. So if you add another one like GLAD you need to add it as a sub module instead of explicitly putting it into the third party folder. That way it's skipped (or not even checked out) during those CI checks.
